### PR TITLE
all: change remaining usage codes of 2 to 1 for GNU compat

### PR DESCRIPTION
**Pull request by tertsdiepraam**
Closes https://github.com/uutils/coreutils/issues/3102

Changes the exit code for the utils below from 2 to 1. A few utils remain with more complicated errors.

- [x] arch
- [x] basename
- [x] chgrp
- [x] chmod
- [x] chown
- [x] cksum
- [x] comm
- [x] csplit
- [x] cut
- [x] date
- [x] dd
- [x] df
- [x] dircolors
- [x] dirname
- [x] du
- [x] expand
- [x] factor
- [x] fmt
- [x] fold
- [x] groups
- [x] head
- [x] hostname
- [x] id
- [x] install
- [x] join
- [x] kill
- [x] link
- [x] ln
- [x] logname
- [x] mkdir
- [x] mkfifo
- [x] mknod
- [x] mv
- [x] nl
- [x] nproc
- [x] numfmt
- [x] od
- [x] paste
- [x] pathchk
- [x] pinky
- [x] ptx
- [x] pwd
- [x] readlink
- [x] rm
- [x] rmdir
- [x] seq
- [x] shred
- [x] shuf
- [x] split
- [x] stat
- [x] stty
- [x] sum
- [x] sync
- [x] tac
- [x] tail
- [x] tee
- [x] touch
- [x] tr
- [x] tsort
- [x] uname
- [x] unexpand
- [x] uniq
- [x] unlink
- [x] uptime
- [x] users
- [x] wc
- [x] who
- [x] whoami
- [x] yes

### CODE REVIEW

**Comment by sylvestre** [comment]
do you think we could have a test to verify that we don't regress? :)

**Comment by tertsdiepraam** [comment]
I was worried you were gonna ask that :) I've added a simple test for all the utils.

**Comment by sylvestre** [comment]
ah ah, yeah, I am quite predictable :) isn't it @calixteman ? :)

**Comment by calixteman** [comment]
> ah ah, yeah, I am quite predictable :) isn't it @calixteman ? :)

Oh yeah 😄

**Comment by tertsdiepraam** [comment]
I've now included some more utils that were off (like the ones that should return 125) and I included tests for them.

**Comment by sylvestre** [comment]
Nice side effect
`Warning: Congrats! The gnu test tests/misc/env is no longer failing!`

**Pull request merged**
