### PR TITLE
Implement pr

### PR DESCRIPTION
**Pull request by tilakpatidar**

### CODE REVIEW

**Comment by Arcterus** [comment]
Sorry for the late response, but would you mind rebasing this?  I'll try to review this in the next week or so, but just looking over the tests, some of them seem excessively long.  If you could shorten them, that'd probably be ideal.

**Comment by tilakpatidar** [comment]
I will rebase this over the weekend. I agree that some tests are excessively long but pr command contains a lot of formatting options. The test cases are copied from the gnu utils itself to ensure consistency. I will surely try to shorten them.

**Comment by sylvestre** [comment]
@tilakpatidar Sorry, I am just taking over the maintenance of coreutils. Are you still interested in landing it? If so, could you please rebase your change? thanks

**Comment by sylvestre** [comment]
Moved here:
https://github.com/uutils/coreutils/pull/1918
(credits are keep)

**Pull request closed without merging**
