### PR TITLE
Make chmod use std where possible instead of libc; compile for Redox

### PR DESCRIPTION
**Pull request by ids1024**

### CODE REVIEW

**Comment by Arcterus** [comment]
Does this still work with the setuid, setgid, and sticky bits?  I just want to make sure before I merge this because, IIRC, I had to use stuff from `libc` to get them to work when I first wrote `chmod`.

**Comment by ids1024** [comment]
It appears to work.

**Comment by Arcterus** [comment]
Can you add a note in the help message that `umask` is not respected on Redox (if it's applicable, not too familiar with Redox atm)?

The build seems to fail on OS X because `mode_t` is a `u16`, so casting `last_mask` to a `u32` should fix it.

**Comment by ids1024** [comment]
I've added a comment to the code about umask on Redox; it isn't currently implemented by Redox.

**Comment by Arcterus** [comment]
Thanks :)

**Pull request merged**
