### PR TITLE
Add instructions for code coverage report generation

### PR DESCRIPTION
**Pull request by sivachandran**

### CODE REVIEW

**Comment by qarmin** [comment]
I would add such instructions to different file e.g. `Developer Instruction.md` or something similar to not bloat `README.md` since not too much people will use this feature.

**Comment by sylvestre** [comment]
Yeah, good point. @sivachandran could you please move it into a different file? thanks :)

**Comment by sivachandran** [comment]
Moved the instructions to `DEVELOPER_INSTRUCTIONS.md` (followed existing file naming convention).

**Comment by sylvestre** [comment]
Excellent, thanks!

**Pull request merged**
