### PR TITLE
Fix wc gnu test suite compatibility 3678

### PR DESCRIPTION
**Pull request by gkalas8**
This is a pull request reopening https://github.com/uutils/coreutils/pull/3679 . 3679 was deleted because I removed my git repo as I accidentally forked from a fork already and wanted to clean up my fork.

This change will extract a utility already present in ls to uucore.
This utility is used by dir and vdir too, which are adjusted to
look it up in uucode. No further changes to ls, dir or dirv intended.

The change here largely fiddles with the output of uu_wc to match
that of GNU wc. This is the case to the extent to make unit tests
pass, however, there are differences remaining. One specific
difference I did not tackle is that GNU wc will not align the
output columns (compute_number_width() -> 1) in the specific case
of the input for --files0-from=- being a named pipe, not real stdin.
This difference can be triggered using the following two invocations.

wc --files0-from=- < files0 # use a named pipe, GNU does align
cat files0- | wc --files0-from=- # use real stdin, GNU does not
align.

### CODE REVIEW

**Comment by sylvestre** [comment]
Fail to build:
```

error[E0428]: the name `test_gnu_compatible_quotation` is defined multiple times
   --> /Users/runner/work/coreutils/coreutils/tests/by-util/test_wc.rs:137:1
    |
124 | fn test_gnu_compatible_quotation() {
    | ---------------------------------- previous definition of the value `test_gnu_compatible_quotation` here
...
137 | fn test_gnu_compatible_quotation() {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `test_gnu_compatible_quotation` redefined here
    |
    = note: `test_gnu_compatible_quotation` must be defined only once in the value namespace of this module

```

**Comment by sylvestre** [comment]
looks good here:
`Warning: Congrats! The gnu test tests/misc/wc-files0 is no longer failing!`

**Comment by sylvestre** [comment]
could you please rebase the stack of patches? too many merge, fix up, etc

`git rebase -i origin/main`
should do it

**Comment by anastygnome** [comment]
@sylvestre I had suashed it all and he force pushed.......

[f0242e2](https://github.com/uutils/coreutils/pull/3685/commits/f0242e2a91febc9a196bea1a12a18a92cfeb5a1a)[f0242e2](https://github.com/uutils/coreutils/pull/3685/commits/f0242e2a91febc9a196bea1a12a18a92cfeb5a1a) ?

**Comment by sylvestre** [comment]
```
$ git reset --hard origin/main && git cherry-pick 04beea9 f0242e2
HEAD est maintenant à 64bc20c2d Merge pull request #3686 from cakebaker/show_error_if_padding_is_zero
fatal: bad revision '04beea9'

```

**Comment by anastygnome** [comment]
@sylvestre I'll open a PR with it on my side :)

**Comment by sylvestre** [comment]
done here: 
https://github.com/uutils/coreutils/pull/3688

**Pull request closed without merging**
