### PR TITLE
ls: Implement new sort option --sort=width 

### PR DESCRIPTION
**Pull request by Skryptonyte**
This option was introduced in some more recent versions of GNU coreutils (around 2021-4-11) which lets you sort by filename widths .

One oddity of this particular option in GNU coreutils is that unlike other sort options, this one does not have a shorthand form flag so I have implemented it similarly as such here.

### CODE REVIEW

**Comment by cakebaker** [comment]
Thanks for your PR!

Can you please run `cargo fmt`?

**Review by cakebaker — COMMENTED** [review]
What happens if you have multiple file names with the same width?

**Comment by Skryptonyte** [comment]
Right, now it should fall back to alphabetic sorting in those cases. Also extended the test case to check for those as well.

**Comment by cakebaker** [comment]
Great work, thanks :)

**Pull request merged**
