### PR TITLE
nohup: improve test coverage

### PR DESCRIPTION
**Pull request by cre4ture**
as requested in #1857

I was able to simulate a terminal such that we can test the code in function "replace_fds"

EDIT: this PR is probably replaced by this: #5869

### CODE REVIEW

**Comment by cre4ture** [comment]
CI/CD reported +15.46% testcoverage for nohup.rs :-)

**Comment by cakebaker** [comment]
I don't know whether you have seen that the test fails on FreeBSD/macOS?

**Comment by cre4ture** [comment]
> I don't know whether you have seen that the test fails on FreeBSD/macOS?

thanks for pointing out. there are so many unrelated error currently that it gets difficult to see the real issues

**Comment by cre4ture** [comment]
closed in favor of https://github.com/uutils/coreutils/pull/5869

**Pull request closed without merging**
