### PR TITLE
quick Makefile tweak ; update chmod ; update chroot

### PR DESCRIPTION
**Pull request by kwantam**
Three commits:

1. Tweak Makefile so that when the make goal is `test` it only considers the `TESTS` variable when building dependencies.

2. Updates in chmod. Works, but I suspect it will have issues with non-UTF-8 filenames. This was probably always the case, though.

3. Updates in chroot (and in `src/common/c_types.rs`). Two things here:

* For now, one of the fixes in c_types is slightly hacky (specifically: I commented out the `Copy` impls for several of the structs), but this will get fixed as necessary for other utils.

* The call to the chroot function seems to fail in some cases. I am still investigating this, but I ran out of time for now.

### CODE REVIEW

**Comment by Heather** [comment]
Thank you.

Why `&a[..]` and not `.as_ref()`

**Comment by kwantam** [comment]
To be honest I don't think it makes a difference, I'm just used to using `&a[..]`. I can revert if you prefer `a.as_ref()`.

**Comment by Heather** [comment]
@kwantam don't need to revert, there are more important things just asked about if there is specifc case, however `as_ref` looks more readable for me personally

**Comment by ctjhoa** [comment]
@Heather I agree `as_ref` is more readable specially for rust beginner.

**Pull request merged**
