### PR TITLE
Use sccache to cache build results

### PR DESCRIPTION
**Pull request by sylvestre**
instead of Swatinem/rust-cache@v2

After that PR, GNU's jobs are next

### CODE REVIEW

**Comment by sylvestre** [comment]
We look good:
```
/opt/hostedtoolcache/sccache/0.4.0-pre.9/x64/sccache --show-stats
Compile requests                    377
Compile requests executed           240
Cache hits                          226
Cache hits (C/C++)                   48
Cache hits (Rust)                   178
Cache misses                         13
Cache misses (Rust)                  13
Cache timeouts                        0
Cache read errors                     0
Forced recaches                       0
Cache write errors                    0
Compilation failures                  1
Cache errors                          0
Non-cacheable compilations            0
Non-cacheable calls                 135
Non-compilation calls                 2
Unsupported compiler calls            0
Average cache write               0.143 s
Average compiler                  0.582 s
Average cache read hit            0.000 s
Failed distributed compilations       0

Non-cacheable reasons:
incremental                          75
crate-type                           55
unknown source language               4
-                                     1

Cache location                  ghac, name: sccache-v0.4.0-pre.9, prefix: /sccache/
Version (client)                0.4.0-pre.9
```

**Comment by tertsdiepraam** [comment]
Cool! You're still using `Swatinem/rust-cache` in a few places, do we need both there? Or is that just to get access to the Rust toolchain?

**Comment by sylvestre** [comment]
It seems that they are caching different things

**Comment by tertsdiepraam** [comment]
Alright! There's no harm in having both either I suppose.

**Pull request merged**
