### PR TITLE
publish: by default, put it as draft

### PR DESCRIPTION
**Pull request by sylvestre**
to send email only when ready
closes: #6859

### CODE REVIEW

**Review by williamdes — APPROVED** [review]
How do you generate release notes ?

**Comment by sylvestre** [comment]
Github generates the list and I organize them myself

**Review by cakebaker — APPROVED** [review]
I can't say whether this change is correct, I guess we will see it with the next release.

**Comment by williamdes** [comment]
> Github generates the list and I organize them myself

Maybe it would save some minutes to pre fill the contents then

**Pull request merged**
