### PR TITLE
Default environment variables for tests

### PR DESCRIPTION
**Pull request by tertsdiepraam**
Closes https://github.com/uutils/coreutils/issues/4586 and hopefully also https://github.com/uutils/coreutils/issues/4253 but I won't let it close the latter automatically.

### CODE REVIEW

**Comment by tertsdiepraam** [comment]
I think the DST test I changed was actually broken since https://github.com/uutils/coreutils/pull/3319?

**Comment by anastygnome** [comment]
@tertsdiepraam If I'm not mistaken, DST comes back into effect on Sunday at 1AM UTC, or thereabouts. This gives us some time to fix it

**Comment by sylvestre** [comment]
touch: move from time to chrono

Maybe in a separate PR ?

**Comment by tertsdiepraam** [comment]
Yeah that's probably better

**Pull request merged**
