### PR TITLE
fix: seq panic on no arguments #4749

### PR DESCRIPTION
**Pull request by NikolaiSch**
This is in reference to issue #4749, where just running `seq` ends up panicking. I have added a new `NoArguments` error, and refactored the display formatting, in order to match GNU messages.

### CODE REVIEW

**Comment by sylvestre** [comment]
please fix the clippy warning and add a test to make sure we don't regress 
thanks

**Comment by NikolaiSch** [comment]
> please fix the clippy warning and add a test to make sure we don't regress 
> 
> thanks

however i have a question, that made clippy fail for me, selinux was not imported correctly for me, but i didn't change any of that code, so what should my next approach be?

**Comment by tertsdiepraam** [comment]
I don't understand. Following the clippy lint made clippy fail because of selinux? Or selinux is making clippy fail in general? In the latter case, turning off the `feat_selinux` feature should help.

**Comment by cakebaker** [comment]
@NikolaiSch ping?

**Comment by sylvestre** [comment]
I fixed the clippy warnings

**Comment by cakebaker** [comment]
Thanks :)

**Pull request merged**
