### PR TITLE
Bump MSRV to 1.60

### PR DESCRIPTION
**Pull request by tertsdiepraam**
Unblocks:
- Clap 4.0 (https://github.com/uutils/coreutils/pull/3991)
- PHF 0.11 (https://github.com/uutils/coreutils/pull/3795, https://github.com/uutils/coreutils/pull/3794)
- bstr 1.0 (https://github.com/uutils/coreutils/pull/3930)

Do we want to do a release before this?

### CODE REVIEW

**Comment by sylvestre** [comment]
If you are motivated to do a new release, please go ahead :)

**Comment by tertsdiepraam** [comment]
I'll try to do that this week. Not sure when I have the time :)

**Comment by sylvestre** [comment]
@tertsdiepraam still planning to do a release ?

**Comment by tertsdiepraam** [comment]
Yes! Either tomorrow or the day after.

**Pull request merged**
