### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by aarzee**

### CODE REVIEW

**Comment by Heather** [comment]
may you get rid of this merge commit here? (it's regularry easy to avoid by rebasing your fork branch before making pull request)

**Comment by aarzee** [comment]
I'm not very familiar with git; what command(s) would I use here?

**Comment by ebfe** [comment]
Assuming uutils/coreutils is your `origin` remote and you are in your pull-request branch:

`git fetch origin`
`git rebase origin/master`

Then force push.

Further reading: https://git-scm.com/book/en/v2/Git-Branching-Rebasing

**Comment by aarzee** [comment]
Thanks. Done.

**Comment by ebfe** [comment]
It looks like you rebased on top of the wrong branch.

**Comment by ebfe** [comment]
... or rebased the wrong branch.

**Comment by aarzee** [comment]
Yep, rebased on the wrong branch.

**Comment by aarzee** [comment]
Tried again, is that correct?

**Comment by ebfe** [comment]
Yes this looks good.

**Pull request merged**
