### PR TITLE
Fix overflow error on WSL. Default to 0 when the values are non-sense.

### PR DESCRIPTION
**Pull request by howard0su**
Hit crash like this:
```
thread 'main' panicked at src/uu/df/src/table.rs:156:21:
attempt to subtract with overflow
stack backtrace:
   0: rust_begin_unwind
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:595:5
   1: core::panicking::panic_fmt
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:67:14
   2: core::panicking::panic
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:117:5
   3: <uu_df::table::Row as core::convert::From<uu_df::filesystem::Filesystem>>::from
             at ./src/uu/df/src/table.rs:156:21
   4: uu_df::table::Table::new
             at ./src/uu/df/src/table.rs:392:27
   5: uu_df::uumain::uumain
             at ./src/uu/df/src/df.rs:470:20
   6: uu_df::uumain
             at ./src/uu/df/src/df.rs:430:1
   7: coreutils::main
             at ./src/bin/coreutils.rs:103:31
   8: core::ops::function::FnOnce::call_once
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

After the fix, manual validated the df output with native df on WSL Debian. It works as expected. Native df also default to 0.

### CODE REVIEW

**Comment by sylvestre** [comment]
cool, thanks
how did you get this error ?

could you please add a test to make sure we don't regress in the future?

**Comment by howard0su** [comment]
Sure. I will add one more test case.

**Review by tertsdiepraam — COMMENTED** [review]
Nice find! I wonder why these values are weird on Windows 🤔 Good workaround nonetheless. Would you mind also putting in a comment describing the issue in the code?

**Comment by howard0su** [comment]
update per the suggestions. add a test case as well.

**Comment by shinhs0506** [comment]
i filed this [issue](https://github.com/microsoft/WSL/issues/10017) to the wsl team a while ago, but the issue is caused by the filesystem reporting negative numbers. related t o #3640

**Pull request merged**
