### PR TITLE
Fix clippy warnings

### PR DESCRIPTION
**Pull request by ebfe**
Fixes most warnings generated by [rust-clippy](https://github.com/Manishearth/rust-clippy)

### CODE REVIEW

**Comment by Heather** [comment]
@ebfe `isaac.rs:134:37: 134:48 error: the type of this value must be known in this context`

**Comment by ebfe** [comment]
Don't know yet. #792 also fails in dependency code. Probably new rust nightly that breaks these libs.

**Comment by ebfe** [comment]
rust-lang/rust#30713

**Comment by Arcterus** [comment]
Please squash the commits and then I'll merge this.

**Comment by ebfe** [comment]
done

**Pull request merged**
