### PR TITLE
chmod: replace walkdir with std::fs

### PR DESCRIPTION
**Pull request by xxyzz**
I guess `filter_map` removes some files even though they can be modified(#3118). `tests/mkdir/p-3.sh` passed after the change.

### CODE REVIEW

**Comment by xxyzz** [comment]
How could `test_chmod_recursive` pass? GNU chmod failed this test as the `a` and `z` folder can't be read.

**Comment by tertsdiepraam** [comment]
You're right, `Walkdir` doesn't seem to be able to recurse into those directories. Here is the error that is filtered (printed with `dbg!`):
```
[src/uu/chmod/src/chmod.rs:244] e = Error {
    depth: 1,
    inner: Io {
        path: Some(
            "a/b",
        ),
        err: Os {
            code: 13,
            kind: PermissionDenied,
            message: "Permission denied",
        },
    },
}
```

Too bad, we can't use `WalkDir` but it does look like you found the right solution. Could you add a test for this?

**Comment by xxyzz** [comment]
Should I delete the `test_chmod_recursive` test from `test_chmod.rs`?

**Comment by tertsdiepraam** [comment]
Hmm, yeah it's wrong, but it's probably better to change the expected outcome than to remove it alltogether.

**Comment by rivy** [comment]
> Hmm, yeah it's wrong, but it's probably better to change the expected outcome than to remove it alltogether.

Adding a quick comment about it (at the change or function level) would likely diminish future confusion as well.

And before a final merge, please rebase and merge the more casual/fix commits into their respective commits.
Thanks!

**Comment by xxyzz** [comment]
Some GNU tests should complete instantly but take 10m...

**Comment by jfinkels** [comment]
> Some GNU tests should complete instantly but take 10m...

Do you know which tests are taking an unexpectedly long time to run? If you can identify them, maybe we can help diagnose the problem.

**Comment by xxyzz** [comment]
Here are the tests run ten minutes on CI:
- tests/misc/readlink-root.sh
- tests/cp/existing-perm-race.sh
- tests/cp/file-perm-race.sh
- tests/cp/preserve-mode.sh
- tests/ls/stat-dtype.sh
- tests/ls/stat-failed.sh
- tests/mv/mv-special-1.sh

Maybe it has something to do with symbolic links?

**Pull request merged**
