### PR TITLE
Rust Edition 2021

### PR DESCRIPTION
**Pull request by tertsdiepraam**
Finishing what I started for https://github.com/uutils/coreutils/issues/3342. I bumped the edition for all crates to 2021 and made some simple changes that this enabled. In particular:
- `TryInto` and `TryFrom` are now part of the prelude and no longer need to be explicitly imported
- Arrays implement `IntoIterator`, so they don't need to be prefixed with a `&` to iterate over them.

### CODE REVIEW

**Comment by tertsdiepraam** [comment]
Hmmm, I think the failures are due to the new feature resolver?

**Comment by tertsdiepraam** [comment]
I need a bit of help on the codecov failures. I'm not sure what's going on there

**Comment by tertsdiepraam** [comment]
Okay seems to be all good now!

**Comment by sylvestre** [comment]
Well done

**Pull request merged**
