### PR TITLE
cp: only allow directory for -t

### LINKED ISSUE #2986: cp: -t overwrites data if called with a file, not a directory
```
printf '123' > file
printf '456' > dir
cp -t dir file && cmp dir file
```

`cp -t` expects two arguments: a directory to copy into, and a file to copy. If the first argument is a directory, uutils has the correct behavior. If the first argument is a file, GNU will detect this and fail with the message `cp: target 'dir' is not a directory`, but uutils will erase the data in `dir` and replace it with a copy of `file`. Effectively, uutils treats `cp -t first second` as equivalent to `cp second first` if `first` and `second` are both files.

### PR DESCRIPTION
**Pull request by shoriminimoe**
Add a validator to the `--target-directory` option that only allows directories as the argument value.

Closes #2986

### CODE REVIEW

**Comment by tertsdiepraam** [comment]
Thank you! I'm a little bit hesitant about the use of clap validators. In any code that does not need to be compatible with other code I would encourage using them, but in this project we try to match GNU coreutils as closely as possible. With this solution, both the error message and the exit code are in compatible (it's `1` in GNU and `2` here). Could you maybe defer this check to after the argument parsing and return a custom error?

**Comment by shoriminimoe** [comment]
> Thank you! I'm a little bit hesitant about the use of clap validators. In any code that does not need to be compatible with other code I would encourage using them, but in this project we try to match GNU coreutils as closely as possible. With this solution, both the error message and the exit code are in compatible (it's `1` in GNU and `2` here). Could you maybe defer this check to after the argument parsing and return a custom error that matches GNU?

I totally understand. I will make the change.

**Comment by shoriminimoe** [comment]
@tertsdiepraam I had a couple of thoughts as I went back to make your suggested changes.

For exit codes, you're going to encounter this issue with any sort of `clap` argument rules. We just went through this in #3012. In that case, I used `try_get_matches_to` with `map_err` to force an exit code of `1` since all `clap` parsing errors return `2`:

```rust
    let matches = uu_app()
        .override_usage(&usage[..])
        .after_help(&long_usage[..])
        .get_matches_from(args);
        .try_get_matches_from(args)
        .map_err(|e| {
            e.print().expect("Error writing clap::Error");
            match e.kind {
                clap::ErrorKind::DisplayHelp | clap::ErrorKind::DisplayVersion => 0,
                _ => 1,
            }
        })?;
```

Instead of using the closure, we could add a common named function and use that with all `clap` argument parsing. This would allow using convenient `clap` argument rules and GNU compliant exit codes.

That said, we would not get GNU identical error messages. Is that a hard design requirement of the project?

**Comment by tertsdiepraam** [comment]
Interesting idea! I would also like to see some more flexibility of clap on this, but this sounds like a good workaround. Another option is to implement `From<ClapError>` for `UResult`and fine it exit code 1.

Regarding the messages, we're not super strict about them if they are due to invalid arguments. Because that's usually not behaviour that people rely on and claps messages are now informative than GNU usually.

**Comment by shoriminimoe** [comment]
I added a `UError` impl for `clap::Error`. If `uu_app().try_get_matches_from(args)?` results in an error, the exit code will be `1` instead of `2`.

Doing it this way disables the colorized output from `clap`. I'm sure there is some simple thing that I am missing to make this work. I just haven't figured it out yet.

**Comment by sylvestre** [comment]
@tertsdiepraam is that ok with you?

**Pull request merged**
