### PR TITLE
Use Iterator::copied() in sieve.rs (merged once 1.36.0 is the minimal version)

### PR DESCRIPTION
**Pull request by est31**
This requires MSRV of 1.36.0 so probably can't be merged right away.

### CODE REVIEW

**Comment by ArniDagur** [comment]
The minimal version is 1.40.0 now. That's higher than 1.36.0.

**Comment by sylvestre** [comment]
Right, I re triggered the CI :)

**Comment by est31** [comment]
I've rebased. Think the CI failure is unrelated I think. Master fails too.

**Pull request merged**
