### PR TITLE
seq: reject NaN arguments

### PR DESCRIPTION
**Pull request by miDeb**
Move the validation logic to an argument validator.

### CODE REVIEW

**Comment by miDeb** [comment]
How serious do we take having the same error messages as GNU?
Ours is "error: Invalid value for '<numbers>...': invalid floating point argument `nan`: can not be NaN", GNU's is "seq: invalid 'not-a-number' argument: 'nan'". Should I change this, or is it not that importatn?

**Comment by sylvestre** [comment]
Yeah, we should have the same output.
Looking at the logs, it seems that it is indeed checked
```
2021-06-01T11:03:55.3098408Z --- 1 ----
2021-06-01T11:03:55.3099133Z ! seq: seq: invalid floating point argument `-f`: invalid float literal
2021-06-01T11:03:55.3099840Z fmt-eos1...
2021-06-01T11:03:55.3100736Z seq.pl: test fmt-eos1: stderr mismatch, comparing fmt-eos1.1 (expected) and fmt-eos1.E (actual)
2021-06-01T11:03:55.3101636Z *** fmt-eos1.1	Tue Jun  1 10:03:50 2021
```

**Comment by sylvestre** [comment]
it is still failing here:
https://pipelines.actions.githubusercontent.com/Tv5Yv5nIzIhWaMo3xdKzjIorSSIlfCwnxr6L52Y7lKBOTZPJ76/_apis/pipelines/1/runs/4698/signedlogcontent/3?urlExpires=2021-06-02T08%3A20%3A49.9036202Z&urlSigningMethod=HMACV1&urlSignature=lEBuZl3agbX1GUP0DBB2xvncYhkxaIt%2BltW4MeA5b3k%3D

grep for ": invalid floating point argument:"
is that expected?

**Comment by miDeb** [comment]
This is more or less expected. The failures are because
- We don't support the `--format` option
- Rust parses "nan" (regardless of case) as NaN starting from 1.53, which isn't stable yet.

**Comment by sylvestre** [comment]
ok, thanks

**Pull request merged**
