### PR TITLE
Fix lints (*very large* PR)

### PR DESCRIPTION
**Pull request by rivy**
This is a multi-week effort to fix all `cargo clippy` lint complaints.

I've made significant effort to segregate the changes by `clippy` category per commit.

The last commits (containing "allow ...") are added allow attributes for code that `clippy` doesn't like but has no easy refactor (or would increase MinSRV).

I tried to be very mechanical and straight-forward about all refactors. But, I'm happy to work on any of this if you disagree with any of the refactoring choices or the "allow" commits.

* note: this PR is on top of the ["fix+modernize" PR](https://github.com/uutils/coreutils/pull/1442) in order to be able to easily build and test on multiple machines

### CODE REVIEW

**Comment by rivy** [comment]
All tests pass, see [AppVeyor for `13fb466c`](https://ci.appveyor.com/project/rivy/rust-coreutils/builds/29816958); AppVeyor fail here is some transient clone error.

**Comment by ArniDagur** [comment]
In my opinion we should update the Minimum Supported Release to 1.36, and fix the uses of `mem::uninitialized` properly. What do you think @Arcterus?

**Comment by Arcterus** [comment]
Sorry for lack of response.  I will be more active going forward.

@ArniDagur I agree.  I'm actually tempted to bump us up to 1.39 to experiment with async/await.

@rivy can you also rebase?  The only thing that should be different so far is `uptime`.  In the meantime I'll start looking through the changes over the next day or two.  Would you prefer I merge the other two PRs first or just merge this one when it's done?

**Comment by rivy** [comment]
@Arcterus , glad to see you back!

I've rebased all three PRs and committed a couple of needed fixups.

I think merging the sub-PRs first would be easier to digest, but I'm happy to support whatever is easier for you.

I've got one more substantial PR that I'll post tomorrow which includes refactored features so that `cargo build` just works on all platforms (compiling the overlapping subset of utils), a more robust `cargo make` bundle that tailors the build to the platform automatically and can build individual utilities easily. And, the best part... is a full GitHub Action CICD that performs about 5 to 10 times faster that Travis or AppVeyor. And it can do automatic release deployment for tagged commits.

- ... see <https://github.com/rivy/rust.coreutils/compare/fix.lints...rivy:add.cicd> for a preview
- ... see a workflow run at <https://github.com/rivy/rust.coreutils/actions/runs/32068265>
- .. see an automatic release at <https://github.com/rivy/rust.coreutils/releases/tag/0.0.2>

**Comment by rivy** [comment]
Closing in favor of #1449 (which includes these commits).

**Pull request closed without merging**
