### PR TITLE
Remove plenty of unused deps

### PR DESCRIPTION
**Pull request by sylvestre**

### CODE REVIEW

**Comment by blyxxyz** [comment]
This doesn't seem to build:
```
error[E0433]: failed to resolve: use of undeclared crate or module `uucore_procs`
 --> src/uu/comm/src/main.rs:1:1
  |
1 | uucore_procs::main!(uu_comm);
  | ^^^^^^^^^^^^ use of undeclared crate or module `uucore_procs`

For more information about this error, try `rustc --explain E0433`.
error: could not compile `uu_comm` due to previous error
warning: build failed, waiting for other jobs to finish...
error[E0601]: `main` function not found in crate `comm`
 --> src/uu/comm/src/main.rs:1:1
  |
1 | uucore_procs::main!(uu_comm);
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ consider adding a `main` function to `src/uu/comm/src/main.rs`

Some errors have detailed explanations: E0433, E0601.
For more information about an error, try `rustc --explain E0433`.
error: build failed
```
I'm guessing `udeps` was wrong?

**Comment by sylvestre** [comment]
> I'm guessing udeps was wrong?

it is more complex than that ;)

**Comment by sylvestre** [comment]
it should work for most of the things but "make all" fails because the uucore procs dep is used for main:
https://github.com/rust-lang/cargo/issues/1982

**Comment by sylvestre** [comment]
we are good and I will land the CI check later.
Auto land

**Pull request merged**
