### PR TITLE
fix: Limit the max output of printf

### LINKED ISSUE #1879: printf does not have limits for the maximum value of its arguments
The GNU `printf` command limits the value of arguments it will accept, for example
```
$ printf '%.*d\n' 10 0
0000000000
$ printf '%.*d\n' 2147483648 0
bash: printf: warning: 0: Numerical result out of range
```

The version of printf in this repo does not apply this limit so it will produce 2 billion 0s. This is causing the gnu tests to fail when attempting to generate the final log as it has to process a log from a test that is ~2GB in size.

If this isn't considered a bug then the gnu tests should be patched to remove the problematic check.

### PR DESCRIPTION
**Pull request by howjmay**
Closes #1879

### CODE REVIEW

**Comment by sylvestre** [comment]
Clippy is not happy

**Comment by jfinkels** [comment]
I'm not sure this is solving the right problem. The linked issue is requesting the following behavior:
```
$ /usr/bin/printf '%.*d\n' 2147483648 0
/usr/bin/printf: invalid precision: ‘2147483648’
```
First, this pull request does not produce that error message. Second, it would need to fill a vector with a very long string just to get to that point. This would probably be more effectively implemented by just checking at the time of parsing the command-line arguments whether the number is 2^31 or greater. Also, it would benefit from a unit test in the `tests/by-util/test_printf.rs` file.

**Comment by howjmay** [comment]
> I'm not sure this is solving the right problem. The linked issue is requesting the following behavior:
> 
> ```
> $ /usr/bin/printf '%.*d\n' 2147483648 0
> /usr/bin/printf: invalid precision: ‘2147483648’
> ```
> 
> First, this pull request does not produce that error message. Second, it would need to fill a vector with a very long string just to get to that point. This would probably be more effectively implemented by just checking at the time of parsing the command-line arguments whether the number is 2^31 or greater. Also, it would benefit from a unit test in the `tests/by-util/test_printf.rs` file.

So I should find if `%.*d` exist in the format patter? I am implementing in this way, since I found it quite hard to find escape character and corresponding parameter

**Comment by tertsdiepraam** [comment]
> This would probably be more effectively implemented by just checking at the time of parsing the command-line arguments whether the number is 2^31 or greater

Indeed, the goal here is that this number is so large that it's probably a user error and just writes a nonsensical amount of data. So we don't gain much if we still try to write it to a vec, which might also make `printf` run out of memory.

> I am implementing in this way, since I found it quite hard to find escape character and corresponding parameter

Yeah that is quite difficult. I suppose it should be a check somewhere inside `Memo`, which already does most of the parsing.

**Comment by sylvestre** [comment]
Clippy complains about:
ERROR: `cargo clippy`: this comparison involving the minimum or maximum element for this type contains a case that is always true or always false (file:'src/uucore/src/lib/features/memo.rs', line:121)

and format!() (should be easy)

**Pull request closed without merging**
