### PR TITLE
tac: check if stdin is closed

### LINKED ISSUE #2873: tac: should fail when stdin is closed but doesn't
The `uutils` version of `tac` disagrees with GNU `tac` in the case where `stdin` is closed on the command line:

GNU prints an error message to `stderr` and returns exit status code 1:
```
$ tac <&-
tac: 'standard input': read error: Bad file descriptor
tac: -: Bad file descriptor
```
[`<&-` means close stdin][0].

`uutils` prints nothing and returns exit status code 0:
```
$ ./target/debug/coreutils tac <&-
```
This is causing one of the GNU tests to fail.

[0]:  https://tldp.org/LDP/abs/html/io-redirection.html

### PR DESCRIPTION
**Pull request by 353fc443**
Fixes #2873 and added `lseek` to cspell :)

### CODE REVIEW

**Comment by tertsdiepraam** [comment]
Hi! Looks good! Just a quick tip: you don't have to open a new PR if you force push, the CI will just rerun on the old PR.

**Comment by 353fc443** [comment]
> Hi! Looks good! Just a quick tip: you don't have to open a new PR if you force push, the CI will just rerun on the old PR.

Oh I'm sorry. I force pushed without commiting the changes that made github close that PR.
Sorry again :)

**Comment by tertsdiepraam** [comment]
No problem!

**Review by tertsdiepraam — CHANGES_REQUESTED** [review]
Great work for Unix systems, but Windows doesn't seem to happy about this change :). Instead of checking beforehand, I think it makes more sense to just try the `read_to_end` call and inspect the result (so we get the cross-platform-ness from the stdlib). Something like:
```rust
match stdin().read_to_end(&mut buf1) {
    Ok(0) => return Err(TacError::StdinClosed("-".into()).into()),
    Ok(_) => &buf1,
    Err(e) => {
        let e: Box<dyn UError> = TacError::ReadError("stdin".to_string(), e).into();
        show!(e);
        continue;
    }
}
```

**Comment by 353fc443** [comment]
@tertsdiepraam is this what you had in mind ? :)

**Comment by tertsdiepraam** [comment]
Almost, the `Ok(0)` actually indicates already that stdin has been closed, so the additional check can be remove, which makes it work on Windows. The `is_stdin_open` function then becomes unnecessary. This will still give a `Bad File Descriptor` on Windows if you close the stdin there (I think). I (hopefully) found a way to test this so I'll push that to this branch so you can see.

**Comment by 353fc443** [comment]
The new test seems to fail

**Comment by tertsdiepraam** [comment]
That's annoying. Locally, I'm also running into this:
```
❯ cargo run --features tac --no-default-features -- tac
tac: 'standard input': read error: Bad file descriptor
tac: -: Bad file descriptor
```
both with the libc and atty version. So maybe it's not the correct solution after all. I'll look further into this later, feel free to experiment (and remove that test if it doesn't do what it's supposed to).

**Comment by 353fc443** [comment]
Okay sure :)

**Pull request closed without merging**
