### PR TITLE
ls: when -aA are provided, the order matters

### PR DESCRIPTION
**Pull request by sylvestre**

### CODE REVIEW

**Comment by tertsdiepraam** [comment]
Ohh good find! Instead of manually checking the indices, we should probably make them override each other with clap's `Arg::overrides_with`, so we don't need to implement the logic ourselves.

**Comment by sylvestre** [comment]
it supports the order?
-aA is different than -Aa

**Comment by tertsdiepraam** [comment]
Yeah the `overrides_with` method makes it so that the earlier argument is automatically discarded when the second one is passed, so `-aA` is equivalent to `-A` and `-Aa` is equivalent to `-a`.

**Comment by sylvestre** [comment]
bien vu, done :)

**Comment by anastygnome** [comment]
Hey there 
> Yeah the `overrides_with` method makes it so that the earlier argument is automatically discarded when the second one is passed, so `-aA` is equivalent to `-A` and `-Aa` is equivalent to `-a`.

Nice finding @tertsdiepraam ! 
@sylvestre You should consider adding a comment there, as I, as a foreigner to this project, had to read this PR to understand this part of the code. 

> any thing that's clever, or that you find surprising should be commented. 
 (a CS prof. of mine, back in the day)

**Comment by sylvestre** [comment]
Yeah:
`
Changes from main: PASS +1 / FAIL -1 / ERROR +0 / SKIP +0
`

**Comment by sylvestre** [comment]
@anastygnome I think it is self explanatory but as it doesn't hurt, I added comments :)

**Review by tertsdiepraam — COMMENTED** [review]
Looks good, but while we're changing this, both should also override themselves (so that `ls -aa` is possible). @anastygnome this is a technique used throughout the codebase, but you're right that more comments never hurt anybody :)

**Comment by sylvestre** [comment]
> both should also override themselves 

I used `.multiple_occurrences` for this

**Comment by tertsdiepraam** [comment]
Sure! That's a good solution in this case. More generally, we should probably push for using https://docs.rs/clap/3.1.6/clap/struct.App.html#method.args_override_self in (almost) all utils.

**Pull request merged**
