### PR TITLE
CI: run GnuComment also if pipeline fails

### PR DESCRIPTION
**Pull request by tertsdiepraam**
Followup on https://github.com/uutils/coreutils/pull/4010

(again needs to be merged before we can test sadly)

### CODE REVIEW

**Comment by tertsdiepraam** [comment]
There has been a run of GnuComment with an issue. I'll also try to fix that here.

**Comment by tertsdiepraam** [comment]
The ecosystem really needs some significant innovation in the CI configuration space. Just running hour-long jobs while hoping that they work is really not great. I wonder if we'll see improvements from GitHub in the near future.

**Comment by sylvestre** [comment]
Agreed
(this is why I tested on smaller tasks)

**Comment by tertsdiepraam** [comment]
@sylvestre can I merge changes I make to this workflow myself? Otherwise it's gonna take a long time to test 😄

**Comment by sylvestre** [comment]
sure

**Pull request merged**
