### PR TITLE
groups: clap migration

### PR DESCRIPTION
**Pull request by sylvestre**

### CODE REVIEW

**Comment by sylvestre** [comment]
@rivy I wrote this PR yesterday, before your comment about clap :)

**Comment by rivy** [comment]
Yeah, as we discussed, `clap` increases the executable size without an real appreciable benefits that I can see at this moment. And `uucore` is currently using `getopts` as well.

I am a fan (and contributor) to `clap`, but we need some reason(s) to switch. I think everything should be getopts-based until we have those reasons and decide to switch as a whole.

**Comment by sylvestre** [comment]
@rivy thanks. I reached out to on discord to continue this discussion :)

**Comment by sylvestre** [comment]
I landed a7de28a7140ec79f4cb550f7008a5f9e4bf2cb62
I will rebase the patch for clap as I am convinced it is the right approach for the future of the project

**Comment by Arcterus** [comment]
Looks good to me.  I’d been meaning to move everything over to clap (in part to get support for non-UTF-8 environments), although I do understand the worry about increased executable size.

**Pull request merged**
