### PR TITLE
Tail large files

### LINKED ISSUE #764: tail performance on big files
tail is very slow when operating on large files. It reads the whole file from
the beginning when it probably should count newlines starting from the end of
file.

    $ wc -l lines
    100000000 lines
    
    $ time tail -n 1 lines
    blabla
    
    real	0m0.002s
    user	0m0.000s
    sys	0m0.000s
    
    $ time target/release/uutils tail -n 1 lines
    
    blabla
    
    real	0m6.349s
    user	0m6.247s
    sys	0m0.107s

### PR DESCRIPTION
**Pull request by fitzgen**
Fixes #764

### CODE REVIEW

**Comment by Heather** [comment]
LGTM

**Comment by fitzgen** [comment]
Should I be worried about the appveyor failure? It looks like master is failing appveyor as well.

@Heather, what else is needed to get this PR merged? Thanks!

**Comment by nathanross** [comment]
@fitzgen no, it's been failing for a while. I've been chipping away at them, but there's still a couple left. I'll see what I can do this week.

**Comment by nathanross** [comment]
@Heather @fitzgen major objection to this PR though. There is no reason to be adding 12 mb of files to the repo for test fixtures.

That's going to make all git clones in the future much much slower.

In general the best approach for testing large amounts of data is to generate that data programatically in your test. If you need that fixture for multiple tests, use a helper method to programatically generate it that can be called in each test, or is called in a more general setup method called by multiple tests. 

Performance in running a test for a particular utility is not nearly as major a concern as performance for operations on the git repo.

**Comment by fitzgen** [comment]
Removed the large files and generate them in the test now.

**Comment by ebfe** [comment]
Please prefix commits with `tail:` or `tests/tail:` so the commit history is easier to skim.

**Comment by fitzgen** [comment]
> Please prefix commits with tail: or tests/tail: so the commit history is easier to skim.

Done

**Pull request merged**
