### PR TITLE
yes: Cleanup

### PR DESCRIPTION
**Pull request by blyxxyz**
Report errors properly instead of panicking.

Replace zero_copy by a simpler specialized private module.

Do not assume splices move all data at once.

Use the modern uutils machinery.

Remove the "latency" feature. The time it takes to prepare the buffer is drowned out by the startup time anyway.

I'd like to write more tests but I'm not sure what the best way to do that is. The output needs to be cut off somehow, as by `head -c100`. Any ideas?

### CODE REVIEW

**Comment by miDeb** [comment]
> I'd like to write more tests but I'm not sure what the best way to do that is. The output needs to be cut off somehow, as by head -c100. Any ideas?

I wrote a similar test for sort some time ago: https://github.com/uutils/coreutils/blob/master/tests/by-util/test_sort.rs#L961-L972. Maybe that's useful?

**Comment by blyxxyz** [comment]
Thank you, that helped me figure out a way.

**Comment by miDeb** [comment]
Could you squash your commits together (`git rebase --autosquash`)?

**Comment by sylvestre** [comment]
@miDeb you can do it yourself in github:
image

**Comment by miDeb** [comment]
@sylvestre when you run `--autosquash` it squashes `fixup` commits (but keeps commits that are not fixups), but if I select `squash` I think it squashes all commits into one. Not that it really matters.

**Comment by miDeb** [comment]
@blyxxyz thanks for the PR!

**Pull request merged**
