### PR TITLE
sort: fix some exit codes and error messages

### PR DESCRIPTION
**Pull request by miDeb**

### CODE REVIEW

**Comment by sylvestre** [comment]
this will improve the compat with the gnu testsuite you think ?

**Comment by miDeb** [comment]
There is this one big GNU test `sort.pl` which I'm looking at, this will only fix one test case of that file. Getting the whole thing to pass is unlikely to happen soon because some test failures are caused by a bug in clap (https://github.com/clap-rs/clap/issues/2624), others are caused by clap printing different usage errors than gnu and some are because our custom parser for the `-k` argument prints different usage errors. But I'm about to submit more PRs to fix other bugs I found :)

I don't know how difficult it is going to be to fix the usage errors (or if that's even a priority, since I'd prefer clap's errors over gnu's)

**Comment by sylvestre** [comment]
Don't spend too much time on hacking on clap/workaround/limitation

What I did is just update the gnu test on the fly.
See
https://github.com/uutils/coreutils/blob/master/util/build-gnu.sh#L106-L120

**Comment by miDeb** [comment]
> What I did is just update the gnu test on the fly.

I will do that after having fixed all of the bugs we can fix :)

**Pull request merged**
