### PR TITLE
Add some test utils needed for major test refactoring

### PR DESCRIPTION
**Pull request by Gilnaa**
In order to ease the reduction of CmdResult fields directly,
I've added the following measures:

 * `CmdResult::{success,failure}` and `UCommand::{failed,succeeded}` now
 print the stdout/stderr. This is done to reduce prints in tests. (as suggested [here](https://github.com/uutils/coreutils/issues/1982#issuecomment-811808890))
 * Added `code_is` that asserts that return code
 * Fixed documentation of `stdout_only` which stated that it trims the string.
 * Added some more utilities for actions that previously required accessing `stdout` or `stdout_str()`.
 * Fix documentation of `stdout_only` which claimed it was trimming the output.
 * ~(some) Panicking utilities now has `track_caller` slapped on them to point accurately at the call location in the tests.~

On different PRs:
 * I've applied this on some files but got defeated while refactoring
 `test_ls.rs`. https://github.com/uutils/coreutils/pull/2034
 * Unrelated: Changed panics to use string literals because of Rust 2021
 warning. https://github.com/uutils/coreutils/pull/2033

There's probably a use for `stdout_trimmed()`, since it's used in many places.
After this PR, grepping the repo for the regex `\.stdout[^_\( ]` (with match-whole-word) returns only 156 in 18 files.

### CODE REVIEW

**Comment by Gilnaa** [comment]
Ummm, just realized that track_caller is only available from Rust 1.46 and and the MSRV is 1.40, guess I'll have to remove it

**Comment by jhscheer** [comment]
I like these changes in combination with #1982, however you should probably split this PR into multiple PRs.

**Comment by Gilnaa** [comment]
Sure, no problem.
According to any specific criteria, or just to make it a bit more digestible?

**Comment by jhscheer** [comment]
Yes more digestible is good :)
Based on your bullet points and what belongs together with regards to content, I'd say:
One PR for everything that belongs to the testing framework (first 5 bullet points). And then one PR for each of the last 3 bullet points.

**Comment by Gilnaa** [comment]
Sure thing.
Will leave this PR with the start of the and split off the rest

**Comment by Gilnaa** [comment]
Split off macro changes into https://github.com/uutils/coreutils/pull/2033
Most of the tests changes are in https://github.com/uutils/coreutils/pull/2034
(I left of the `ls` changes since that file is huge and incomplete)

**Comment by sylvestre** [comment]
I love this change, many thanks :)

it is possible to write some unit tests?

**Comment by Gilnaa** [comment]
Sure. Is there a test suite for the test utils?

**Comment by sylvestre** [comment]
Write a rust unit test
like in
https://github.com/uutils/coreutils/blob/master/src/uu/head/src/head.rs#L515

**Comment by Gilnaa** [comment]
I meant to ask if it's a standard practice to test the test utils themselves.

I'll add some

**Comment by sylvestre** [comment]
could you please fix the conflict? thanks

**Comment by Gilnaa** [comment]
@sylvestre Rebased over master

**Pull request merged**
