### PR TITLE
Download MinGW more reliably (hopefully)

### PR DESCRIPTION
**Pull request by Arcterus**
Don't merge this.  I'm going to play with it until it works.

### CODE REVIEW

**Comment by mpkh** [comment]
feels like AppVeyor periodically just stuck w/o reason

**Comment by mpkh** [comment]
@Arcterus should it be closed for now?

**Comment by wimh** [comment]
On [stackoverflow](http://stackoverflow.com/questions/37408661/appveyor-build-script-file-downloads-fail-intermittently) there is a recommendation to enable the [http proxy](https://www.appveyor.com/docs/how-to/http-proxy/).

**Comment by nathanross** [comment]
A couple weeks ago I wrote a script to use appveyor's [cache](https://github.com/nathanross/coreutils/blob/tooling-faster-appveyor/appveyor.yml) feature for the rust download to save time. It actually ended up taking the same amount of time (rust download servers are pretty fast, looks like), but I imagine this could be repurposed to, on the first successful download, just store the fixed version of mingw in the cache and reuse that version indefinitely.

**Comment by Arcterus** [comment]
@nathanross that sounds like a good idea.  I have no idea what I'm doing with PowerShell (lol).

**Comment by Arcterus** [comment]
Closed in favor of #986

**Pull request closed without merging**
