### PR TITLE
fix two clippy warnings

### PR DESCRIPTION
**Pull request by llogiq**
Just small stylistic things.

### CODE REVIEW

**Comment by Heather** [comment]
wow I even didn't know such syntax exists

**Comment by llogiq** [comment]
`if let` is just syntactic sugar for a match with one arm (and optionally an else arm without pattern destructuring). There's also `while let`, which can sometimes be useful.

**Comment by Heather** [comment]
@llogiq honestly I wondered about `let Some` alike in haskell

**Comment by llogiq** [comment]
You may want to read up on [patterns](http://doc.rust-lang.org/book/patterns.html). :smile: Those things are ludicrously powerful.

**Pull request merged**
