### PR TITLE
Backport and/or replace unstable features.

### PR DESCRIPTION
**Pull request by jbcrail**
After seeing #665, I fixed several unstable methods that caused the stable build to fail. In particular, I

* backported Path.{is_dir, is_file, exists, metadata}
* replaced fs::walk_dir() with a third-party crate (walker)
* replaced Path.canonicalize() with fs::canonicalize()
* fixed other smaller issues

This is a first-pass for a successful stable build.

### CODE REVIEW

**Comment by Heather** [comment]
@jbcrail it works for both now, stable & nightly?

**Comment by jbcrail** [comment]
@Heather These commits fix three commands in stable and partially fixes several others. The nightly build and all tests still pass. There are still a several updates to do for stable (replace set_file_times() and possibly use the custom canonicalize() in readlink instead of fs::canonicalize()).

I'm not sure if we'll ever get a clean stable build, but we can get close.

**Comment by ebfe** [comment]
Thanks!

Maybe we can add the beta to travis targets? Just to get a sense what will fix itself in the next release.

**Comment by jbcrail** [comment]
Good idea. I'll put in a PR later today.

**Comment by ebfe** [comment]
Disabling broken utils with specific compiler version might also be an option.

```Makefile
ifeq (rustc 1.1.0, $(shell rustc --version))
        DONT_BUILD="cp du echo expand fmt ln mv nl ptx realpath relpath stdbuf test timeout touch tr unexpand users yes"
else
...
```
Though i'm unsure how to do that in a non fragile way, and the Makefile is scary enough as it is.

**Comment by hexsel** [comment]
Also, 'tr' uses the .chars() method which is unstable even on nightly.

**Pull request merged**
