### PR TITLE
Don't panic when calling readlink from a nonexistent directory

### PR DESCRIPTION
**Pull request by water-ghosts**
If `readlink` is called with a relative path from a nonexistent directory, return an Error instead of panicking.

GNU's test suite contains several tests like this:

```
cd "$pwd/$tmp/removed" || framework_failure_

# Skip this test if the system doesn't let you remove the working directory.
if rmdir ../removed 2>/dev/null; then
  v=$(returns_ 1 readlink -e .) || fail=1
  test -z "$v" || fail=1
fi
```

In this situation, `readlink` attempts to read a relative path `.` from a directory that no longer exists, and GNU returns exit code 1 with no output. The same thing happens with other relative paths, but there are no problems when using absolute paths. Meanwhile, uutils panics. This isn't because of any code specific to uutils, but because Rust's own `fs::canonicalize()` panics when given a relative path from a nonexistent directory. 

I took a stab at solving this. First, this PR checks if the current directory exists. If it does, it can use `fs::canonicalize` like normal. If not, it uses a slower path by wrapping `fs::canonicalize` with `panic::catch_unwind` to recover from the panic and convert it to an Error. Since this still prints the error text to stderr, the PR also temporarily replaces `panic`'s hook function with a no-op to suppress output. 

I tested this locally and it showed the correct behavior, but I wasn't able to get a unit test working. Removing the active directory causes `ucmd` itself to panic! This is the closest I got:

```
#[test]
fn test_readlink_in_removed_directory() {
    let (at, mut ucmd) = at_and_ucmd!();
    let rmdir = fs::remove_dir(&at.subdir);
    // Don't fail if the platform won't let you remove the current directory.
    if rmdir.is_ok() {
        ucmd.arg("-e").arg(".").run().fails_silently();
    }
}
```

Let me know if you have any suggestions for how to write this unit test, or if there are easier ways to handle the panic. Also, feel free to close this PR and use it as a jumping off point for another if you think it can be significantly improved.

### CODE REVIEW

**Comment by tertsdiepraam** [comment]
Is it correct that this concerns https://github.com/uutils/coreutils/issues/3036? If so, have you checked out the discussion there?

**Comment by water-ghosts** [comment]
This PR isn’t responding to any particular issue. I just noticed that this situation caused a few of the remaining Errors in the GNU Test suite, and wanted to give it a shot. 

I don’t think this is related to #3036. That issue is specifically about absolute paths in a different utility. For readlink, absolute paths work correctly, even if the file or directory they point to doesn’t exist. It’s only relative paths from a nonexistent directory which panic.

**Comment by tertsdiepraam** [comment]
Alright! 

> This isn't because of any code specific to uutils, but because Rust's own fs::canonicalize() panics when given a relative path from a nonexistent directory.

I can't look properly into this right now, so I'm not sure if you're aware or even whether it matters, but note that the `fs::canonicalize` function used here is the `uucore::fs::canonicalize` not the one from `std`. It unwraps a results from `dunce::canonicalize` under the hood. Could that be why it panics? Again, sorry if I'm completely wrong again :)

**Comment by eyoungs** [comment]
Ah, I didn't realize this was an internal implementation. In that case, it's probably better to handle the error in that canonicalize function, rather than implementing this awkward workaround. Thanks for pointing that out!

**Comment by water-ghosts** [comment]
Ah, I didn’t realize this was a custom implementation. In that case, it’s probably better to handle this situation in the canonicalize function, rather than implementing this awkward workaround. Thanks for pointing that out!

**Comment by water-ghosts** [comment]
Closing this in favor of a much simpler PR: https://github.com/uutils/coreutils/pull/3103

**Pull request closed without merging**
