### PR TITLE
Revert the force set of the rustc nightly version

### PR DESCRIPTION
**Pull request by sylvestre**

### CODE REVIEW

**Comment by tertsdiepraam** [comment]
I just read about this problem again this morning in this post: https://nnethercote.github.io/2022/04/12/how-to-speed-up-the-rust-compiler-in-april-2022.html

> I made some missteps, too. Most notably, I caused a P-critical bug when I removed a code path that I mistakenly thought was impossible, which briefly prevented [ring](https://crates.io/crates/ring) from compiling with Nightly. (Apologies to everyone who was affected!) Interestingly, my mistake unintentionally exposed a possible bug: the compiler currently ignores doc comments in a matcher, which is arguably the wrong thing to do. But enough real code depends on this behaviour that it can’t be changed without some care.

**Review by tertsdiepraam — APPROVED** [review]

**Comment by sylvestre** [comment]
> I just read about this problem again this morning in this post: https://nnethercote.github.io/2022/04/12/how-to-speed-up-the-rust-compiler-in-april-2022.html

Ditto :) Fun fact, a couple years ago, I have been @nnethercote 's manager for a few months (with great pleasure ;) 

Nicholas, funny to see your blog post this morning;)

**Comment by tertsdiepraam** [comment]
Nice! His work is super impressive!

**Comment by nnethercote** [comment]
👋

**Pull request merged**
