### PR TITLE
Cleanup gnu test script

### PR DESCRIPTION
**Pull request by jaggededgedjustice**
This fixes the last review comments from #1699

### CODE REVIEW

**Comment by sylvestre** [comment]
```
# TOTAL: 624
# PASS:  546
# SKIP:  62
# XFAIL: 0
# FAIL:  16
# XPASS: 0
# ERROR: 0
```

Are you sure you are really testing rust/coreutils?

**Comment by sylvestre** [comment]
That sounds too good to be true

**Comment by jaggededgedjustice** [comment]
I can't see how anything would be going wrong, posibly the `make` to generate `getlimits` is messing things up? I did test that adding that make command wouldn't affect the binaries in the uutils build dir, but then again locally running `lib/configmake.h src/getlimits` was enough to get it the executable while in github there was another file that needed to be generated. So there might be remnants in my local test environment that is changing the results.
I'll run some experiments to confirm that the uutils binaries are what's being testsed.

**Comment by tdulcet** [comment]
> That sounds too good to be true

Yeah, something is not right. Most of the `factor` [tests should fail](https://github.com/coreutils/coreutils/blob/master/tests/factor/create-test.sh#L41-L68), since they test numbers >  2<sup>64</sup> - 1, which uutils factor does not currently support (#1559). Only two are [currently failing](https://github.com/uutils/coreutils/runs/1744777923?check_suite_focus=true#step:7:724).

**Comment by jaggededgedjustice** [comment]
I have discovered my mistake. I was building uutils with `cargo` but that doesn't build all the individual binaries, so this is effectively testing the binaries that are installed on the system. After fixing this the tests just hang, a bit of digging indicates a `fmt` call was stuck in a `read` syscall which I assume is why the `ulimit -t` doesn't keep things moving.
I couldn't see an easy way to wrap individual tests with `timeout`, so I'll see if I can come up with a list of non-hanging tests.

**Comment by sylvestre** [comment]
@jaggededgedjustice ok, thanks for digging into that :)
Don't hesitate to report a bug about the fmt issue, we could just fix the problem

**Comment by sylvestre** [comment]
@jaggededgedjustice are you going to work on a fix to really use rust/coreutils?
Thanks

**Comment by jaggededgedjustice** [comment]
Still working on it, I hope I've found the last problem and it just needs testing. If things work out I should have a PR over the weekend.

**Pull request merged**
