### PR TITLE
expr: implement regular expressions

### PR DESCRIPTION
**Pull request by Arcterus**

### CODE REVIEW

**Comment by Arcterus** [comment]
I have no idea what is wrong with Travis right now.

**Comment by mpkh** [comment]
seems related `error: failed to run custom build command for `onig_sys v61.1.0``

**Comment by Arcterus** [comment]
That's the issue with AppVeyor (which I need to reboot into Windows to figure out how to fix).  I'm not sure what is going on with Travis though because it compiles everything but then fails the tests.

**Comment by knight42** [comment]
@Arcterus Now that I had fixed the error, could you rebase on top of [this commit](https://github.com/uutils/coreutils/commit/fd7be06e5beabfe9cf01119d9093a9503a00c304), so that we can see whether this can be merged?

**Comment by knight42** [comment]
ping @Arcterus

**Comment by Arcterus** [comment]
AFAICT, the build on Windows is still failing because of Oniguruma, although I'm not exactly sure what's wrong with it given that the Appveyor build seems to be working for `rust-onig`.

**Comment by ebfe** [comment]
Do we really want to add more dependencies on C libraries?

**Comment by Arcterus** [comment]
I would rather not, but the syntax for the regexes accepted by `expr` is different than the syntax accepted by `regex`.  Because I didn't want to translate the input (which seems error-prone) or write my own regex parser, I decided that it would be best to use the `rust-onig` crate for the time being.

**Comment by ids1024** [comment]
> Because I didn't want to translate the input...

Posix Basic Regular Expressions (BREs) and Extended Regular Expressions (EREs) support back-references, which the `regex` crate doesn't support by design, so unfortunately I don't think it will be of much help. I guess the long term solution is implementing them in Rust?

So the only thing blocking this is figuring out the appveyor issue?

**Comment by Arcterus** [comment]
Yeah, this is the only short-term solution I can see right now, so once the MSVC build works I think this will be ready to go.

**Comment by ids1024** [comment]
Rust-onig's [appveyor.yaml](https://github.com/rust-onig/rust-onig/blob/master/appveyor.yml) has this line:

```
# Rust needs at least Visual Studio 2013 Appveyor OS for MSVC targets.
os: Visual Studio 2015
```

Possibly the cause? The issue must be some discrepancy between their appveyor configuration and the uutils one. In any case, this could be awkward for people trying to build uutils on msvc.

**Comment by ids1024** [comment]
This should hopefully pass CI now if the merge conflicts are resolved.

**Pull request merged**
