### PR TITLE
Add support in uucore for illumos and solaris

### PR DESCRIPTION
**Pull request by bbarker**
The build was broken on these systems; confirmed working now on illumos. It should also work on solaris after conferring with a solaris developer.

### CODE REVIEW

**Review by tertsdiepraam — COMMENTED** [review]
Cool! The only thing I don't really like is the macro for concatenating arrays. It's unfortunate that the lengths of the array are explicit for example. I'd like to propose this as an implementation for the `ALL_SIGNALS` static (simplified to just two signals):
```rust
#[cfg(target_os = "solaris")]
const SIGNALS_SIZE: usize = 1;

#[cfg(target_os = "illumos")]
const SIGNALS_SIZE: usize = 2;

#[cfg(or(target_os = "solaris", target_os = "illumos"))]
static ALL_SIGNALS: [&str; SIGNALS_SIZE] = [
    "HUP",
    #[cfg(target_os = "illumos")]
    "LWP",
];
```

**Comment by bbarker** [comment]
Thanks, that's a definite improvement! Pushed up the change :pray:

**Comment by sylvestre** [comment]
would it be possible to have a CI for these platforms ?

**Comment by bbarker** [comment]
I'd love to ... Think we'd have to fork the freebsd-vm project, so that
might take me a while on my own.

**Comment by bbarker** [comment]
Is it OK to merge without the illumos CI support for now?

I will try to look into it. Have you had good success with your approach to FreeBSD CI?

**Comment by Toasterson** [comment]
> would it be possible to have a CI for these platforms ?

I am a Maintainer with the OpenIndiana Project. The illumos reference distribution.
What platform do you need the CI on? We usually have either Jenkins or Buildomat as our CI runners but also have github action templates for VM's  Seel Chezmoi for a contributed example https://github.com/twpayne/chezmoi/blob/v2.9.3/.github/workflows/main.yml#L173-L191

**Comment by tertsdiepraam** [comment]
We usually use GitHub Actions. If you could point us towards good templates or help us out with creating one, that would be great!

Also I don't think this PR is blocked by not having CI. Adding CI is a task that is big enough to be a separate PR as it will probably uncover more problems to fix.

**Comment by Toasterson** [comment]
@tertsdiepraam  https://github.com/twpayne/chezmoi/blob/v2.9.3/.github/workflows/main.yml#L173-L191

**Comment by tertsdiepraam** [comment]
Thanks! I've made an issue for the CI here: https://github.com/uutils/coreutils/issues/5492. @bbarker feel free to pick that up if you want!

**Pull request merged**
