### PR TITLE
env: support string args by "-S", "-vS" or "--split-strings"

### PR DESCRIPTION
**Pull request by cre4ture**
addresses  #5710

This implements all the functionality tested by gnu/tests/env/env-S.pl.
I had to patch the test due to more powerfull implementation and differencences in how parser errors are reported.
I Introduced a mechanism to patch the test with patch-files as the sed-stuff I could not make run for me.

The feature is quite complex, as the tool needs do parsing and evaluation (quoting, escape sequences, environmental variables) of the string on a similar level as a shell:
 `env -S<single full featured shell command>`

Therefor I was trying different existing rust implementations of sh/bash-like shells. The first one that was working for me to a large extent was the `nsh`: https://github.com/nuta/nsh
Its licenced as "MIT or CC0". So we can use it without licence issues.

Sadly, it was not yet perfectly suited for the env split-string feature. Therefor I had to do modifications. I pushed them to a feature branch on my fork: https://github.com/cre4ture/nsh/tree/feature/coreutils_env_split_string
Then I added a git submodule pointing to that feature branch.
EDIT: Apparently, the submodule has the issue that style checks and clippy tests are run on it. This causes red CI/CD builds.

I guess that these points needs to be discussed, agreed at and fixed before this pull request can be approved:
- [ ] is nsh the right "library" for us to use?
  - [ ] bring changes into the main branch of nsh
  - [ ] decide on sticking with submodule
- [ ] is the patching mechanism ok?

### CODE REVIEW

**Comment by sylvestre** [comment]
Why do you need nsh ? 
Seems that we don't need to add a dependency on a shell for this feature?

**Comment by cre4ture** [comment]
> Why do you need nsh ? Seems that we don't need to add a dependency on a shell for this feature?

Let me help you getting the right picture. 
Citation: "What shells do when splitting a command-line string into arguments is far from trivial, especially when you want to handle things like quoting." (Source: [stack-overflow](https://stackoverflow.com/questions/53498414/how-do-i-pass-a-single-string-with-multiple-arguments-to-stdprocesscommand) )
Because of this it is then recommend to use [shell-words](https://crates.io/crates/shell-words) or [shlex](https://crates.io/crates/shlex) to avoid spending a lot of time on it.
The parser of `shell-words` has 500 lines of code. The `shlex`ha 420. Both are missing the part that expands `$VARIABLES`.
And both implementations fail at many of the cases from the GNU test-suite, such they can't be used without adaptions. I had the impression that the `nsh` parser was doing the best in the test-suite. And therefor I started to adapt it from there.

I also see that its not ideal, as we need to do adaptions to nsh as well. My hope was, that these adaptions could make into the official main branch of nsh. But they might conflict with the goals of nsh.

If we consider that we anyway need to do adaptions, we could try to go for `shell-words` and a other library for variable expansion like [shellexpand](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwji2NH0lr2DAxXKhP0HHUaxCZ8QFnoECA0QAQ&url=https%3A%2F%2Fdocs.rs%2Fshellexpand%2F&usg=AOvVaw1Od_2pi127Sx_SHQM3HscI&opi=89978449) or [subst](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwji2NH0lr2DAxXKhP0HHUaxCZ8QFnoECCYQAQ&url=https%3A%2F%2Fdocs.rs%2Fsubst&usg=AOvVaw0_oK7Qa0iNdLg5NF_halms&opi=89978449). Fork them, and modify them as much as needed to fit for env-S.

But I think this will also be quite some work.
Please tell me what expectations you have regarding the implementation.

**Comment by sylvestre** [comment]
yeah, sorry, it is no go for add a dependency to a shell for this kind of feature

Instead, you should contribute to nsh to move this feature into a new crate so that both us and nsh can use it.

Really sorry but we are not going to add a fork of shell as a new dep :(


Note: stackoverflow isn't a good source for me, sorry :(

**Comment by cre4ture** [comment]
will create new one

**Pull request closed without merging**
