### PR TITLE
Fix a TODO by making `conv_block_unblock_helper` consume the input.

### PR DESCRIPTION
**Pull request by resistor**

### CODE REVIEW

**Comment by anastygnome** [comment]
@resistor 

hmm, apart from the linter thing, clippy seems unhappy.

```
ERROR: `cargo clippy`: this argument is passed by value, but not consumed in the function body (file:'src/uu/dd/src/blocks.rs', line:25)
```

**Comment by anastygnome** [comment]
Also there seems to be a bunch of &buf that make the macos build unhappy

**Comment by sylvestre** [comment]
@resistor ping? Thanks

**Comment by resistor** [comment]
> @resistor Nice work here hmm, apart from the linter thing, clippy seems unhappy.
> 
> ```
> ERROR: `cargo clippy`: this argument is passed by value, but not consumed in the function body (file:'src/uu/dd/src/blocks.rs', line:25)
> ```

Done

**Comment by resistor** [comment]
> Also there seems to be a bunch of &buf that make the macos build unhappy

Should be resolved as well now.

**Comment by sylvestre** [comment]
The coverage implies that we don't have a test for this, is that correct?

**Comment by resistor** [comment]
> The coverage implies that we don't have a test for this, is that correct?

I suppose so? I'm not familiar with this functionality.

**Comment by sylvestre** [comment]
Would it be possible for you to write a test? thanks :)

**Comment by resistor** [comment]
Done to the extent I can figure out how.

**Pull request merged**
