### PR TITLE
feature(install) - add group & owner support + a refactor

### PR DESCRIPTION
**Pull request by sylvestre**
For this, move the chown & chgrp functions to uucore 
As we need this feature for install too

### CODE REVIEW

**Comment by sylvestre** [comment]
@rivy @Arcterus @nbraud 
show_info is using executable!() which uses module_path() to get the name of the program.

In this PR, I would like to use the actual binary name instead of uucore. Otherwise, it causes unexpected output and test failure like:
```
  left: `"uucore: changing group of \'/tmp\': Operation not permitted (os error 1)"`,
 right: `"chgrp: changing group of \'/tmp\': Operation not permitted (os error 1)"`', tests/common/util.rs:132:9
```

Any idea how to fix that? thanks

**Comment by rivy** [comment]
> 
> 
> @rivy @Arcterus @nbraud
> show_info is using executable!() which uses module_path() to get the name of the program.
> 
> In this PR, I would like to use the actual binary name instead of uucore. Otherwise, it causes unexpected output and test failure like:
> 
> ```
>   left: `"uucore: changing group of \'/tmp\': Operation not permitted (os error 1)"`,
>  right: `"chgrp: changing group of \'/tmp\': Operation not permitted (os error 1)"`', tests/common/util.rs:132:9
> ```
> 
> Any idea how to fix that? thanks

Yeah, don't do it this way... avoid UI I/O within `uucore` and instead refactor to return `Result<...>`'s.
Then, you can handle the results within the specific util itself including any UI.

**Comment by rivy** [comment]
@sylvestre , I know I read something about why you wanted to do this... but I can't find the email/post.
Would you reiterate your reasoning for the move?

**Comment by sylvestre** [comment]
>  Would you reiterate your reasoning for the move?

@rivy because the "install" command can change the ownership & group of a file. As we are already doing this for chgrp & chown, I think it would be better to have it uucore and make them reusable by both programs.

**Comment by sylvestre** [comment]
> Yeah, don't implement it as a straight copy of the code... avoid UI I/O within uucore and instead refactor to return Result<...>'s. Then, you can handle the results within the specific util itself including any UI.

I was hoping for something easier but you are right, I will do that, thanks :)

**Pull request merged**
