### PR TITLE
ignore the test_ls_styles

### PR DESCRIPTION
**Pull request by sylvestre**
Breaks the CI too often

### CODE REVIEW

**Comment by tertsdiepraam** [comment]
@sylvestre That's fair. Do you have an error message for the style test? I haven't seen that one break yet.

**Comment by sylvestre** [comment]
@tertsdiepraam 
```

---- test_ls::test_ls_order_birthtime stdout ----
current_directory_resolved: 
open: /tmp/.tmp5XjC2o/test-birthtime-1
run: /home/runner/work/coreutils/coreutils/target/debug/coreutils ls --time=birth -t
thread 'test_ls::test_ls_order_birthtime' panicked at 'assertion failed: `(left == right)`
  left: `"test-birthtime-1\ntest-birthtime-2\n"`,
 right: `"test-birthtime-2\ntest-birthtime-1\n"`', /home/runner/work/coreutils/coreutils/tests/by-util/test_ls.rs:580:5

```

Could you please try to make them work again?

**Comment by miDeb** [comment]
FWIW the re_locale regex `r"[a-z-]* \d* \w* \w* \d* [A-Z][a-z]{2} \d{2} \d{2}:\d{2} test\n"` fails because it expects two digits for the day, but it's "May  1" (notice two spaces between May and 1 at least on my machine)

**Comment by tertsdiepraam** [comment]
Oh that's hilarious! I'll fix it!

**Comment by sylvestre** [comment]
ah ah, well spotted :)

**Pull request merged**
