### PR TITLE
Clippy Pedantic Acceptable Commits Try Again

### PR DESCRIPTION
**Pull request by dcampbell24**
I changed the wording of a commit to include `clippy::`.

https://github.com/uutils/coreutils/pull/6738
https://github.com/uutils/coreutils/pull/6746

### CODE REVIEW

**Comment by tertsdiepraam** [comment]
You can force push to branches to overture old commits so you don't have to create new PRs. I'll try to look at this tomorrow

**Review by tertsdiepraam — APPROVED** [review]
Great! Yeah this all looks good!

**Comment by tertsdiepraam** [comment]
@sylvestre @cakebaker How are these GNU tests doing? Are they usual suspects for intermittently failing tests?

**Comment by cakebaker** [comment]
@tertsdiepraam: yes, they are the usual suspects for intermittently failing tests :|

@dcampbell24: thanks!

**Comment by BenWiederhake** [comment]
Yes, please use force-push in the future to preserve discussions about a PR :)

**Comment by dcampbell24** [comment]
Sure, I didn't know that I could do that.

**Pull request merged**
