### PR TITLE
ci: use `-pcoreutils` when running clippy

### PR DESCRIPTION
**Pull request by cakebaker**
While looking at https://github.com/uutils/coreutils/pull/6246 I wondered why those clippy warnings were not caught by our CI. <del>The reason is probably that `${{ matrix.job.cargo-options }}` is never defined and so I replaced it with `${{ steps.vars.outputs.CARGO_FEATURES_OPTION }}`.</del> <del>I couldn't figure out the reason and my two attempts to make the CI fail on those warnings failed. And so this PR is just about removing the undefined `${{ matrix.job.cargo-options }}`.</del> It looks like the reason is that we select the utils for the specific platform and then run clippy on those  packages (which don't contain the tests). By running clippy on the `coreutils` package with the `--features` flag, the tests are also checked by clippy.

### CODE REVIEW

**Comment by cakebaker** [comment]
Changes since last push:

* changed `${{ steps.vars.outputs.CARGO_FEATURES_OPTION }}` to `--all-features` as the original approach didn't work

**Comment by cakebaker** [comment]
Changes since last push:

* removed `--all-features`

**Comment by cakebaker** [comment]
Changes since last push:

* removed unused `CARGO_FEATURES_OPTION` from `style_format` job
* used `--features ${{ matrix.job.features }} -pcoreutils` instead of `${{ steps.vars.outputs.CARGO_UTILITY_LIST_OPTIONS }}` when running clippy
* removed code used to set `CARGO_UTILITY_LIST_OPTIONS`

**Comment by cakebaker** [comment]
Changes since last push:

* fixed warnings from the [redundant_clone](https://rust-lang.github.io/rust-clippy/master/index.html#/redundant_clone) lint

**Comment by cakebaker** [comment]
Changes since last push:

* moved unit tests from `tests/by_util/test_env.rs` to `src/uu/env/src/env.rs`
* fixed the fixes from the previous push

**Comment by cakebaker** [comment]
Changes since last push:

* fixed "the borrowed expression implements the required traits" warnings in the `env` tests introduced with the previous push

**Review by BenWiederhake — APPROVED** [review]
Does what it says on the tin, and evidently you "tested" it by finding actual problems in the code. Yay! :)

Do you know why the Windows CI fails? This doesn't look like a flake:
```console
$ cargo nextest run --profile ci --hide-progress-bar --features=windows -p uucore -p coreutils
<SNIP downloading and compiling>
   Compiling rstest v0.19.0
   Compiling unindent v0.2.1
   Compiling hex-literal v0.4.1
    Finished `test` profile [unoptimized + debuginfo] target(s) in 1m 56s
error: creating test list failed

Caused by:
  for `coreutils::bin/coreutils`, command `'D:\a\coreutils\coreutils\target\debug\deps\coreutils-08f81a256ac17834.exe' --list --format terse` exited with code 0xc0000135: The specified module could not be found. (os error 126)
--- stdout:

--- stderr:

---
Error: Process completed with exit code 1.
```

**Comment by cakebaker** [comment]
@BenWiederhake it looks like it was a temporary issue

**Review by BenWiederhake — APPROVED** [review]
Looks still good :+1:

**Pull request merged**
