### PR TITLE
tail: Reactivate ---presume-input-pipe option

### PR DESCRIPTION
**Pull request by Joining7943**
During #3905, I missed to reactivate the ---presume-input-pipe option. This fix will reactivate it.

### CODE REVIEW

**Comment by tertsdiepraam** [comment]
Okay, seems like I was a bit quick on the merge last time, we should at least have the same features with each PR. Any other missing functionality from that PR? And is there a reason to keep this as a draft or is it ready (when the conflicts are fixed).

**Comment by Joining7943** [comment]
> Okay, seems like I was a bit quick on the merge last time, we should at least have the same features with each PR. Any other missing functionality from that PR? 

Sorry for that. No, `---presume-input-pipe` is the only missing functionality. This was still a draft because I needed tests and a way to detect that we're not using the wrong function. Additionally, I was a little bit confused by some performance tests when I used `---presume-input-pipe`, so I needed some additional checks to verify we're doing the right thing.

**Comment by Joining7943** [comment]
@tertsdiepraam Not meant badly, but I don't think this option is crucial. I guess gnu tail has this hidden, undocumented option because there is a perfomance difference between `tail ---presume-input-pipe random_ascii_505MB` and `tail random_ascii_505MB`.

```
❯ wc --lines --words --bytes --chars --max-line-length random_ascii_505MB.BIG            
  5000000  12650766 505000000 505000000       100 random_ascii_505MB.BIG
```

Maybe they used the option for testing purposes. However, we don't have this performance difference. Tailing this file with bounded_tail() or unbounded_tail() is comparable fast in our version of tail.

**Comment by tertsdiepraam** [comment]
Oh I agree that it's not very useful, but if we want to claim full compatibility, then this option should be included and should probably do what it implies. The testing argument could also apply to us. However, there are indeed also some of those triple dash arguments we silently ignore because they don't apply.

**Comment by Joining7943** [comment]
Sure. No problem. I didn't want to stress :) Just for completeness and maybe it helps: When I readded the functionality, I was looking at the code of tail in gnu's coreutils and I'm very sure, that it's all about not using file seeks. It's a little bit buried, but I think it can be stripped down to: in case of `---presume-input-pipe`, they use `pipe_lines()`, `pipe_bytes()`, we use `unbounded_tail()`.

**Comment by tertsdiepraam** [comment]
That seems to match our previous investigations into this (see https://github.com/uutils/coreutils/issues/2907#issue-1111615209), so I think you're correct!

**Comment by Joining7943** [comment]
@tertsdiepraam Are we ready here?

**Comment by tertsdiepraam** [comment]
Yeah, all good!

**Pull request merged**
