### PR TITLE
uucore: leading zeros are ignored in version compare

### PR DESCRIPTION
**Pull request by shinhs0506**
should fix `tests/misc/sort-version.sh`

### CODE REVIEW

**Comment by tertsdiepraam** [comment]
Have you seen the previous discussion on this? In particular this thread: https://github.com/uutils/coreutils/pull/4325

**Comment by shinhs0506** [comment]
@tertsdiepraam Ah, i totally missed that. thanks for pointing it out. 

I was using [this](https://www.gnu.org/software/coreutils/manual/html_node/Version_002dsort-ordering-rules.html) as a reference for the non-stable sorting. And i guess stable sorting just preserves the relative order in case when the values are equal?

**Comment by tertsdiepraam** [comment]
Indeed. I'm not sure how intentional that is on GNU's side. We could start a discussion there too, because it is (in my opinion) a bit strange.

**Comment by shinhs0506** [comment]
they do specify `--stable` [here](https://www.gnu.org/software/coreutils/manual/html_node/sort-invocation.html). Would make sense if they wanted something deterministic.

**Comment by tertsdiepraam** [comment]
Interesting, I hadn't seen that sentence. That makes sense if it's about the last resort comparison. We shoud do the same then!

**Comment by shinhs0506** [comment]
@tertsdiepraam should be ready for review

**Comment by tertsdiepraam** [comment]
This does not fix the issue for both stable and unstable does it? I would imagine that version_cmp needs to stake a `stable` flag that defines the behaviour. Or do you think it should he fixed in some other way?

**Comment by shinhs0506** [comment]
In my opinion, the comparison function should return `Cmp::Ordering::Equals` if they are equal. And the Caller should handle the equal case as it is done [here](https://github.com/uutils/coreutils/blob/42bf580f132cd4951b31837f02d2d2a4849e8ecc/src/uu/sort/src/sort.rs#L1637-L1645)

And i believe this pr fixes both stable and unstable case

**Comment by tertsdiepraam** [comment]
Returning equal does make sense. How does this sovle both cases, though?

**Comment by shinhs0506** [comment]
I can't find anything on how `ls` breaks ties. Nothing will necessarily be 'broken' because it would still sort correctly in a non-deterministic way which makes sense because `ls` doesn't do last resort comparison as you said.

If we wanted to provide our own rules, and make `ls` behave similar to `sort`, that would be a reasonable approach too.

**Comment by tertsdiepraam** [comment]
Yeah not really broken, but it would be something we might need to fix. That could just mean that we need to open an issue, but we do need to know. Could you do some testing with `ls` with GNU and uutils before and after this patch?

**Comment by shinhs0506** [comment]
I did some manual testing and looks like GNU's `ls` also behaves like `sort` when breaking ties.

**Comment by sylvestre** [comment]
Thanks :)
Still an improvement over the previous state :)

**Pull request merged**
