### PR TITLE
mv: fix error when moving directory to itself

### LINKED ISSUE #3770: mv removing data
rust mv is removing data and directory structure (ignoring the bad practice demonstrated here)
**gnu mv**
```
mkdir mv-test
cd mv-test
mkdir mv-test-sub
touch test.txt mv-test-sub/test2.txt
cd mv-test-sub
mv ../* .
/usr/bin/mv: cannot move '../mv-test' to a subdirectory of itself, './mv-test'
ls
test2.txt  test.txt
```

#results in warning, but all files exist as expected - i.e. moved into current subdirectory.

**rust mv**
Running the above results in the mv-test-sub directory and the test2.txt inside being removed

Tested with 0.0.14, the latest git, and 0.0.12 on SLES 15SP3 and (latest git only) on Ubuntu 22.04 systems. 
manually built using make method:
PROFILE=release  make PREFIX=location install

### PR DESCRIPTION
**Pull request by Fuchczyk**
Fixes #3770

Behaviour of the rewritten mv utility was changed to match this in gnu's mv. Moving folder into itself does not stop entire process, but only results in showing appropriate error and changing exit code to 1 (of course moving folder into itself is skipped).

### CODE REVIEW

**Comment by sylvestre** [comment]
Could you please add a test to make sure we don't regress in the future?
Thanks

**Comment by Fuchczyk** [comment]
Test has been added.

**Comment by Fuchczyk** [comment]
Workflow failed because of cspell issue with word 'Exitcode', removed from comments.

**Comment by sylvestre** [comment]
And

`Congrats! The gnu test tests/mv/into-self is no longer failing!` passes
bravo!

**Pull request merged**
