### PR TITLE
od: fix parsing of hex input ending with `E`

### LINKED ISSUE #4981: `od: --skip-bytes argument '0x20E' too large`
I apologize in advance for creating such a vague and incomplete issue, I basically have no idea how `od` works but it is [erroring out](https://gitlab.archlinux.org/archlinux/mkinitcpio/mkinitcpio/-/issues/196#note_102416) when used in Arch Linux's `mkinitcpio` tool.

```
==> Building image from preset: /etc/mkinitcpio.d/linux.preset: 'default'
==> Using default configuration file: '/etc/mkinitcpio.conf'
  -> -k /boot/vmlinuz-linux -g /boot/initramfs-linux.img --microcode /boot/intel-ucode.img
od: --skip-bytes argument '0x20E' too large
==> ERROR: invalid kernel specified: '/boot/vmlinuz-linux'
```

`mkinitcpio` is written in bash script and the problematic `od` call is specifically on this [line](https://gitlab.archlinux.org/archlinux/mkinitcpio/mkinitcpio/-/blob/59f9d06e03c7cec1f097e2e1eeb574a65bce7c05/functions#L149):
```
offset="$(od -An -j0x20E -dN2 "$1")" || return
```

Everything works fine when GNU coreutils are used.

### PR DESCRIPTION
**Pull request by TheDcoder**
This should fix #4981.

This is my first contribution in Rust and I just started learning it today, so pardon me if I missed something, do let me know and I will fix it promptly!

Special thanks to @tertsdiepraam for finding the bug before I even started learning Rust, thus saving me a bunch of time :smile:

### CODE REVIEW

**Comment by sylvestre** [comment]
cool, could you please add a test in tests/by-util/test_od.rs ?

**Comment by TheDcoder** [comment]
@sylvestre Ah, I haven't gotten far enough in "the book" to do that yet. Though I did take a look if I can just modify some existing test, but there doesn't seem to be (I might be wrong).

It's worth noting that hex input ending with `B` didn't have this bug since the initial implementation (459db47) because it already had the safeguard which I added to `E`.

So IMHO writing a new test is out of scope for both this PR and my technical knowledge in rust :sweat_smile:

Also I did add a simple assertion to check if `0XE == 14` :smile: 

Let me know what you think, if a new test is needed then I will need more time to study the book and implement it.

**Comment by sylvestre** [comment]
Adding a test should be trivial
Just copy another example from here:
https://github.com/uutils/coreutils/blob/main/tests/by-util/test_od.rs

**Comment by sylvestre** [comment]
@TheDcoder https://www.phoronix.com/forums/forum/phoronix/latest-phoronix-articles/1398170-uutils-0-0-20-improves-gnu-coreutils-compatibility-for-this-rust-written-replacement/page7
Happy to read this ;)

**Comment by TheDcoder** [comment]
@sylvestre Thank you so much once again! Crazy how small things like this end up making such a big difference :)

I'm working on my first rust [project](https://github.com/TheDcoder/rsudoas) right now (it's empty since I haven't committed any code).

**Comment by sylvestre** [comment]
we have plenty of other good first bugs here if you want

**Pull request merged**
