### PR TITLE
df: -h -H shouldn't cause an error #3366

### PR DESCRIPTION
**Pull request by gmnsii**
Solve issue #3366. Make -h and -H override each other (the latest take the priority)

### CODE REVIEW

**Comment by tertsdiepraam** [comment]
Looks good, but could you maybe extend this to all arguments? Then we don't have to go back and fix those later. All arguments should override themselves and the arguments they now conflict with. For example,
```
df --sync --sync
```
should work and also
```
df --block-size=3K -k
```
should override each other.

**Comment by gmnsii** [comment]
No problem. By the way, `df --block-size=3K`doesn't seem to work, you need to put 3000. (It work on GNU `df`)

Screen Shot 2022-04-17 at 1 03 42 AM

**Comment by tertsdiepraam** [comment]
Thanks for fixing this! I'll open an issue for the `--block-size` parsing :)

**Comment by gmnsii** [comment]
I finished. `--output` still conflicts with `-i`, `-P` and `-T` because it is the same in the GNU version

**Comment by gmnsii** [comment]
But if we want all utils to work exactly like their GNU couterpart we need to do this with all of them:

GNU:
Screen Shot 2022-04-17 at 1 56 31 AM



uutils:
Screen Shot 2022-04-17 at 1 56 51 AM

**Comment by sylvestre** [comment]
not a big deal but please try to avoid screenshots: search isn't able to parse the content :)

**Comment by gmnsii** [comment]
Sorry about that

**Comment by sylvestre** [comment]
don't be, it isn't a big deal :)

**Comment by tertsdiepraam** [comment]
> But if we want all utils to work exactly like their GNU couterpart we need to do this with all of them

Yep, it's an ongoing effort :) Feel free to do this for more utils if you want!

**Comment by gmnsii** [comment]
A test for sort is failing the CI, which is wierd since I didn't touch anything related to it.
```
failures:
    test_sort::test_numeric_floats_and_ints

test result: FAILED. 1661 passed; 1 failed; 28 ignored; 0 measured; 0 filtered out; finished in 407.86s
```

```
---- test_sort::test_numeric_floats_and_ints stderr ----
thread 'main' panicked at 'Command was expected to succeed.
stdout = 0
.02

 stderr = ', tests\common\util.rs:174:9
```

**Comment by gmnsii** [comment]
CI is now passing

**Comment by tertsdiepraam** [comment]
Almost ready to merge, but there's a chance one of the tests (`test_df_output_overridden`) might fail due to another PR I just merged. I'll rerun the checks to be sure.

**Comment by gmnsii** [comment]
Ok

**Comment by tertsdiepraam** [comment]
> CI is now passing

Yeah, some tests are flaky. We reran the failed checks.

**Comment by gmnsii** [comment]
The FreeBSD testsuite failed while installing packages

```
[5/8] Installing gettext-runtime-0.21...
[5/8] Extracting gettext-runtime-0.21: .........Connection to localhost closed by remote host.
Error: The process '/usr/bin/ssh' failed with exit code 255
```

**Comment by sylvestre** [comment]
not your fault, thanks

**Comment by sylvestre** [comment]
Cool, seems that it fixed a GNU test:

`Congrats! The gnu test tests/df/df-symlink is no longer failing!`

**Pull request merged**
