### PR TITLE
base64: Moved argument parsing to clap.

### PR DESCRIPTION
**Pull request by ricardoaiglesias**
Moved argument parsing to clap and added tests to cover using "-" as
stdin, passing in too many file arguments, and updated the "wrap" error
message in the tests.

`base64` is a similar application to `base32`, so I ended up modifying similar things to it, such as adding similar tests.

### CODE REVIEW

**Comment by sylvestre** [comment]
Seems that a lot of code is duplicated with base32. Is it possible to factorize some of the code ?
thanks

**Comment by ricardoaiglesias** [comment]
Sure. One idea I had for refactoring was to create a `base_common` directory somewhere with two functions defined: 

````
pub mod base_common;
pub struct Config { /* config for base32 and base64 goes here. */ }; 

pub fn handle_input<R: Read>(input: &mut R, format: Format, line_wrap: Option<usize>, ignore_garbage: bool, decode: bool){}

// The "Box <dyn Read>" is so that we can use this function for both argument parsing and opening+returning an open file handle
// or stdin, which both implement the Read trait. 
pub fn parse_base_cmd_args(args: impl uucore::Args) -> (base_common::Config, Box<dyn Read>) {}
````

And then for the implementation of `base64` and `base32`, it would be something along these lines: 
````
// base64
pub fn uumain(args: impl uucore::Args) -> i32 {
   let config, input_file_obj = parse_base_cmd_args(args);
   handle_input(input_file_obj, config, format::Base64);
  0
} 
````

````
// base32
pub fn uumain(args: impl uucore::Args) -> i32 {
   let config, input_file_obj = parse_base_cmd_args(args);
   handle_input(input_file_obj, config, format::Base32);
0
} 

````
What do you think? If you agree, where in the source tree should I put these functions?

**Comment by sylvestre** [comment]
either uucore `src/uucore/src/lib/` or you put in `base32/src/base_common.rs` and import it from base64

**Comment by ricardoaiglesias** [comment]
Note, I now return a `Result<Config, String>` from `Config::from` because I found that executing the `crash!` macro (which uses the `executable!` macro to print out the current executable) uses the path of the _current_ module, not the path of the module it was compiled as a part of (so even though I would be calling `crash!` within the `base64` executable, it would print out `base32: error` instead of `base64: error`). 

Returning a string and `crash!`-ing in `uumain` was a workaround for this.

**Comment by ricardoaiglesias** [comment]
I think this is ready to be merged.

**Comment by sylvestre** [comment]
indeed, many thanks :)

**Pull request merged**
