### PR TITLE
cp: added options no-clobber, recursive, link, interactive

### PR DESCRIPTION
**Pull request by jerenept**
re: PR  #955 (which is closed now)

### CODE REVIEW

**Comment by Arcterus** [comment]
It looks like there is still some code commented out, so is this not quite done?

**Comment by jerenept** [comment]
Ya it isn't, I'm still to figure out --backup, but --update should be simple enough, I'm gonna do that next. Also I got lots of tests to write for all these here options (didn't do any of that yet). I'll commit to that branch so thy should show up here.

**Comment by Arcterus** [comment]
Alright, let me know when you finish.

**Comment by Arcterus** [comment]
I believe #1051 incorporated these changes, so I'm going to close this pull request.

**Pull request closed without merging**
