### PR TITLE
Various improvements to chroot

### PR DESCRIPTION
**Pull request by sylvestre**
Try to fix the issue `skipped test: user nobody lacks execute permissions` like
https://github.com/coreutils/coreutils/blob/master/tests/cp/special-bits.sh#L45

(but this line fails as it is parsed as `cp -p c c2 ` is part of the chroot args

### CODE REVIEW

**Comment by sylvestre** [comment]
And glad we are now testing chroot for real :)

**Review by tertsdiepraam — COMMENTED** [review]
I'm not sure I fully understand the `--skip-chdir` implementation. It seems to me that `--skip-chdir` implies that the `chdir` never happens, not that it still happens and is then restored?

**Comment by sylvestre** [comment]
You are correct :)
we do it internally to make sure that the chroot(".") works but, in the chroot, we are back in the initial dir

**Comment by tertsdiepraam** [comment]
Hmm I see, so we can't do something like this?
```rust
let err = unsafe {
    chroot(CString::new(root).unwrap().as_bytes_with_nul().as_ptr() as *const libc::c_char)
};
// some error handling
if !skip_chdir {
    std::env::set_current_dir(root).unwrap();
}
 ```

**Comment by sylvestre** [comment]
I tried this but it didn't work (but maybe it is my fault). I will have a look again

**Comment by sylvestre** [comment]
Yeah:
`Warning: Changes from 'main': PASS +1 / FAIL +7 / ERROR +0 / SKIP -8 `

**Comment by sylvestre** [comment]
> Hmm I see, so we can't do something like this?

worked great, thanks :)

**Pull request merged**
