### PR TITLE
uucore: refactor show_error! macro

### PR DESCRIPTION
**Pull request by ycd**
Follow up PR for the https://github.com/uutils/coreutils/pull/2273#issuecomment-848310698. 

* Deleted `show_info!` macro.
* Deleted `error:` prefix from the `show_error!`macro.
* Changed `show_info!` macro with `show_error!` across all utilities. 
* Updated tests.

### CODE REVIEW

**Comment by ycd** [comment]
Yay!

**Comment by tertsdiepraam** [comment]
Awesome! @sylvestre do you agree with this solution and does this have any impact on the GNU tests?

**Comment by ycd** [comment]
I think it definitely effects GNU tests but in a positive way.

**Comment by sylvestre** [comment]
Clearly, with this patch
`GNU testsuite = TOTAL: 601 / PASS: 149 / FAIL: 339 / ERROR: 22`
Before:
`GNU testsuite = TOTAL: 601 / PASS:  144 / FAIL:  344 / ERROR: 22`

**Comment by sylvestre** [comment]
Improved the results:
https://github.com/uutils/coreutils-tracking

**Pull request merged**
