### PR TITLE
uucore (re)integration

### PR DESCRIPTION
**Pull request by Arcterus**
Splitting off `uucore` into a separate repository was a mistake.  Making changes to `uucore` as it exists right now is painful as generally these changes also affect utilities in the `coreutils` repository.  Thus, this PR reintegrates `uucore` into `coreutils` as a subtree (see [git-subtree](https://raw.githubusercontent.com/git/git/master/contrib/subtree/git-subtree.txt)) and updates the utilities accordingly.

### CODE REVIEW

**Comment by Arcterus** [comment]
I just noticed the subtree commit isn't signed.  That's a little annoying, but I don't think I'll bother to fix it.

**Comment by sylvestre** [comment]
Kudos for keeping the history!
I do think it should be done.

@rivy wdyt?

**Comment by sylvestre** [comment]
we will have some clippy warnings to fix

**Comment by Arcterus** [comment]
BTW, I don't know if it's the same for you, but GitHub seems to be defaulting to "squash and merge" rather than "create a merge commit" after I used it for #1540.  I'd really hate to accidentally squash all the history into one commit (as I assume that's what would happen), so be careful when merging.

**Comment by sylvestre** [comment]
Yeah, as I am using both features often, I am always careful :)

**Comment by Arcterus** [comment]
@rivy is there anything you would like changed?  If not, I’d like to get this merged sooner rather than later.

**Comment by rivy** [comment]
I'll look at it later today.

**Comment by rivy** [comment]
Overall, it looks good; but, `cargo publish --dry-run` is failing. It's likely because of the `OsString`/`arg_os()` updates done since `uucore-0.0.4` was published. I'd probably fix that prior to merging (ie, commit and publish a `0.0.5` version of `uucore` + update deps to `0.0.5`).

Syncing versions between at least `coreutils`, `uucore`, and `uucore_procs` might be a good idea as well so that we can continue to simply tag published "touchstone" versions.

**Comment by Arcterus** [comment]
Okay, I’ll see if I can publish `0.0.5` later today.

**Comment by equal-l2** [comment]
Do you have any update?
This blocks https://github.com/Homebrew/homebrew-core/pull/55987.

**Comment by rivy** [comment]
@uutils/maintainers , I'm going to try to land a version of this merge this weekend as a straight code merge (no complicating git-subtree management; wip => d11551c3d15860c4466cdecb33a7f0ac44b62313). History is still [preserved](https://github.com/rivy/rs.coreutils/tree/merge.uucore), just filtered into the proper location in 'coreutils'.

I prefer this to adding a 'git-subtree' complication. And it's simple enough that I should be able to get it done by the end of the weekend for review.

Any objections? If not, I'll close this in deference to the new PR (#1627).

**Comment by sylvestre** [comment]
Works for me, thanks!

**Comment by rivy** [comment]
Closed by alternate PR #1627.

**Pull request closed without merging**
