### PR TITLE
uucore: update data_encoding and add wrap_write()

### PR DESCRIPTION
**Pull request by Arcterus**
For the time being, I am planning on restructuring various things to support arbitrary writers/readers rather than relying on stdio/stdin/stderr.  I am also planning on preventing arbitrary panics (which could have occurred in the previous implementation).

### CODE REVIEW

**Comment by Arcterus** [comment]
This also stops trying to install `libstdbuf.so` when using `make install` (as that file is autogenerated by `stdbuf` now).  We will also now call `make install` on Travis to try to ensure the Makefile setup is in sync with the Cargo setup.

**Comment by Arcterus** [comment]
@mpkh

**Comment by mpkh** [comment]
yes, sorry for delay

**Comment by Arcterus** [comment]
No worries :)

**Pull request merged**
