### PR TITLE
Various Windows fixes

### PR DESCRIPTION
**Pull request by retep998**
This is blocked on bumping a few crates on crates.io

### CODE REVIEW

**Comment by Heather** [comment]
@retep998 sorry but moving some utils alike `mv` to Linux only is not correct, they were working just fine, the problem may be somewere else

**Comment by retep998** [comment]
Maybe they were working just fine a long time ago, but right now they don't build and they make use of unix specific things like `std::os::unix::fs::MetadataExt`. I don't know how that can be considered working fine. Later on I'll probably see if I can get them building on Windows, but for now I moved them to unix-only so that I wouldn't be blocked on them and could get some of the easier ones fixed.

**Comment by Heather** [comment]
@retep998 yes, it was long ago and as far as I see for now they are hardly outdated

**Comment by Heather** [comment]
Okay there is tracking issue for mv touch and du https://github.com/uutils/coreutils/issues/658

**Pull request merged**
