### PR TITLE
Fixes for Redox

### PR DESCRIPTION
**Pull request by jackpot51**
This contains a number of small fixes for Redox support. It should not affect other platforms, at all. After this, there are still some minor fixes I am waiting on other crates to implement before Redox builds could be enabled in CI.

I have organized the changes into small commits, please view and evaluate each commit by itself if the whole patchset does not make sense.

### CODE REVIEW

**Comment by sylvestre** [comment]
Excellent and looks great. Do you think it would be possible to add a check in the CI to prevent this from happening?

**Comment by jackpot51** [comment]
@sylvestre this is not 100% building on Redox yet, because of awaiting upstream crate releases for filetime and termsize. When that is done, I can add the CI test required

**Comment by sylvestre** [comment]
Excellent, thanks

**Comment by jackpot51** [comment]
Here was the commit getting it working 100%, but at the cost of having to patch some crates: https://gitlab.redox-os.org/redox-os/uutils/-/commit/cfb9f9bc594395edc3afe442889506efa169e158

**Comment by sylvestre** [comment]
@jackpot51 I hope you are doing great. Do you know if we could have redox in the CI now ? :)
thanks

**Comment by jackpot51** [comment]
I will have to check if filetime and termsize ever got updated

**Comment by sylvestre** [comment]
thanks!

**Pull request merged**
