### PR TITLE
ls: fix quoting alignment, add tests for default quoting style in TTY and quoting alignment

### LINKED ISSUE #6386: ls: Unexpected space before stdout in TTY output
I was fixing [TODOs](https://github.com/uutils/coreutils/blob/8078fca99b71946ff5865c097d0d42bd6818ee92/tests/by-util/test_ls.rs#L2659C12-L2659C16) in the testsuite to check TTY outputs.

And I realized that there is a seemingly unexpected character (presumably a space) that gets printed.

```
❯ /bin/ls "$(echo -e 'a\nb')" --hide-control-chars  
'a'$'\n''b'

❯ target/debug/ls "$(echo -e 'a\nb')" --hide-control-chars
 'a'$'\n''b'
^
Unexpected space
```

The default escaping strategy when outputing to a TTY is `shell-escape`. Strangely, the bug does not appear when output is not a TTY but with `--quoting-style=shell-escape` set, as already [checked by the testsuite](https://github.com/uutils/coreutils/blob/8078fca99b71946ff5865c097d0d42bd6818ee92/tests/by-util/test_ls.rs#L2678)

### PR DESCRIPTION
**Pull request by RenjiSann**
Fixes #6386

### CODE REVIEW

**Comment by sylvestre** [comment]
I guess you saw that some jobs are failing

**Comment by RenjiSann** [comment]
> I guess you saw that some jobs are failing

Yes, sorry for that. I always forget about linting and windows stuff.

**Comment by RenjiSann** [comment]
@sylvestre if you don't mind taking look. I don't understand why is the macos test failing.

**Comment by sylvestre** [comment]
@RenjiSann it isn't your fault. it is unrelated

**Comment by sylvestre** [comment]
LGTM, thanks

**Pull request merged**
