### PR TITLE
Add Sphinx documentation to generate man pages

### PR DESCRIPTION
**Pull request by Arcterus**
This is my first time using Sphinx, so please let me know if there's something wrong (or a less hacky way to set the description of the man page).

I also updated the dependencies and sped up the Makefile while adding the documentation generation.  As part of the documentation efforts, I have also updated the `README` to more accurately reflect how to build and install the project.

### CODE REVIEW

**Comment by Arcterus** [comment]
Don't merge this yet.  I'm considering whether it would be better to use Asciidoctor.

**Comment by Arcterus** [comment]
@ids1024 does Redox have support for Python at the moment?  That may influence this decision.

**Comment by ids1024** [comment]
Redox has limited support for Python currently. But at the moment things are still generally cross-compiled, so don't worry about that.

You may want to look at mdbook for generating documentation, which is in Rust and is what [the Rust book](https://github.com/rust-lang/book) uses, for instance.

**Comment by Arcterus** [comment]
Alright, it's good that Python isn't an issue then.

I remember looking at mdBook and deciding against it because it could not generate man pages, which is the primary use case here.  The ability to generate HTML is more of a bonus.

**Comment by Arcterus** [comment]
@mpkh I think we should just use Sphinx, so can you merge this at some point?

**Comment by mpkh** [comment]
@Arcterus afair we did fixed appveyor, isn't it? other than that it's fine

**Comment by Arcterus** [comment]
Apparently `cp` didn’t mark which version of `winapi` it wanted, and a breaking change just came out, so it broke.  I just pinned the dependency to the old version of `winapi` for now.

**Pull request merged**
