### PR TITLE
comm: move help strings to markdown file

### PR DESCRIPTION
**Pull request by cakebaker**
#4368 and add an "after help" text.

### CODE REVIEW

**Comment by tertsdiepraam** [comment]
I think we need another category apart from after help. I think the format of `--help`/`uudoc` should be something like this:
```
<usage>
<short summary>

<long description>

<options>

<after help>
```
What GNU does is that they explain some more about the options in the after help. So for instance, explaining the valid formats that an argument accepts.

I think this is what `long_help` in clap is for, but we weren't really using that. We could adapt the macros such that it uses the first line of the current about as short summary and the long description as the rest. For now I suppose using after help is fine though.

**Comment by cakebaker** [comment]
Hm, I'm not sure whether an additional category is needed because `help_about!` already supports multi-line text (for example, [base32](https://github.com/uutils/coreutils/blob/main/src/uu/base32/base32.md) uses it).

Clap's `long_help` is not helpful in this situation because it defines the long help for a single argument and not for the program, see https://docs.rs/clap/latest/clap/struct.Arg.html#method.long_help

**Comment by tertsdiepraam** [comment]
Ah got confused. I meant [`long_about`](https://docs.rs/clap/4.0.29/clap/struct.Command.html#method.long_about). Nevertheless, I think you're right and we do not need anything else. I think what you wrote as after help here belongs in the about. Do you agree?

**Comment by cakebaker** [comment]
Yes, that makes sense and I fixed it in the latest push.

**Comment by tertsdiepraam** [comment]
Thanks!

**Pull request merged**
