### PR TITLE
Add the codecov badge

### PR DESCRIPTION
**Pull request by sylvestre**

### CODE REVIEW

**Comment by rivy** [comment]
I'm for this ... but, code coverage calculation is, at the moment, sub-par.

I'm experimenting with `grcov` to improve cross-platform coverage, but I'm stuck trying to get coverage for the workspace packages. Right now, only `uutils` gets any coverage information.

I think I'm going to have to include the workspace packages as modules to get coverage information generated for them. Any ideas?

**Comment by sylvestre** [comment]
@rivy my team at Mozilla developed grcov. If you have more details, they can probably help :)

**Comment by rivy** [comment]
I've got code coverage building and sending coverage reports for macos, windows, and unix platforms (see <https://github.com/rivy/rs.coreutils/runs/572806040?check_suite_focus=true>; built from f695cdc9). But, it's only generating results for `uutils` (the [[bin]] for the crate).

I believe than the various utility packages in the workspace will have to somehow be pulled in as modules before any code coverage can be accomplished on them. I'm not sure how to do that and preserve the current build framework.

**Comment by rivy** [comment]
After hacking on this for a day or so, I've discovered that the coverage instrumentation needs source files to be in the *src* directory (even for the workspace sub-packages) in order to actually evaluate the lines. I don't know whether it's the compiler instrumentation or `grcov` that has the problem, but at least it's a workable solution.

I'm in the midst of a refactoring all the sub-package files to be in their respective *src* directories onto a test branch. I'll keep you updated on the progress and hopefully success of this change.

**Comment by rivy** [comment]
After a reorganization of the source files into more "standard" locations and hacking the coverage filenames, I'm getting an improved coverage report.

original @ <https://codecov.io/gh/rivy/rs.coreutils/tree/7c0132354576701771dd29bad404b4106a50669b>
re-org'd @ <https://codecov.io/gh/rivy/rs.coreutils/tree/528d14212cf83542bb623c5011bc37ee4ba1bf2c>

Would you mind taking a look and commenting?

**Comment by rivy** [comment]
Argh! That was a day-long hack task! 
But I finally have reasonable, working, code coverage branch.

🚀 

Take a look at [rivy:rust.coreutils/rf.reorg-codecover](https://github.com/rivy/rs.coreutils/tree/rf.reorg-codecover) and the corresponding [CodeCov report](https://codecov.io/gh/rivy/rs.coreutils/tree/26ee5f8d249ccdf93cd6442f048e397633cadb8d).

My plan is to release a PR for it Monday right after I merge #1449.
We can then merge it and this on top of it.

Sound good?

**Comment by sylvestre** [comment]
this is great, bravo :)

I would ignore tests/ as it isn't super interesting info.

**Comment by rivy** [comment]
I was going to take out the "tests" directory, but then I found a bug by reviewing the uncovered lines. The uncovered section shown at <https://codecov.io/gh/rivy/rs.coreutils/src/7f81bf3de1a2df3362f9fe2506ad7d00e8b7feb3/tests/test_du.rs#L16...32> points out that `test_du_basics()` is actually failing to call `_du_basics()`. So, I think it could be useful.

`grcov` is close to merging a PR that can exclude line or branch coverage for specific lines/sections (see https://github.com/mozilla/grcov/pull/416). When that merges, I should be able to ignore the internal branch coverage errors in the `assert` functions, and we could shoot for 100% coverage in tests. Once achieved, anything less could be seen as a testing bug.

**Comment by sylvestre** [comment]
55% coverage, well done :)

**Comment by rivy** [comment]
👍 

I'm working on a quick PR to condense redundant CI testing on AppVeyor and Travis to reduce the total time to success/failure for a given commit. It should come down to a total of about 15 minutes (median) time to success/fail (from the median of about an hour that it's taking now).

I'm also attempting a CodeCov configuration change to make it informational (ie, never fail the build).

**Comment by rivy** [comment]
I added the commits for condensed CI and fixed CodeCov to my already open PR #1480.

**Pull request merged**
