### PR TITLE
Fix 3722: rm: when error during recursive, stops prematurely

### LINKED ISSUE #3722: rm: when error during recursive, stops prematurely
uutils doesn't remove `b/d` in the following example

```bash
$ mkdir -p b/a/p
$ mkdir b/c b/d
$ chmod -w b/a
$ rm -rf b
rm: cannot remove 'b': Permission denied
$ ls b
a d
```

but GNU removes `b/d`

That's probably because of [`fs::remove_dir_all`](https://doc.rust-lang.org/std/fs/fn.remove_dir_all.html) behavior

### PR DESCRIPTION
**Pull request by tommady**
close #3722

### CODE REVIEW

**Comment by sylvestre** [comment]
@tommady ping?

**Comment by tommady** [comment]
> @tommady ping?

hi, I asked a question on the issue but still got no answer.
https://github.com/uutils/coreutils/issues/3722#issuecomment-1788614472

please guide 🙇🏻 
thank you

**Comment by sylvestre** [comment]
@tommady sorry, i missed your question. are you still interested? thanks

**Comment by tommady** [comment]
No problem.
Ya I am still interested.

**Comment by sylvestre** [comment]
ok, great :)
have you made progress on this question ?
https://github.com/uutils/coreutils/issues/3722#issuecomment-1788614472

**Comment by tommady** [comment]
> ok, great :)
> 
> have you made progress on this question ?
> 
> https://github.com/uutils/coreutils/issues/3722#issuecomment-1788614472
> 
> 

It has been a while let me take a time to recall my memory ahah

**Pull request closed without merging**
