### PR TITLE
Use `u64` instead of `ino_t`/`dev_t` types

### LINKED ISSUE #3775: selinux: doesn't build on 32bits archs
after enabling selinux in Debian packaging, i noticed that it fails to build on some 32 bits archs:

```
   Compiling uu_chcon v0.0.14 (/<<PKGBUILDDIR>>/src/uu/chcon)
error[E0308]: mismatched types
   --> src/uu/chcon/src/chcon.rs:698:5
    |
695 |   fn get_root_dev_ino() -> Result<(libc::ino_t, libc::dev_t)> {
    |                            ---------------------------------- expected `std::result::Result<(u32, u64), errors::Error>` because of return type
...
698 | /     fs::symlink_metadata("/")
699 | |         .map(|md| (md.ino(), md.dev()))
700 | |         .map_err(|r| Error::from_io1("std::fs::symlink_metadata", "/", r))
    | |__________________________________________________________________________^ expected `u32`, found `u64`
    |
    = note: expected enum `std::result::Result<(u32, _), _>`
               found enum `std::result::Result<(u64, _), _>`

```
Full log:
https://buildd.debian.org/status/fetch.php?pkg=rust-coreutils&arch=armhf&ver=0.0.14-4%7Eexp1&stamp=1659648168&raw=0

@koutheir rings a bell ? :)

Similar issue:
https://github.com/rust-lang/libc/issues/2394

### PR DESCRIPTION
**Pull request by koutheir**
Closes #3775.

### CODE REVIEW

**Comment by koutheir** [comment]
@sylvestre, can you please check that this fixes #3775, particularly when building for 32-bit Android targets?

**Comment by anastygnome** [comment]
@koutheir needs a cargo fmt run ;)

**Comment by koutheir** [comment]
> @koutheir needs a cargo fmt run ;)

Oh sorry I forgot to do that! I'll do it as soon as I get a chance.

**Comment by koutheir** [comment]
@anastygnome, I don't think the failures are related to this patch.

**Comment by sylvestre** [comment]
https://buildd.debian.org/status/package.php?p=rust-coreutils&suite=experimental
works great, thanks!

**Pull request merged**
