### PR TITLE
factor(doc): Fix benchmarking documentation and other sundries

### PR DESCRIPTION
**Pull request by nbraud**
- Revert "docs/factor ~ fix markdownlint complaints"
- Revert "refactor/factor ~ polish spelling (comments, names, and exceptions)"

Since those commits included a bunch of other cosmetic changes, I'm really
not bothering to be more selective.

### CODE REVIEW

**Comment by nbraud** [comment]
*pokes @sylvestre.*

Sorry my first “being back” PR is a “grumpy” one, but I literally opened the benchmarking docs and they were broken.

**Comment by sylvestre** [comment]
@nbraud sorry but how are they broken?
if you look at the diff view, it has errors

**Comment by nbraud** [comment]
> @nbraud sorry but how are they broken?

See the commit message; Roy removed things like `  ` (double spaces) at ends of lines, because his Markdown linter was unhappy about it, when those has meaning (forced line-break) and removing them results in unreadable / meaningless text; here is a screenshot where I marked some missing line-breaks:

image


> if you look at the diff view, it has errors

Yes, apparently the spell checker is enforcing US spelling over anything else; I'd consider that a CI bug.
I did, however, run a search-and-replace to remove the scary Greek letter (technically, µ was “micro sign” in Unicode, which is a different codepoint from Greek μ, but whatever.)

**Comment by sylvestre** [comment]
> Yes, apparently the spell checker is enforcing US spelling over anything else; I'd consider that a CI bug.

Maybe? However, merging this will make a task fail.
What do you want to do?

**Comment by nbraud** [comment]
> > Yes, apparently the spell checker is enforcing US spelling over anything else; I'd consider that a CI bug.
> 
> Maybe? However, merging this will make a task fail. What do you want to do?

Overall?  I think CI should be fixed.

I don't think it's in scope for this PR, however, and I would be highly uncomfortable with it being a requirement, given how often you have told me to ignore CI being red or even actively pushed back on fixing it.

**Comment by rivy** [comment]
Using trailing double whitespace to force line breaks in Markdown is commonly seen as an anti-pattern. Instead, `<br>` is generally used to force line breaks within paragraphs.

Spelling has to have a targeted language and `US English` was picked as the most commonly used and well-understood target for the devs and the code base. A discussion could be had to expand with other languages, but just changing all words back to an alternate English version, and gratuitously breaking CI, without a discussion or reason seems to be an incorrect path.

And several of the changes make the source more opaque and will make it more difficult to understand for future readers.

Since the issue started with "markdown is broken" because of line breaks, I'd suggest dropping the reverts completely and making only a targeted change to the markdown by adding `<br>` or intervening blank lines where needed to increase readability.

**Review by rivy — CHANGES_REQUESTED** [review]
Remove the reverts and target the "broken" markdown with `<br>` or additional/interval blank lines to restore readability.

**Comment by sylvestre** [comment]
> how often you have told me to ignore CI being red

Because we had intermittent issues (which have been fixed), because new rules have been introduced in clippy, some components changed (freebsd for example)...

I told you to ignore because I had good reasons. not because the CI is useless.

Anyway, I think Rivy explained it better than I could. I also agree that en-US is the facto standard in FLOSS (I have 0 interest in changing it :)

**Comment by nbraud** [comment]
> (I have 0 interest in changing it :)

And I have 0 interest in making more “surgical” changes by hand simply because Rivy couldn't be bothered not to push kitchen-sink commits.

**Comment by rivy** [comment]
And, with that snarky comment, you've transitioned from self-described "grumpy" to fully insulting.

@nbraud , thanks for your contributions, but I see no reason to accept any more "help" from you.

**Comment by rivy** [comment]
@sylvestre , I should have fix for the markdown line break issue by the end of the weekend.

**Pull request closed without merging**
