### PR TITLE
Update the version to 0.0.20

### PR DESCRIPTION
**Pull request by sylvestre**

### CODE REVIEW

**Comment by tertsdiepraam** [comment]
What is your long-term plan for versioning? In other words, when do we move to 0.1, or 1.0? I suppose we go to 1.0 once we pass a large majority of the GNU tests? Do you want to go to 0.x before that?

For this release just bumping to 0.0.20 is fine of course. I'm just wondering because I don't think we ever discussed this.

**Comment by sylvestre** [comment]
> For this release just bumping to 0.0.20 is fine of course. I'm just wondering because I don't think we ever discussed this.

I was just thinking 1 when we are almost at GNU testsuite results :)
and do 0.0.X+1 but I don't have strong opinions on this

**Comment by tertsdiepraam** [comment]
Sounds good! I figured that was the idea, but it's good to have it confirmed. I think it's a good strategy.

**Comment by sylvestre** [comment]
@tertsdiepraam actually, i have a new proposition :)

We still keep the aim at 1.0.0 more or less equivalent to GNU

But until then, 0.Y.0 and Y being the number of GNU tools with full GNU successful coverage
WDYT? (there is the question of regression but we can probably leave with this)

**Comment by tertsdiepraam** [comment]
That's nice too! I was thinking something similar where 0.2.0 would mean passing around 20% GNU tests or something. And then we increment Z with every release where we don't cross that threshold.

**Comment by tertsdiepraam** [comment]
I've made an issue for this to make this discussion a bit more visible for contributors: https://github.com/uutils/coreutils/issues/5083

**Pull request merged**
