### PR TITLE
mktemp: change directory permission after creation

### LINKED ISSUE #3466: mktemp: should create directory with mode 700 but doesn't
According to `man mktemp`,

> Files are created u+rw, and directories  u+rwx,  minus  umask  restrictions.

uutil mktemp does not set the specified directory permissions correctly. (Although it does set the permissions correctly for temporary _files_.)

GNU mktemp:
```sh
$ mktemp -d /tmp/XXX
/tmp/uQf
$ ls -ld /tmp/uQf
drwx------ 2 jeffrey jeffrey 4096 May  1 20:42 /tmp/uQf
```

uutils mktemp:
```sh
$ ./target/release/mktemp -d /tmp/XXX
/tmp/jND
$ ls -ld /tmp/jND
drwxrwxr-x 2 jeffrey jeffrey 4096 May  1 20:42 /tmp/jND
```

### PR DESCRIPTION
**Pull request by 353fc443**
Closes #3466

### CODE REVIEW

**Comment by sylvestre** [comment]
please add a test :)
thanks

**Comment by 353fc443** [comment]
Writing one

**Comment by 353fc443** [comment]
I tries writing a test, unfortunately that does't work

**Comment by sylvestre** [comment]
could you please give more detail on "that does't work" ? :)

**Comment by jfinkels** [comment]
@353fc443 here is a test case you can add to the `tests/by-util/test_mktemp.rs` file. (There may be a similar test that can work for Windows as well.)
```rust
#[cfg(unix)]
use std::os::unix::fs::PermissionsExt;

#[cfg(unix)]
#[test]
fn test_directory_permissions() {
    let (at, mut ucmd) = at_and_ucmd!();
    let result = ucmd.args(&["-d", "XXX"]).succeeds();
    let dirname = result.no_stderr().stdout_str().trim_end();
    assert_matches_template!("XXX", dirname);
    let metadata = at.metadata(dirname);
    assert!(metadata.is_dir());
    assert_eq!(metadata.permissions().mode(), 0o700);
}
```

**Comment by 353fc443** [comment]
@jfinkels Thanks I'll add the test and push it again!

**Comment by 353fc443** [comment]
@jfinkels  The test doesn't seem to work

```shell
failures:

---- test_mktemp::test_directory_permissions stdout ----
current_directory_resolved:
run: /Users/user/coreutils/target/debug/coreutils mktemp -d XXX
thread 'test_mktemp::test_directory_permissions' panicked at 'assertion failed: `(left == right)`
  left: `16832`,
 right: `448`', /Users/user/coreutils/tests/by-util/test_mktemp.rs:498:5
```

Tested on Macos

**Comment by jfinkels** [comment]
Yes, looks like you were able to fix up the test that way. Great, thanks.

**Comment by jfinkels** [comment]
Yes, looks like you were able to fix up the test that way. Great, thanks.

**Review by jfinkels — APPROVED** [review]

**Comment by 353fc443** [comment]
@sylvestre any suggestions?

**Comment by sylvestre** [comment]
nope, this is great, thanks for the ping :)

**Pull request merged**
