### PR TITLE
factor: Fix test build failure introduced in #1573

### PR DESCRIPTION
**Pull request by nbraud**

### CODE REVIEW

**Comment by nbraud** [comment]
Looks like CI is not correctly running each crate's tests, given that #1573 was green there...

**Comment by rivy** [comment]
CI runs the "global" coreutils tests but doesn't currently check tests for each individual utility crate.

I think that is something that should be done, but most utilities haven't had any individual tests to perform until recently and so this hadn't come up. We should put this on the near-future agenda.

**Comment by sylvestre** [comment]
the freebsd issue is network related. I will just ignore it
```
warning: spurious network error (2 tries remaining): failed to get 200 response from `https://crates.io/api/v1/crates/users/0.10.0/download`, got 504
```

**Comment by nbraud** [comment]
Thanks @sylvestre

**Comment by rivy** [comment]
> CI runs the "global" coreutils tests but doesn't currently check tests for each individual utility crate.

Fixed by #1583.

**Pull request merged**
