### PR TITLE
Silently accepts ---presume-input-tty

### LINKED ISSUE #2345: Implement `rm  ---presume-input-tty`
` --presume-input-tty` is an undocumented option of `rm`.

https://bug-coreutils.gnu.narkive.com/AMUZEL4V/rm-p
     
 ```
             It is relatively difficult to ensure that there is a tty on stdin.
            Since rm acts differently depending on that, without this option,
            it'd be harder to test the parts of rm that depend on that setting. 
```

GNU testsuite:
`2021-06-04T19:17:12.4465259Z +error: Found argument '--presume-input-tty' which wasn't expected, or isn't valid in this context`

It should not be visible in rm in clap

### PR DESCRIPTION
**Pull request by hbina**
For whatever reason, the following is equivalent,

```bash
cargo run -- rm --presume-input-tty
cargo run -- rm ---presume-input-tty
cargo run -- rm -----presume-input-tty
cargo run -- rm ---------presume-input-tty
```

It seems that this is basically a noop in GNU as well. I haven't taken the time to go through the source code to know what it actually does.
And I can't even google anything on this (What secrets does it try to hide!?)

```bash
hbina@DESKTOP-2D0I5MJ:~/git/uutils$ touch test
hbina@DESKTOP-2D0I5MJ:~/git/uutils$ echo "test" | rm ---presume-input-tty
rm: missing operand
Try 'rm --help' for more information.
hbina@DESKTOP-2D0I5MJ:~/git/uutils$ echo "test" | rm ---presume-input-tty test
```

Closes #2345 (Will you look at that number)

Signed-off-by: Hanif Bin Ariffin <hanif.ariffin.4326@gmail.com>

### CODE REVIEW

**Comment by miDeb** [comment]
This is to override `stdin_tty` in gnu's rm for testing, even if stdin is not really a tty. It seems like `rm` changes its behavior based on that, however only in one particular case: https://github.com/coreutils/coreutils/blob/00ea4bacf6063ccc125209d5186f8f2382c6f0d4/src/remove.c#L211. I can't really understand what's it doing, and until we replicate gnu's behavior (our rm does not currently look at whether stdin is a tty at all) I think it's fine to make this a no-op.

**Comment by sylvestre** [comment]
Could you please add a test to verify that the option isn't going to be rejected?
And maybe add a comment explaining what should/might be done if we want to implement it one day?
thanks

**Comment by sylvestre** [comment]
Running GNU testsuite:
```PASS +2 / FAIL -2 / ERROR +0 / SKIP +0 
```
Well done!

**Comment by tertsdiepraam** [comment]
Quick question since I'm running into this with the transition to clap 3 (https://github.com/uutils/coreutils/pull/2863). In this PR, tests were added for `--presume-input-tty` and `----presume-input-tty` (2 and 4 hyphens), but when I test GNU `rm` on my machine, both give an `unrecognized option` error. Should we still support these?

**Comment by tertsdiepraam** [comment]
Thanks! Clap indeed removed the arbitrary number of hyphens, so I'll move to only supporting 3 hyphens with clap 3 (although because of how long arguments work in clap I'll have to support both 2 and 3 hyphens)

**Pull request merged**
