### PR TITLE
expand: flush output buffer

### PR DESCRIPTION
**Pull request by muskuloes**
Hi,
I noticed that when I used expand on stdin, the output wasn't immediately printed on the screen after I pressed the enter key. The output was printed only after <ctrl-d> (EOF) was pressed.

### CODE REVIEW

**Comment by sylvestre** [comment]
@muskuloes Would you have some step to reproduce this issue? thanks

**Comment by muskuloes** [comment]
Hi @sylvestre. If I remember correctly, when I run `expand` without spacing a file it should read from `stdin` and print back the result after the enter key is pressed directly. But right now running `cargo run expand` only prints back to `stdout` once I press `ctrl-d`. So the aim of the PR was to flush the output buffer to print to `stdout` when the enter key is pressed.

**Comment by rivy** [comment]
I can confirm the stated behavior (both on an ubuntu server [<ENTER> => output] and uutils [no response until <EOF>]). Likely, `unexpand` would need the same treatment.

**Comment by muskuloes** [comment]
It indeed happened with the `unexpand` command too. I updated the PR.

**Comment by sylvestre** [comment]
I guess it is hard but would it be possible to have a test for this?
thanks

**Comment by muskuloes** [comment]
I wouldn't know how to do that. Any suggestions?

**Comment by sylvestre** [comment]
@muskuloes sorry for the latency. Do you think you could fix the clippy warning ?

```

error: the function has a cognitive complexity of (27/25)
##[error]   --> src/uu/unexpand/src/unexpand.rs:212:4
    |
212 | fn unexpand(options: Options) {
    |    ^^^^^^^^
    |
    = note: `-D clippy::cognitive-complexity` implied by `-D warnings`
    = help: you could split it up into multiple smaller functions
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#cognitive_complexity
```

**Comment by muskuloes** [comment]
Yeah, I can do that.

**Comment by sylvestre** [comment]
Let's close it then :)

**Pull request closed without merging**
