### PR TITLE
Update Windows support.

### PR DESCRIPTION
**Pull request by jbcrail**
This is a collection of Windows-related updates for the build system and imports.

### CODE REVIEW

**Comment by Heather** [comment]
@jbcrail thanks but why mv?

**Comment by jbcrail** [comment]
The primary motivation is to support Windows without requiring make (and the requisite MinGW or Cygwin environments, which aren't easy to install). Cargo has advanced enough to replace make for Rust projects.

The secondary motivation is reducing duplication. Both Cargo.toml and Makefile need to be updated to add new utilities. If we reduce this to Cargo.toml, it would bring coreutils in line with other Cargo-based projects.

The goal is to run `cargo build && cargo test && cargo install` on both Windows and Unix without needing anything else.

**Comment by Heather** [comment]
@jbcrail I mean why `mv` is in unix group?

**Comment by jbcrail** [comment]
Oops. `mv` currently relies on the Unix APIs according to 47f82f0d.

**Comment by Heather** [comment]
I see... not sure if we should create issues like TODO list nodes for porting stuff to be really crossplatform

**Comment by jbcrail** [comment]
I think that's a good idea.

**Pull request merged**
