### PR TITLE
ptx: rewrite logic to support UTF8 input

### PR DESCRIPTION
**Pull request by granquet**
The current logic uses offset addressing into the string converted as a byte slice. This is problematic when the input is UTF8 encoded as the offset in the byte slice doesn't necessarily correspond to a valid character boundary in a utf8

Recode the logic to use String instead of a byte slice.

Creating the PR as a draft, as this needs more cleanup... and before I do the cleanups and try to optimize it, I'd rather gather some inputs.

The code "works" on the input provided (if you omit the utf8 addition, I need to regenerate the expected output) and I've compared it with various random files to the gnu coreutil version...
I've never used ptx before and I'm still unsure how it works and what it does...
The code complexity is rather bad and the performance suffers... but at least it should be correct when the input is utf8 and not panic as in issue [2049](https://github.com/uutils/coreutils/issues/2049)

### CODE REVIEW

**Comment by tertsdiepraam** [comment]
I haven't looked at the code, but please also do some testing with GNU to see how they deal with this. If GNU accepts slicing in code point boundaries then probably so should we. And since GNU is written in C, it's quite likely they allow that :)

**Comment by tertsdiepraam** [comment]
Looking at the original issue, this indeed seems like a good idea. However, do test with invalid utf-8 as well. It might be best to use `bstr` here instead of `String`. Looking forward to the patch :)

**Comment by granquet** [comment]
> I haven't looked at the code, but please also do some testing with GNU to see how they deal with this. If GNU accepts slicing in code point boundaries then probably so should we. And since GNU is written in C, it's quite likely they allow that :)

Thx for the tip, I'll try to understand better how the original ptx works and get back to the drawing board :)

**Comment by granquet** [comment]
> I haven't looked at the code, but please also do some testing with GNU to see how they deal with this. If GNU accepts slicing in code point boundaries then probably so should we. And since GNU is written in C, it's quite likely they allow that :)

Had some time to look into this.
So GNU ptx slices in the middle of codepoints with the GNU extensions.
It doesn't seem to allow that in `--traditional` (`-G`) as it will latch to a "word" boundary instead.

The main problem I'm trying to solve is that regex in rust will return a code point index in a String.
The current code takes that index and uses it to index a byte representation of that string, which in case of utf8 doesn't work (and can leads to out of bound access).

**Comment by sylvestre** [comment]
stalled PR, closing.
please reopen when ready!

**Pull request closed without merging**
