### PR TITLE
Fix `make busytest`

### PR DESCRIPTION
**Pull request by ttrunck**
The binary was rename from uutils to coreutils in that commit
52ae491fcdd2cd9bd56fb56fae8270c399654dcd
but the makefile to run the busybox test wasn't updated

This commit update the makefile to use the correct binary name.
It also updates the busybox to the 1.32.1 version and fix the makefile
to run all the busybox tests instead of stopping after the first failed exe

This also change the main binary usage to match busybox. This allow to run the new busybox tests.
New busybox tests use an exact match on the usage string to find the list of defined functions. So without that change we had a `SKIPPED: cp (not built)` issue

### CODE REVIEW

**Comment by sylvestre** [comment]
Would it be possible to add a test for this? (checking that busytest works)
thanks

**Comment by ttrunck** [comment]
I could add a GitHub action like the GNU workflow. Do you think that would work for that project?
I can have a separate workflow for busybox or I can add that into the GNU one. Do you have a preference?
It could also be great to have a `make gnutest` command, what to you think? I can also add that (and mention it in the readme)

I should be able to work on all that this weekend

**Comment by sylvestre** [comment]
yeah, a new github action would be perfect!

(and yeah, make gnutest would be great too :)
thanks

**Comment by ttrunck** [comment]
Perfect, I will do that!

**Comment by sylvestre** [comment]
It should go in 
https://github.com/uutils/coreutils/blob/master/.github/workflows/CICD.yml

**Comment by ttrunck** [comment]
I added a job to run the busytest in CICD. Those only run on the latest ubuntu and because some are failing I'm set the job to pass even if there are some test failure, but those failures create warnings on the summary. (It's the same thing as what is in place for cargo fmt/cargo clippy checks).

You can see what's happening with the build triggered by that PR. (On the side note you may want to check your CI policy. I'm able to run arbitrary code on your CI agents just by creating a PR in your repo which could easily be a problem)

**Comment by sylvestre** [comment]
> I added a job to run the busytest in CICD. Those only run on the latest ubuntu and because some are failing I'm set the job to pass even if there are some test failure, but those failures create warnings on the summary. (It's the same thing as what is in place for cargo fmt/cargo clippy checks).
Excellent and good enough :)


> You can see what's happening with the build triggered by that PR. (On the side note you may want to check your CI policy. I'm able to run arbitrary code on your CI agents just by creating a PR in your repo which could easily be a problem)

Sure but this isn't specific to coreutils, it is general with github action.

**Pull request merged**
