### PR TITLE
csplit: added core logic for splitting a file on patterns

### LINKED ISSUE #501: Implement csplit
I'll be working on this.

### PR DESCRIPTION
**Pull request by scampi**
Close #501 

Tested on linux. The core logic of splitting a file seems to be ok.

Remaining tasks:
- [x] implement all options
- [x] handle some invalid states, especially when using an option
- [x] add some more tests

### CODE REVIEW

**Comment by Arcterus** [comment]
Should I review the code now or are you planning to finish the remaining tasks soon (in which case I will wait until you have finished most likely)?

**Comment by scampi** [comment]
@Arcterus I will first fix what I have based on your comment on the related issue.

**Comment by Arcterus** [comment]
Alright, let me know when you finish. :)

**Comment by scampi** [comment]
@Arcterus It is now ready to review. There are few edge cases which do not follow the gnu's behaviour (marked as such at the bottom of the test file).

**Comment by scampi** [comment]
@Arcterus bump

**Comment by sylvestre** [comment]
@scampi Hello
I am well aware that this PR is 2 years old. I am a new maintainer on this project and would like to know if you are still interested to land this?

Sorry about that :(

**Comment by sylvestre** [comment]
Sorry for the latency. I took over the maintenance.
I moved this PR here:
https://github.com/uutils/coreutils/pull/1672

**Pull request closed without merging**
