### PR TITLE
Added another way of installation

### PR DESCRIPTION
**Pull request by mehandes**
Added simpler way of installation (using Nix) in order to encourage more people to use it (by omitting configuration and build steps)

### CODE REVIEW

**Comment by Arcterus** [comment]
I'm not really familiar with Nix, so can you explain what this does?

**Comment by mehandes** [comment]
@Arcterus  It is a [package manager](https://nixos.org/nix/). I just use Nix, cause it's convenient way to easily add some relatively new packages on eg. Debian. Btw. it works (with most packages) on OSX too!

**Comment by Arcterus** [comment]
Does the command download and then build, just build, or something else entirely?  If it downloads, does it download uutils or GNU coreutils (I'd assume the latter given that it's the original "coreutils")?

**Comment by mehandes** [comment]
@ it builds only if a pre-built binary is not yet available. It's completely from-source for all dependencies, but it can replace builds with cached binaries from a trusted source.

**Comment by Ma27** [comment]
@mehandes it builds the actual GNU coreutils, not the uutils/coreutils (`nixpkgs.coreutils` points to the GNU coreutils). However I added this coreutils rewrite to `Nix` so you could run `nix-env -iA nixpkgs.uutils-coreutils` :-)

**Comment by Arcterus** [comment]
I had a feeling that's what this would do.  Can one of you either submit a new pull request or change this one to suggest that command as an alternate installation method?

**Comment by Ma27** [comment]
@Arcterus done. See #1142

**Comment by Arcterus** [comment]
Thanks!  Also, I noticed in the pull request adding uutils to Nix that the installation fails on macOS (looks like it is because of `stdbuf`)?  If you ever notice something like that feel free to create an issue. :)

**Comment by Ma27** [comment]
@Arcterus thanks! The thing is, I don't own a mac, I'll ask one of my coworkers with a mac to investigate, then we'll see whether we can fix this on our side :)

**Comment by Arcterus** [comment]
Sounds good!  Let me know how it goes :)

**Pull request closed without merging**
