### PR TITLE
sort/ls: implement version cmp matching GNU spec

### PR DESCRIPTION
**Pull request by miDeb**
This reimplements version_cmp, which is used in sort and ls to sort
according to versions.
However, it is not bug-for-bug identical with GNU's implementation.
I reported a bug with GNU here:
https://lists.gnu.org/archive/html/bug-coreutils/2021-06/msg00045.html
This implementation does not contain the bugs regarding the handling of
file extensions and null bytes.

### CODE REVIEW

**Comment by tertsdiepraam** [comment]
Could you explain what the difference is with the current `ls` implementation? I thought I was pretty close to getting it correct there. I think I missed the handling of `~` and the file extensions? Pretty cool that you were able to do this without any allocations too!

**Comment by miDeb** [comment]
I also think the current implementation is pretty close, but I wasn't aware of all the differences at the beginning so I rewrote it in a way that is close to what [GNU documents](https://www.gnu.org/software/coreutils/manual/html_node/Version-sort-ordering.html). Now that I think about it, it would probably have been possible to add the special cases to the old implementation.
Differences are (afaik):
- In the lexical comparison:
  - Handling of `~`
  - Letters are in front of non-letters
- Handling of file extensions
- Handling of "", "." and ".."
- Handling of files with a leading "."
- There's also this interesting one: the current implementation falls back (when it can't find a difference) to comparing the amount of leading zeros. This implementation (and GNU's) falls back to the result of a normal string comparison of the whole string, but I think that might actually be the same thing at the end?

> should we be moving to bstr for this to avoid lossy conversions

Not sure, it will not avoid lossy conversions on windows. (btw, sort will panic if you input is not utf8, maybe also something i have to change)

**Comment by tertsdiepraam** [comment]
> Now that I think about it, it would probably have been possible to add the special cases to the old implementation.

I like your implementation better, so no problem there!

> There's also this interesting one: the current implementation falls back (when it can't find a difference) to comparing the amount of leading zeros. This implementation (and GNU's) falls back to the result of a normal string comparison of the whole string, but I think that might actually be the same thing at the end?

Interesting, I think you're right. All the tests pass so I think it works :)

**Comment by miDeb** [comment]
> All the tests pass so I think it works :)

I forgot to mention that I used a fuzzer to check if there are differences between GNU's implementation and this one, and the only things it found were the bugs in GNU I reported :)

**Comment by tertsdiepraam** [comment]
I was proud of my initial implementation, but it seems so convoluted now in comparison to this one :) Great work!

**Pull request merged**
