### PR TITLE
sort: use unstable sort when possible

### PR DESCRIPTION
**Pull request by miDeb**
This results in a very minor performance (speed) improvement.
It does however result in a memory usage reduction, because unstable
sort does not allocate auxiliary memory. There's also an improvement in
overall CPU usage.

### CODE REVIEW

**Comment by miDeb** [comment]
To show some numbers:
Hyperfine: very slight speed improvement, almost in the error range:
> 'target/release/coreutils sort shuffled_numbers.txt -o output.txt' ran
    **1.09 ± 0.07 times faster** than './oldutils sort shuffled_numbers.txt -o output.txt'

`/bin/time -v` shows more interesting differences:
|Before|After|
|---|---|
| User time (seconds): 0.10|User time (seconds): 0.06
Percent of CPU this job got: 396%|Percent of CPU this job got: 261%
Maximum resident set size (kbytes): 24588|Maximum resident set size (kbytes): 17180

**Comment by sylvestre** [comment]
could you please update the BENCHMARK.MD file with this? thanks

**Comment by electricboogie** [comment]
I think you can add random_shuffle to those "compares" you can use unstable with.

**Comment by miDeb** [comment]
@electricboogie I am only using stable sort for `--stable` and `--unique`, so random shuffling already uses unstable sorting.

@sylvestre done!

**Pull request merged**
