### PR TITLE
chmod + chroot new io

### PR DESCRIPTION
**Pull request by ctjhoa**
I've got an issue with src/common/c_types.rs.
As `os::errno` is no longer in the std lib, the project may needs to rely on something like https://github.com/carllerche/nix-rust

Otherwise I've no idea where I can get a equivalent.

(Disclaimer I'm not a C programmer)

### CODE REVIEW

**Comment by Arcterus** [comment]
I think you can substitute `Error::last_os_error().raw_os_error().unwrap()` for `os::errno()`.

**Comment by kwantam** [comment]
Note also: chmod does not actually work as checked in, it panics on an unwrap()

My new_io branch has working chmod. chroot builds and only kinda sorta works. I'll rebase onto master and open a PR.

**Comment by Heather** [comment]
@kwantam thank you, sorry for merging it.

**Comment by kwantam** [comment]
no worries, just a couple more minutes and I'll have something quasi-working :)

My fault for not coordinating with @ctjhoa :)

**Comment by ctjhoa** [comment]
@kwantam Yeah coordination is difficult with this kind of refactoring. Sorry for the chmod bug I'll try to do some test next time.

**Pull request merged**
