### PR TITLE
comm: remaining tests for feature completion

### PR DESCRIPTION
**Pull request by nathanross**
This PR includes

* revisions of existing comm tests for l20n, status code, and stderr correctness
* addition of all remaining tests required to be able to measure/demonstrate feature completion. (save temporarily undecidable tests due to #818)

### CODE REVIEW

**Comment by ebfe** [comment]
Not sure if its worth adding `locale` stuff to the tests right now. It's not like anything is looking at it or am I missing something?

**Comment by nathanross** [comment]
```man comm``` specifies that comm respects ```LC_COLLATE``` in regard to determining whether a line is later in sort order from the previous line or not. ```respect_lc_collate``` (a test added in the second commit) is an example of this, where when ```LC_COLLATE=C``` we expect that uppercase alphabetical characters are considered as before lowercase in sort order, and so a file with a row that line that starts with uppercase that follows a line that starts with lowercase should throw an error when ```--check-order``` is enabled.

```LC_COLLATE``` is overridden by ```LC_ALL```, a commonly set locale variable. I defaulted to explicitly providing the locale of ```en_US.UTF-8``` out of (possibly reflecting my unworldliness / limited experience in these matters) concern for the possibility that someone may run these tests in a locale that uses ascii characters but considers them as having a different sort order than the sort order that was considered when writing the tests.

**Comment by ebfe** [comment]
Nothing in uutils or the rust std lib looks at these variables, so it has no effect right now. If we ever add support for locales that's most likely through an external crate, but i don't expect that to happen anytime soon. So until we know how we want to support locales (or at all), i think it makes little sense to add locale specific tests to the utils.

**Comment by ebfe** [comment]
cc @Heather @Arcterus for opinions

**Comment by Heather** [comment]
@ebfe well locale is important sure but I'm also agreed that it should be added globally, that's all I can say

**Comment by nathanross** [comment]
@ebfe @heather references to locale rm'd.

**Pull request merged**
