### PR TITLE
docs: add examples from tldr-pages

### PR DESCRIPTION
**Pull request by tertsdiepraam**
Add examples to the documentation, provided by [tldr.sh](https://tldr.sh). Every run, the tldr archive is downloaded and unzipped into the `docs/tldr` folder (which is in `.gitignore`) and then both the `common` and `linux` folders are checked to see if they contain examples for a given util. In the future, we might not want to download the archive every time, for example only when an `--update-examples` flag is passed to `uudoc`, but that doesn't seem super important right now.

If a markdown file is found, some light "parsing" is done to make it fit better with the rest of the page, meaning that:
- The lines that aren't examples are removed.
- The text is not in a list
- Code uses 3 backticks instead of 1.

As far as I can tell, the examples are licensed under CC BY 4.0, which requires attribution, so I have added a block with a link to the project and the license.

~For the downloading and unzipping, I've used CLI commands instead of Rust libraries, because new dependencies would have to go into the global `Cargo.toml` given the current project structure and that didn't seem ideal. Currently, this requires that `curl` and `unzip` are installed.~ Changed my mind, see below.

Note: It could be that the util does not match the examples for some reason or that they document a flag that we don't have yet.

image

### CODE REVIEW

**Comment by tertsdiepraam** [comment]
I changed my mind, it's a bit more convenient to not rely on external programs, so I used `ureq` and `zip` to download the zip and extract the files directly, without having to save anything to files.

**Comment by sylvestre** [comment]
excellent stuff :)

**Comment by sylvestre** [comment]
it is amazing:
https://uutils.github.io/coreutils-docs/user/utils/du.html

Just a small nit:
https://github.com/uutils/coreutils/pull/3160

**Comment by sylvestre** [comment]
btw, did you notice pages without examples from tldr?

**Comment by tertsdiepraam** [comment]
> Just a small nit:

Yeah, I was conflicted about what the right placement was. After the options might be better indeed.

> btw, did you notice pages without examples from tldr?

`basenc`, `hashsum`, `relpath`, `sha3-224sum`, `sha3-256sum`, `sha3-384sum` & `sha3-512sum`.

**Pull request merged**
