### PR TITLE
use trim_(start/end) insted of deprecated trim_(left/right)

### PR DESCRIPTION
**Pull request by meltinglava**

### CODE REVIEW

**Comment by meltinglava** [comment]
Tests fail on 1.27 since trim_start was in stable in 1.30. Do not know why the nightly failed. Nightly failed for some build error. No idea what. Looks like AppVeyor could not merge from forks other than master. Might be a config problem.

**Comment by rivy** [comment]
`trim_start()` wasn't added until v1.30.0; `trim_left()` is deprecated v1.33.0.

So, if this, or something similar is used, the minimum rust version would have to be pushed up to v1.30.

In my local 'dev' fork, to suppress spurious compilation warnings, I marked all the locations with `#[allow(deprecated)]` and a MAINT comment (see 9cc9cf73). I'm not sure if there's a better solution, so I didn't push it up as a PR. But, I think it's either that, or push the minimum version to v1.30.

**Comment by meltinglava** [comment]
Indeed it is needed to bump minimum to 1.30. think this should be merged when/if another PR / commit forces the bump to >=1.30.

**Comment by Arcterus** [comment]
Can you rebase?  I am find with updating the minimum version required.  Probably we'd go to Rust 1.31 so we can use 2018 edition features.

**Comment by meltinglava** [comment]
hope i did this right.

**Comment by meltinglava** [comment]
So i do not know why appveyor failed. Sry for takeing so long to respont

**Comment by Arcterus** [comment]
It looks like Appveyor just messed up again...  It's not your fault.  Also don't worry about it, I took a long time to respond before as well.

**Comment by Arcterus** [comment]
It looks like you merged instead of rebasing.  If you don't know how to rebase, I think [this page](https://git-scm.com/book/en/v2/Git-Branching-Rebasing) should help.  If you're still unsure, let me know and I'll try to walk you through it.

**Comment by meltinglava** [comment]
think i the rebase is right now. Please tell if it is not. Exams got in the way for doing it earlyer

**Comment by rivy** [comment]
Thanks for the contribution!
The fix for this same issue was already included in a large lint and CICD fixup PR (#1449).
We'd be happy to see you back with new contributions in the future.

**Pull request closed without merging**
