### PR TITLE
Clap 4

### PR DESCRIPTION
**Pull request by tertsdiepraam**
I'm working on porting everything to clap 4. I figured I should put up a draft PR, because I can't finish it all at once. Most of it is just annoying but easy work, but there were a few harder cases. Let's hope the tests cover enough to ensure the behaviour stays the same :)

~I'm about halfway through this now (doing it alphabetically, now at `mkdir`).~ I've done all of them :) Now just waiting for the bump to 1.60.

Note: this will require a bump to MSRV 1.60.

Blocked by: https://github.com/uutils/coreutils/pull/3994

### CODE REVIEW

**Comment by andrewbaptist** [comment]
One consideration. I believe that you can make the changes OTHER than the change to the Cargo.toml to change the version of clap from 3.2 to 4.0. If you do that, then you should be able to merge these individual commits in first and then just change all the versions at once. 

I haven't verified this, but might be worth trying.

**Comment by tertsdiepraam** [comment]
> I believe that you can make the changes OTHER than the change to the Cargo.toml to change the version of clap from 3.2 to 4.0

Most of them, yes, but sadly not all of them. `Arg::num_args` is not defined in 3.2 for example.

**Comment by tertsdiepraam** [comment]
`uudoc` is broken. Reverting to draft until that's fixed

**Comment by sylvestre** [comment]
merging now to make sure it doesn't bit rot

**Pull request merged**
