### PR TITLE
update wc to rust 2018 and use structopt

### PR DESCRIPTION
**Pull request by vadixidav**
I was able to update `wc` to Rust 2018 and `structopt`, but I was unable to get unit tests to work. I just want to put this out there so a maintainer might be able to describe to me how I should handle testing when introducing something like structopt. I still use the appropriate `uucore::args` where necessary. Running it at the command line seems to work for me fine. Feel free to commit directly to my repo if you wish.

I intend to potentially modernize the implementation as well, but only after switching to structopt works. I will leave this here for a bit while I do some other open source work in the meantime.

### CODE REVIEW

**Comment by vadixidav** [comment]
Okay, I figured out that I just wasn't ever reading stdin even when I got a `-`. Whoops! Now that is fixed and I commented the code more so it is more readable. Hopefully I left it better than where it started.

**Comment by vadixidav** [comment]
One concern may be more lines in the help dialog. Let me know if something specific should be added. Feel free to just modify my repo before merging if that's faster.

**Comment by vadixidav** [comment]
Do we need to support Rust 2015? The CI seems to be using an older Rust version that doesn't support Rust 2018.

**Comment by Arcterus** [comment]
At the moment we use Rust 2015.  We'll probably switch to Rust 2018 soon though.  Would you mind rebasing your code?  I'll review it sometime in the next week or so.

**Comment by Arcterus** [comment]
So I'm pretty much fine with this code, but I am planning to merge #1383 first.  Would you mind rebasing after I merge that PR?

**Comment by vadixidav** [comment]
@Arcterus Yeah, my bad for not rebasing before. I'll adapt the argument handling to whatever is being done now.

**Comment by vadixidav** [comment]
Just checked and it seems the PR is still in flight. I will start watching the PR so I know when it's done.

**Comment by sylvestre** [comment]
no activity for a while, closing.
Feel free to reopen with an updated patch

**Pull request closed without merging**
