### PR TITLE
ls: set default quoting style to literal when not TTY

### LINKED ISSUE #5490: ls: Tab produces `\t` instead of `TAB` and the output is not sorted correctly.
Steps to reproduce:

```
touch "a........a"
touch "a....	a"
touch "a		.....a"
touch "aaaaaaaaaaa"
touch "aaaaaaaaaaaa	a"
touch "aaaaaaaaaaaaaaaaa"
touch "a	·····b"
touch "a├─┤·····b"
touch "test....test"
touch "test			test"

ls -Cw18 | batcat -A

./coreutils ls -Cw18 | batcat -A
```

Sample output:

```
nemesis@nemesis:~/Documents/Github/test/bin_3$ ls -Cw18 | batcat -A
───────┬────────────────────────────────────────────────────────────────────────────────
       │ STDIN
───────┼────────────────────────────────────────────────────────────────────────────────
   1   │ a├──┤├──┤.....a␊
   2   │ a....├──┤a␊
   3   │ a........a␊
   4   │ aaaaaaaaaaa␊
   5   │ aaaaaaaaaaaa├──┤a␊
   6   │ aaaaaaaaaaaaaaaaa␊
   7   │ a├──┤\u{b7}\u{b7}\u{b7}\u{b7}\u{b7}b␊
   8   │ a\u{251c}\u{2500}\u{2524}\u{b7}\u{b7}\u{b7}\u{b7}\u{b7}b␊
   9   │ coreutils␊
  10   │ test├──┤├──┤├──┤test␊
  11   │ test....test␊
───────┴────────────────────────────────────────────────────────────────────────────────
nemesis@nemesis:~/Documents/Github/test/bin_3$ ./coreutils ls -Cw18 | batcat -A
───────┬────────────────────────────────────────────────────────────────────────────────
       │ STDIN
───────┼────────────────────────────────────────────────────────────────────────────────
   1   │ 'a'$'\t\t''.....a'␊
   2   │ 'a'$'\t''\u{b7}\u{b7}\u{b7}\u{b7}\u{b7}b'␊
   3   │ 'a....'$'\t''a'␊
   4   │ a........a␊
   5   │ aaaaaaaaaaa␊
   6   │ 'aaaaaaaaaaaa'$'\t''a'␊
   7   │ aaaaaaaaaaaaaaaaa␊
   8   │ a\u{251c}\u{2500}\u{2524}\u{b7}\u{b7}\u{b7}\u{b7}\u{b7}b␊
   9   │ coreutils␊
  10   │ 'test'$'\t\t\t''test'␊
  11   │ test....test␊
───────┴────────────────────────────────────────────────────────────────────────────────
```

### PR DESCRIPTION
**Pull request by RenjiSann**
This PR fixes the quoting behavior of `ls` when stdout is non-TTY. 
Until now, Coreutils' `ls` used the same default quoting style no matter what. However, GNU `ls` uses shell escaped quoting when stdout is a TTY, and Literal quoting otherwise.

I had to modify some quoting tests which expected the TTY-flavored output.

In the future, we should test that the output is still correct when running in the terminal by emulating an stdout file descriptor that can fake the `is_terminal()` behavior.

Fixes #5490

### CODE REVIEW

**Comment by RenjiSann** [comment]
I have no Windows machine on which I can test the actual output of `ls` in a non-TTY, so I don't know if I should fix the tests or add another condition for the default quoting style depending on the host OS.

Can someone verify the GNU ls behavior on Windows ?

**Comment by allaboutevemirolive** [comment]
> I have no Windows machine on which I can test the actual output of `ls` in a non-TTY, so I don't know if I should fix the tests or add another condition for the default quoting style depending on the host OS.
> 
> Can someone verify the GNU ls behavior on Windows ?

After finishing my work today, I'll test this

**Comment by RenjiSann** [comment]
@allaboutevemirolive Any update ? :grin:

**Review by tertsdiepraam — COMMENTED** [review]
Nice! I think this is good enough to be merged, apart from the tests. I think we can assume that Windows will work the same way, so if you can adapt the tests on Windows accordingly (see the CI output) then it should be fine!

**Comment by RenjiSann** [comment]
I've updated the windows tests !

> If you want a next challenge (for another PR). Here's what the GNU docs say:
> > You can specify the default value of the --quoting-style option with the environment variable QUOTING_STYLE. If that environment variable is not set, the default value is ‘shell-escape’ when the output is a terminal, and ‘literal’ otherwise.

May I have the link to this ?

**Comment by cakebaker** [comment]
@RenjiSann https://www.gnu.org/software/coreutils/manual/html_node/Formatting-the-file-names.html

**Comment by cakebaker** [comment]
Thanks for your PR :)

**Pull request merged**
