### PR TITLE
Update to clap 4.5.22 to fix a unsound alert on anstream

### PR DESCRIPTION
**Pull request by sylvestre**
https://rustsec.org/advisories/RUSTSEC-2024-0404

$ cargo update -p clap

### CODE REVIEW

**Comment by cakebaker** [comment]
I don't know if you have seen it, but some `seq` tests fail.

**Comment by cakebaker** [comment]
The problem is that there is a breaking change in clap that affects `seq`: see https://github.com/clap-rs/clap/discussions/5837#discussioncomment-11464260

**Comment by sylvestre** [comment]
I didn't see it
I guess the gnu regressions are the same

**Comment by cakebaker** [comment]
Closing PR, fixed in https://github.com/uutils/coreutils/pull/6955

**Pull request closed without merging**
