### PR TITLE
pr: use clap to handle help & version

### PR DESCRIPTION
**Pull request by cakebaker**
This PR let's clap handle help and version, and removes the deprecated `AppSettings::NoAutoHelp` and `AppSettings::NoAutoVersion`.

### CODE REVIEW

**Comment by tertsdiepraam** [comment]
This is *technically* incompatible with GNU `pr`, because that does not accept `-h` and `-v`, but only the long options. I don't really mind that much in this case, though. If we want 100% compat, then we need [`disable_help_flag`](https://docs.rs/clap/3.2.20/clap/builder/struct.App.html#method.disable_help_flag) and [`ArgAction::Help`](https://docs.rs/clap/3.2.20/clap/enum.ArgAction.html#variant.Help) on the custom flag (and the same for version).

**Comment by cakebaker** [comment]
Hm, at least on my machine clap doesn't use `-h` for help because `-h` is already defined for something else (the `CICD / Binary sizes` check, however, fails because of that).

**Review by tertsdiepraam — CHANGES_REQUESTED** [review]
Completion generation is failing

**Review by tertsdiepraam — APPROVED** [review]

**Comment by tertsdiepraam** [comment]
Works as a charm now! Thanks for proving me wrong :)

**Pull request merged**
