### PR TITLE
stdbuf: make build more reliable and allow installation using Cargo

### LINKED ISSUE #1104: Consider slimming down the make stuff
Why does this project require `make` to build?

### PR DESCRIPTION
**Pull request by Arcterus**
Now instead of trying to finagle Cargo into giving us a shared library that we then have to find and inject into anything called by `stdbuf`, we just generate the library on the fly by embedding it into `stdbuf`.  This allows us to install `stdbuf` using Cargo, so now everything can be built using just Cargo (yay).

I think this is enough that we can close #1104.

### CODE REVIEW

**Comment by Arcterus** [comment]
Also note that this means we can now go on crates.io.

**Comment by mpkh** [comment]
that's great, sadly building on windows with current rust is still being a bit messed up

**Comment by Arcterus** [comment]
How are you building?  I just built it on Windows.

**Comment by mpkh** [comment]
rustc 1.22.1 (05e2e1c41 2017-11-22)
building fine currently

maybe I had problem before because I've used to run cargo update or something and new win32 crate has serious changes

**Comment by Arcterus** [comment]
Ah okay.  I was having issues earlier because I forgot `unix` was a default feature.

**Comment by bugabinga** [comment]
Hi!

Cloning the repo and installing using `cargo install` now works fine. Good work!

Any ideas why 

```sh
cargo install  --git https://github.com/uutils/coreutils uutils
```

might fail? 

[Backtrace](https://hastebin.com/ozewipemur.coffeescript)

It is hard for me to parse, but I think it reports an issue in the `build.rs` of `stdbuf`.

**Comment by Arcterus** [comment]
Which version of the compiler are you using?  If it’s repeatable something may have changed in Cargo.

**Comment by Arcterus** [comment]
@bugabinga sorry it has taken so long to respond.  Interestingly, this issue only seems to happen when installing like `cargo --git https://github.com/uutils/coreutils uutils`.  If you clone the repository and run `cargo install` from there, it seems to work just fine.

**Comment by Arcterus** [comment]
@bugabinga from looking at Cargo bugs, it may be related to something like [this](https://github.com/rust-lang/cargo/issues/4263).

**Comment by bugabinga** [comment]
> @bugabinga sorry it has taken so long to respond. Interestingly, this issue only seems to happen when installing like cargo --git https://github.com/uutils/coreutils uutils. If you clone the repository and run cargo install from there, it seems to work just fine.
> 
Yes, I was aware. Sorry for not mentioning that. 

The bug you linked gives some clues , so I will test some more later and report back.

**Pull request merged**
