### PR TITLE
fix build infrastructure ; modernize library use

### PR DESCRIPTION
**Pull request by kwantam**
This patch begins the work of modernizing uutils to work with 1.0-ish
Rust. In particular, it

1. Updates to the latest submodules.

2. Convert mkmain.rs, mkuutils.rs, and src/uutils/uutils.rs
   to new slice syntax and use of new io, fs, and path APIs.

3. Convert src/common/util.rs to new io, fs, and path APIs.

4. Convert fmt to use new APIs.

The plan is to propagate fixes to all other submodules and thereby end up with something that builds against nightly. After that, it'd be ideal to make something that will build against beta and/or stable (i.e., not requiring anything behind feature gates).

### CODE REVIEW

**Comment by kwantam** [comment]
To be clear: this is not finished yet! I'm opening this now, but I'll continue to push against it. Anyone else interested in helping, please fork and submit PRs against my new_io branch. I'd recommend starting one utility at a time. For example, right now, you can

    make BUILD=fmt

and it will work. The plan is to tackle each util until all of them are building again.

**Comment by Heather** [comment]
@kwantam looks good to me, not sure if we should merge it now because it's already step forward

**Comment by kwantam** [comment]
Up to you! Either way my plan is to keep plugging away.

**Comment by tshepang** [comment]
@kwantam what sort of heads-up? Can you submit a PR to that effect (I would but I'm not sure I understand).

**Comment by kwantam** [comment]
Perhaps the fact that I can't think of anything particularly intelligent to say indicates that we don't really need a note in the README after all :)

**Comment by tshepang** [comment]
@kwantam I think a note would help only if this PR wasn't merged yet

**Comment by kwantam** [comment]
Yep, I think you're absolutely right.

**Pull request merged**
