### PR TITLE
tests/tail: Add and fix tests.

### PR DESCRIPTION
**Pull request by Joining7943**
This pr also adds tests which would currently fail. They are ignored until fixed.

This pr also fixes some of the tests:

* Fixes expected newline characters at the end of error messages
* The error message for directory errors on windows and unix systems actually differ.

### CODE REVIEW

**Comment by Joining7943** [comment]
The failing tests on android and freebsd are not related to this pr as far as I can see

**Comment by tertsdiepraam** [comment]
I think you're still conflating multiple changes. Basically, your original PR  contains:
- Refactor
- Fixes and corresponding tests
- Tests that already pass on main
That should be the split here, because introducing these tests that currently fail is not really helpful. It makes more sense to review them as part of the PR that actually fixes them. It's not about just chunking it up based on which code you change, but about the functional changes. Also note that in this PR you refer to another PR that is not merged and might not be. The changes might be moved to another PR or be blocked for some other reason. Of course, we don't want this to happen, but it's possible so it doesn't make sense to refer to the PR.

**Comment by Joining7943** [comment]
Ok, looks like I misunderstood your comment. You said in #3952 something, that you wanted the changes to the tests separated. Personally, I like having tests up front, failing or not, and if you don't like merging my follow up prs you still got the failing tests which show the wrong behavior. However, I'm closing this pr then.

**Comment by tertsdiepraam** [comment]
> Personally, I like having tests up front, failing or not, and if you don't like merging my follow up prs you still got the failing tests which show the wrong behavior

For development I agree, but as PRs it becomes disjointed. I misspoke in #3952, because I didn't see that there were failing tests in there. Sorry, my mistake :)

**Pull request closed without merging**
