### PR TITLE
timeout: fix subprocess is never terminated

### LINKED ISSUE #4073: split produces one million lines of error messages in the GNU test suite
The `tests/split/filter.sh` test is still producing about one million lines of `shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory`. So, maybe we should skip that part of the test for the moment? I believe it is this part:
```
# Ensure that "endless" input _is_ processed for unbounded number of filters    
for buf in 1000 1000000; do
  returns_ 124 timeout .5 sh -c \
    "yes | split --filter='head -c1 >/dev/null' -b $buf" || fail=1
done
```

_Originally posted by @jfinkels in https://github.com/uutils/coreutils/issues/3281#issuecomment-1288127837_

### LINKED ISSUE #4176: timeout: subprocess is never terminated
When I was working on #4073, I discovered that timeout never terminates the subprocess under the sh shell.
Is this expected behavior?

```sh
$ timeout .5 sh -c "yes | split --filter='head -c1 >/dev/null' -b 1000"
$ ps aux | grep split
coreuti+ 55384  0.0  0.0   3244   712 pts/0    S+   05:05   0:00 grep split
$ /coreutils/target/release/timeout .5 sh -c "yes | split --filter='head -c1 >/dev/null' -b 1000"
$ ps aux | grep split
coreuti+ 55388  6.0  0.0   2680  1672 pts/0    S    05:05   0:00 split --filter=head -c1 >/dev/null -b 1000
coreuti+ 61201  0.0  0.0   3244   644 pts/0    S+   05:05   0:00 grep split
```

### PR DESCRIPTION
**Pull request by miles170**
Closes #4176.

This should also fix #4073.

Follow GNU's timeout behavior, send a signal to the process group to make sure subprocesses are cleaned up, and also send SIGCONT to the child and the whole process group after that.

### CODE REVIEW

**Comment by sylvestre** [comment]
would it be possible to add a test for this?
Thanks

**Comment by miles170** [comment]
> would it be possible to add a test for this? Thanks

Add `test_kill_subprocess` test.

**Comment by miles170** [comment]
I'm not sure why the `test_kill_subprocess` test result is not stable. It works fine on the local machine.

**Comment by miles170** [comment]
I'm not sure why the CI is failing randomly.
I have increased the timeout from 2 seconds to 5 seconds. (Everything works fine on my local Ubuntu 22.10)

**Comment by miles170** [comment]
I have increased the timeout from 5 seconds to 10 seconds, and the failing tests are not related to this PR.

**Review by tertsdiepraam — APPROVED** [review]
I reran the CI because of some unrelated linting issues that should be fixed by now, but this PR looks good.

**Comment by miles170** [comment]
I checked the GNU test logs and found that this should also fix #4073.

**Comment by tertsdiepraam** [comment]
Indeed this reduces the log size from 86MB to just 2MB, that's great! Let's hope the CI becomes a bit more stable as a result.

**Pull request merged**
