### PR TITLE
makefile: replace all uutils with coreutils

### PR DESCRIPTION
**Pull request by SuperSandro2000**
I noticed while debugging the nix package that the makefile is out of date.

### CODE REVIEW

**Comment by sylvestre** [comment]
Could you please create a new github action to run this target? thanks 
See
https://github.com/uutils/coreutils/blob/master/.github/workflows/CICD.yml

**Review by sylvestre — CHANGES_REQUESTED** [review]
Besides the CI, it makes sense, thanks :)

**Comment by sylvestre** [comment]
FYI I just merged https://github.com/uutils/coreutils/pull/1796

**Comment by sylvestre** [comment]
@SuperSandro2000 ping?

**Comment by SuperSandro2000** [comment]
> Could you please create a new github action to run this target? thanks

I don't really have the time to look into this right now.

**Comment by sylvestre** [comment]
I did it
https://github.com/uutils/coreutils/pull/2013

**Pull request merged**
