### PR TITLE
cksum: Added check for sum length

### LINKED ISSUE #6576: cksum: incomplete hex checksum is treated as mismatch instead of improper format
When checking a cksum-file, hexstrings that have the wrong length are reported as mismatching errors instead of simply broken formatting. (Arguably, they should be treated as errors for safety, but I guess it's better to stick with GNU behavior here.)

```console
$ cat sums
BLAKE2b (LICENSE) = e45898002c601e57504d0a7d7cb7ea5a1bc58d2f9a94fde09f370045ba2b3d57cbd26c3b0df1b4023b08c8b101303bb1b1b7c3363b38085194c1067c487a3052
BLAKE2b (build.rs) = ab3ec55005267c4d6333c585a313d424dc3fffc4f5b29aa335724d444bf6a9b26234b9db506e92b48dc76800248fffe618889d45a7b3b5228baca2ff7e2db3e
BLAKE2b (README.md) = c0a230cfdbbb686f91071119c915a19df28cb2e4fc575f19d5c6b81bf4e3ca2e83e6df49f14d8b89ece14eb4090be435a7af6fed2c981774e076caa8fe62b0
$ cksum -c sums
LICENSE: OK
cksum: WARNING: 2 lines are improperly formatted
$ cargo run -q cksum -c sums
LICENSE: OK
build.rs: FAILED
README.md: FAILED
cksum: WARNING: 2 computed checksums did NOT match
[$? = 1]
```

This isn't specific to blake2b:

```console
$ cat sums
SHA256 (LICENSE) = 29953405eaa3dcc41c37d1621d55b6a47eee93e05613e439e73295029740b10c
SHA256 (build.rs) = 299aa98fed9979a78d4022c9993ac19a5c647167b4e85ba7af2240d91ea759d
SHA256 (README.md) = 4d9b4c7b50b976ec5b0b2dce5a767d2da4b63eb68592017d475c4e11799a33
$ cksum -c sums
LICENSE: OK
cksum: WARNING: 2 lines are improperly formatted
$ cargo run -q cksum -c sums
LICENSE: OK
build.rs: FAILED
README.md: FAILED
cksum: WARNING: 2 computed checksums did NOT match
[$? = 1]
```

Found while reviewing #6499, although it's not the cause of this bug. (The `expected_checksum.len() / 2` expression looks suspicious, though.)

### PR DESCRIPTION
**Pull request by SarthakSingh31**
Fixes #6576

### CODE REVIEW

**Comment by cakebaker** [comment]
Can you please add a test so we don't regress in the future?

**Comment by sylvestre** [comment]
and it regressed a test (but maybe the test is incorrect)

```

--- TRY 3 STDERR:        coreutils::tests test_hashsum::test_check_b2sum_strict_check ---
thread 'test_hashsum::test_check_b2sum_strict_check' panicked at 'Expected stderr to be empty, but it's:
b2sum: WARNING: 7 lines are improperly formatted
', tests/by-util/test_hashsum.rs:932:10
stack backtrace:
   0: rust_begin_unwind
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:578:5
   1: core::panicking::panic_fmt
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:67:14
   2: tests::common::util::CmdResult::no_stderr
             at ./tests/common/util.rs:444:9
   3: tests::common::util::CmdResult::stdout_only
             at ./tests/common/util.rs:615:9
   4: tests::test_hashsum::test_check_b2sum_strict_check
             at ./tests/by-util/test_hashsum.rs:927:5
   5: tests::test_hashsum::test_check_b2sum_strict_check::{{closure}}
             at ./tests/by-util/test_hashsum.rs:908:36
   6: core::ops::function::FnOnce::call_once
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/ops/function.rs:250:5
   7: core::ops::function::FnOnce::call_once
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by SarthakSingh31** [comment]
@sylvestre The tests should be fixed.

I think the `checkrum.rs` and `sum.rs` need to rewritten with more typing. One of the big issues is that everything is referred to as `length`.
Like this 100% wrong
https://github.com/uutils/coreutils/blob/e33cecd7740eb3b14bf1c59bda5c5c5d90dfed22/src/uucore/src/lib/features/checksum.rs#L238-L239
Here bits (which should be bits) are passed to `Blake2b::with_output_bytes()` which expects to take in bytes. After some investigation I found that the bits are actually bytes. So the assignment to `HashAlgorithm::bits` is wrong.

I have found that this issue effects other parts of the code aswell.

**Comment by sylvestre** [comment]
@SarthakSingh31 are you still planning to finish this? thanks

**Pull request closed without merging**
