### PR TITLE
tests for ptx output width, -w 50 fails

### PR DESCRIPTION
**Pull request by sylvestre**

### CODE REVIEW

**Comment by sylvestre** [comment]
more tests is great :)

**Comment by sylvestre** [comment]
@mike-kfed some of the tests are failing, could you please have a look?

**Comment by mike-kfed** [comment]
that's kind of the point of those tests, to show that one is failing - the one with `-w 50`. That's why I added this as an issue #1807 and not a PR, it needs fixing ;).

When trying to implement #1763 I found even more output inconsistencies so I am inclined to wait for PR #1602 to be merged before I look into what exactly is causing that behaviour. I assume fixing the output algo will maybe close this `-w` arg issue too?

**Comment by sylvestre** [comment]
closing for now, sorry for jumping on the gun :)

**Pull request closed without merging**
