### PR TITLE
sort: implement --buffer-size and --temporary-directory (external sort)

### PR DESCRIPTION
**Pull request by electricboogie**
The crate this was built off of required some modification to use for our purposes.  It is Apache 2.0 licensed.  

I've copied the relevant docs and created a module in the ext_sorter directory.  Needs review but also needs approval for the dependency which I've "vendored" and its Apache license.

Thanks.

### CODE REVIEW

**Comment by electricboogie** [comment]
This is still a work in progress.  I touch something and I break something else, so it's not as ready for review as I thought just yet.  Thank you.

**Comment by sylvestre** [comment]
>  I touch something and I break something else

Usually, this is a sign that the code needs refactoring :)

**Comment by electricboogie** [comment]
I figured out why I was crashing on small buffer sizes.  It was because of the overhead of the Line struct when we serialize out.  I incorporated a change which expands the size of the buffer to account for the struct overhead (which is 96 bytes per line!).  

I wonder if there is a way to reduce the size of the struct in the most common case.  One serialized line looks like this:

{"line":"142:3 When my spirit was overwhelmed within me, then thou knewest my","selections":[{"range":{"ByIndex":{"start":0,"end":3}},"num_cache":{"WithInfo":{"exponent":2,"sign":"Positive"}}}]}

Perhaps an Option enum for selections instead of the SmallVec?  I supposed that still has to account for the largest possible Some value in memory though?

@miDeb you probably know better than I.  Any thoughts?

**Comment by electricboogie** [comment]
Okay, starting over.  This crate isn't for me!

**Comment by miDeb** [comment]
@electricboogie yeah the line struct has turned quite big. This is essentially a tradeoff between doing some initial precomputation vs doing everything again for each comparison. The latter is a bit slower if you do many comparisons, but uses less memory at the same time. Generally reducing the size of `Line` sounds like a very good idea, I'll have a look.

It's not very easy to estimate how much memory we use because that's different based on which options are passed to us.

**Pull request closed without merging**
