### PR TITLE
GnuComment: zizmor: ignore[dangerous-triggers]

### PR DESCRIPTION
**Pull request by dcampbell24**
This looks like a false positive.

### CODE REVIEW

**Comment by sylvestre** [comment]
maybe it should be reported to upstream as a bug

**Comment by woodruffw** [comment]
FWIW, this is not a false positive: the impact is low in your case, but any third-party fork can declare `foo.yml` with `name: GnuTests` and trigger your workflow in an upstream context.

(In your case the attacker can run a workflow with upstream repo credentials, which they can then use to submit an arbitrary comment/contents as if it was your normal "testsuite comparison" response. This is pretty low-impact, but it's probably not something you intended 🙂)

**Comment by dcampbell24** [comment]
Thanks for the information! If we were going to fix this what would we do?

**Comment by woodruffw** [comment]
My recommendation would be to switch from `workflow_run` to `workflow_call` -- there are some recommendations and links here: <https://woodruffw.github.io/zizmor/audits/#remediation_1>

**Pull request merged**
