### PR TITLE
install: fix bad target directory permissions

### LINKED ISSUE #4360: Wrong permissions on directories when invoking `uu-install -Dm644`
## Issue

The  `uu-install` implementation handles the argument combination of `-Dm644` which is commonly use in C/C++ install tools differently then `coreutils`.

The `uu-install` implementation sets the `-m644` permissions on the directories it creates and fails to copy the file as the execute bit is mentioning on the directories. 

Meanwhile, `install` creates directories with `755` and then creates the final file with `644` permissions as specified.

## Example test cases

uutils
```
$ /usr/bin/uu-install --version
/usr/bin/uu-install 0.0.17
$ /usr/bin/uu-install -Dm644 file.txt uutils644/a/b/c/d
/usr/bin/uu-install: cannot install 'file.txt' to 'uutils644/a/b/c/d': Permission denied
$ exa --no-user -l --tree uu*
drwxr-xr-x - 13 Feb 17:34 uutils644
drwxr-xr-x - 13 Feb 17:34 └── a
drwxr-xr-x - 13 Feb 17:34    └── b
drw-r--r-- - 13 Feb 17:34       └── c
```

```
$ /usr/bin/install --version | head -n1
install (GNU coreutils) 9.1
$ /usr/bin/install -Dm644 file.txt core644/a/b/c/d
$ exa --no-user -l --tree core*
drwxr-xr-x - 13 Feb 17:36 core644
drwxr-xr-x - 13 Feb 17:36 └── a
drwxr-xr-x - 13 Feb 17:36    └── b
drwxr-xr-x - 13 Feb 17:36       └── c
.rw-r--r-- 0 13 Feb 17:36          └── d
```

It appears the default behavior without `-m644`  matches `coreutils` as expected:
```
$ /usr/bin/uu-install -D file.txt uutils/a/b/c/d
$ exa --no-user -l --tree uu*
drwxr-xr-x - 13 Feb 17:34 uutils
drwxr-xr-x - 13 Feb 17:34 └── a
drwxr-xr-x - 13 Feb 17:34    └── b
drwxr-xr-x - 13 Feb 17:34       └── c
.rwxr-xr-x 0 13 Feb 17:34          └── d

$ /usr/bin/install -Dm644 file.txt core644/a/b/c/d
$ exa --no-user -l --tree core*
drwxr-xr-x - 13 Feb 17:36 core
drwxr-xr-x - 13 Feb 17:36 └── a
drwxr-xr-x - 13 Feb 17:36    └── b
drwxr-xr-x - 13 Feb 17:36       └── c
.rwxr-xr-x 0 13 Feb 17:36          └── d
```

### PR DESCRIPTION
**Pull request by kylemanna**
* Correct bug that set the last directory to the mode the file should have been set to.
* Add unit test to verify correct functionality.
* Fixes #4360

### CODE REVIEW

**Comment by kylemanna** [comment]
This is ready to go, any feedback?

**Comment by tertsdiepraam** [comment]
The test looks good, I'm just not sure I understand the change. You now have a structure like this:
```
if b.create_leading {
    ...
    if !b.create_leading && chmod(...) {
        ...
    }
}
```

Where `b` is behind a reference, so isn't mutated. Doesn't that just make the boolean always `false`?

**Comment by sylvestre** [comment]
@kylemanna ping?

**Comment by kylemanna** [comment]
@tertsdiepraam you're right, it doesn't make sense.  Turns out that `chmod` never need to run in that section, perhaps it a bug from an earlier version of `install`?

I figure out that you don't need to `chmod` the leading components, but didn't think much of the surrounding `if b.create_leading` until you pointed it out.

I've updated the code to never `chmod` leading components and the unit test remains unchanged from my earlier code.

All tests pass and this makes more sense.

Not sure why that code was introduced, certainly doesn't seem that the code path was subject to a unit-test until now.

**Review by tertsdiepraam — APPROVED** [review]
That makes more sense! Thanks for figuring this out.

**Comment by kylemanna** [comment]
Thanks!

**Pull request merged**
