### PR TITLE
add additional lints

### PR DESCRIPTION
**Pull request by danieleades**
add warnings for most of the lints used in #2963

### CODE REVIEW

**Comment by danieleades** [comment]
none of these are hard errors. users will still need to actually run `cargo clippy` to see the warnings

**Comment by sylvestre** [comment]
TIL & love it, thanks :)

I guess your clippy tasks will catch them

**Comment by tertsdiepraam** [comment]
@sylvestre can we merge this? If we wait too long with merging this there will be new lints to fix by the time it gets merged :)

**Comment by sylvestre** [comment]
yeah, sounds great :)

**Pull request merged**
