### PR TITLE
ls: Propagate (almost) all write errors up

### PR DESCRIPTION
**Pull request by hbina**
It was previously being ignored using `let _ = ...`.

### CODE REVIEW

**Review by tertsdiepraam — APPROVED** [review]
Awesome! Thanks!

**Comment by tertsdiepraam** [comment]
Sorry, waited too long to merge this. Could you fix the conflicts?

**Comment by hbina** [comment]
@tertsdiepraam resolved the conflict with main

**Comment by tertsdiepraam** [comment]
Ah, whoops, I should've squashed and merged. Anyway, good work!

**Pull request merged**
