### PR TITLE
hashsum: Windows: check in binary mode by default and allow --binary/--text

### LINKED ISSUE #6805: RFC: Impossible to verify checksum on Windows for any binary file that has the sequence `\r\n`
hashsum with `--check` always run in text mode on Windows:
https://github.com/uutils/coreutils/blob/3f694faa2e9399bcc7838322113cbf4c93575e8e/src/uu/hashsum/src/hashsum.rs#L236-L247
And you can't specify `--binary`
https://github.com/uutils/coreutils/blob/3f694faa2e9399bcc7838322113cbf4c93575e8e/src/uu/hashsum/src/hashsum.rs#L225-L227

Since text mode replaces `\r\n` with `\n`, this leads to unusual behavior:
In Linux:
```bash
$ cat sha256sums.txt | rg "2024.10.01-x86_64.iso"
b72dd6ffef7507f8b7cddd7c69966841650ba0f82c29a318cb2d182eb3fcb1db  archlinux-2024.10.01-x86_64.iso

$ sha256sum archlinux-2024.10.01-x86_64.iso --binary
b72dd6ffef7507f8b7cddd7c69966841650ba0f82c29a318cb2d182eb3fcb1db *archlinux-2024.10.01-x86_64.iso

$ sha256sum archlinux-2024.10.01-x86_64.iso --text
b72dd6ffef7507f8b7cddd7c69966841650ba0f82c29a318cb2d182eb3fcb1db  archlinux-2024.10.01-x86_64.iso

$ sha256sum -c sha256sums.txt
archlinux-2024.10.01-x86_64.iso: OK

$ sha256sum archlinux-2024.10.01-x86_64.iso --binary | sha256sum -c
archlinux-2024.10.01-x86_64.iso: OK

$ sha256sum archlinux-2024.10.01-x86_64.iso --text | sha256sum -c
archlinux-2024.10.01-x86_64.iso: OK

$ sha256sum archlinux-2024.10.01-x86_64.iso | sha256sum -c
archlinux-2024.10.01-x86_64.iso: OK
```

In Windows:
```bash
$ cat sha256sums.txt | rg "2024.10.01-x86_64.iso"
b72dd6ffef7507f8b7cddd7c69966841650ba0f82c29a318cb2d182eb3fcb1db  archlinux-2024.10.01-x86_64.iso

$ sha256sum archlinux-2024.10.01-x86_64.iso --binary
b72dd6ffef7507f8b7cddd7c69966841650ba0f82c29a318cb2d182eb3fcb1db *archlinux-2024.10.01-x86_64.iso

$ sha256sum archlinux-2024.10.01-x86_64.iso --text
e91465b21fa5f556c1015a3e8f44aef94301b2f742e56f23c6256c1bc9eb2855  archlinux-2024.10.01-x86_64.iso

$ sha256sum -c sha256sums.txt
archlinux-2024.10.01-x86_64.iso: FAILED
sha256sum: sha256sums.txt: no file was verified
sha256sum: WARNING: 1 computed checksum did NOT match

$ sha256sum archlinux-2024.10.01-x86_64.iso --binary | sha256sum -c
archlinux-2024.10.01-x86_64.iso: FAILED
sha256sum: WARNING: 1 computed checksum did NOT match

$ sha256sum archlinux-2024.10.01-x86_64.iso | sha256sum -c
archlinux-2024.10.01-x86_64.iso: FAILED
sha256sum: WARNING: 1 computed checksum did NOT match

$ sha256sum archlinux-2024.10.01-x86_64.iso --text | sha256sum -c
archlinux-2024.10.01-x86_64.iso: OK
```

I can think of 3 ways this might be fixed:
1. Make `--binary` the default on Windows (might break some workflows for checking text files)
2. Derive the mode for `--check` from previous output on Windows
    - Might require adding `*` manually before passing the input to hashsum, since the output might be obtained previously on GNU system without specifying `--binary`
3. Allow specifying `--binary` for `--check` on Windows

### PR DESCRIPTION
**Pull request by Pistonight**
On Windows, changed hashsum with `--check` to use the same behavior as without `--check` for selecting binary/text mode, i.e. allows `--binary`/`--text` flags and default to binary

Updated command line help message

Added binary test cases for hashsum. Using a PNG file since PNG header conveniently has `0x0D0A` in it. Verified the new test cases would fail on Windows without this change

Closes #6805

### CODE REVIEW

**Comment by sylvestre** [comment]
It is a lot of new files just for a small change. What about checking only one kind of checksum?

**Comment by Pistonight** [comment]
Won't hurt for adding a second test case for all types of sums right? Since right now the only test is `hello, world`? I can change it to just one type if you really want

**Comment by sylvestre** [comment]
yeah, adding 29 files for a simple test like this one isn't ideal

**Comment by Pistonight** [comment]
Updated to only check SHA256 scenarios

**Comment by sylvestre** [comment]
lgtm

**Pull request merged**
