### PR TITLE
try to use rust-cache on github action to build faster

### PR DESCRIPTION
**Pull request by sylvestre**

### CODE REVIEW

**Comment by sylvestre** [comment]
It trims the build from a few minutes.
example:
https://github.com/uutils/coreutils/runs/5263369090?check_suite_focus=true - 10m 17s 
to
https://github.com/uutils/coreutils/runs/5263359479?check_suite_focus=true - 7m 50s 

or
https://github.com/uutils/coreutils/runs/5263369200?check_suite_focus=true - 9m 25s
to
https://github.com/uutils/coreutils/runs/5263359462?check_suite_focus=true - 5m 9s

**Comment by tertsdiepraam** [comment]
That's pretty nice! So it caches between runs or only within a single run?

**Comment by sylvestre** [comment]
@tertsdiepraam dunno :(

**Comment by rivy** [comment]
Looks like good speed-ups! 🚀
LGTM!

**Review by rivy — APPROVED** [review]
👍🏻

**Comment by sylvestre** [comment]
merci :)

**Comment by sylvestre** [comment]
@tertsdiepraam looks like it is using the cache
Example:
https://github.com/uutils/coreutils/runs/5278229421?check_suite_focus=true
 succeeded [...] in 7m 2s 

on a brand new PR:
https://github.com/uutils/coreutils/pull/3172
\o/

**Pull request merged**
