### PR TITLE
chmod: improve compatibility

### PR DESCRIPTION
**Pull request by miDeb**
Various changes to improve the compatibility of `chmod`.

All chmod gnu tests should now be passing, _except_ `usage.sh`. This is because it tests very gnu specific behavior related to command line argument parsing, which we can't easily replicate.

Apparently there are also new failing tests that were previously erroring. I'll take a closer look at those, but I think it's because they previously errored because of a bug in chmod and now fail because of bugs in the utilities they are actually supposed to test.

### CODE REVIEW

**Comment by sylvestre** [comment]
I guess you saw:

`Changes from master: PASS +4 / FAIL +0 / ERROR -4 / SKIP +0
`

**Comment by miDeb** [comment]
What's going on with cirrus ci / freebsd? It often fails with `CI agent stopped responding!`. Is there a way to find out what's going wrong? I remember adding an expensive test (for `factor`), maybe that's the problem?

**Comment by sylvestre** [comment]
Any idea why the other tests regressed?

**Comment by miDeb** [comment]
The error message from the GNU tests is misleading. It says that the tests are passing on master, but in reality they are returning an error on master. This is because we assume that all tests that are not failing must be passing. However, if the test setup fails their status is `ERROR`, not `PASS` or `FAIL`.

The tests that are now failing used `chmod` in their setup, so they returned an error because of a bug in chmod before. Now they fail because of bugs in the utilities they were supposed to test in the first place.

**Comment by sylvestre** [comment]
Could you please fix the conflict? sorry :/

**Comment by sylvestre** [comment]
I think it needs a rustfmt too :)

**Pull request merged**
