### PR TITLE
Remove the author copyright notices

### PR DESCRIPTION
**Pull request by cakebaker**
This PR removes the author copyright notices from files missed by #5184

### CODE REVIEW

**Comment by tertsdiepraam** [comment]
Do you know why these were missed? Is the format slightly different?

**Comment by cakebaker** [comment]
The format is slightly different, they all use `*` in the comments.

**Comment by tertsdiepraam** [comment]
It all seems to be a bit messy. Here are the first four lines of all the files in `src` that are not `main.rs` (thanks nushell!). I'd propose that we convert all to variant 0.
```
╭────┬────────────────────────────────────────────────────────────────────────────────────╮
|  0 │ // This file is part of the uutils coreutils package.                              │
│    │ //                                                                                 │
│    │ // For the full copyright and license information, please view the LICENSE         │
│    │ // file that was distributed with this source code.                                │
│  1 │ // This file is part of the uutils coreutils package.                              │
│    │ //                                                                                 │
│    │ // For the full copyright and license information, please view the LICENSE file    │
│    │ // that was distributed with this source code.                                     │
│  2 │ //  * This file is part of the uutils coreutils package.                           │
│    │ //  *                                                                              │
│    │ //  * For the full copyright and license information, please view the LICENSE      │
│    │ //  * file that was distributed with this source code.                             │
│  3 │ // This file is part of the uutils coreutils package.                              │
│    │ //                                                                                 │
│    │ //  For the full copyright and license information, please view the LICENSE        │
│    │ // file that was distributed with this source code.                                │
│  4 │ #![allow(clippy::missing_safety_doc)]                                              │
│    │ #![allow(clippy::extra_unused_lifetimes)]                                          │
│    │                                                                                    │
│    │ // This file is part of the uutils coreutils package.                              │
│  5 │ // * This file is part of the uutils coreutils package.                            │
│    │ // *                                                                               │
│    │ // * For the full copyright and license information, please view the LICENSE file  │
│    │ // * that was distributed with this source code.                                   │
│  6 │ // This file is part of the uutils coreutils package.                              │
│    │ //                                                                                 │
│    │ //                                                                                 │
│    │ // For the full copyright and license information, please view the LICENSE         │
│  7 │ //* This file is part of the uutils coreutils package.                             │
│    │ //*                                                                                │
│    │ //* For the full copyright and license information, please view the LICENSE        │
│    │ //* file that was distributed with this source code.                               │
│  8 │ // spell-checker:ignore memmem                                                     │
│    │ //! Implementations of digest functions, like md5 and sha1.                        │
│    │ //!                                                                                │
│    │ //! The [`Digest`] trait represents the interface for providing inputs             │
│  9 │ //  * This file is part of the uutils coreutils package.                           │
│    │ //  *                                                                              │
│    │ //  * For the full copyright and license information, please view the LICENSE file │
│    │ //  * that was distributed with this source code.                                  │
│ 10 │ #![allow(unused_must_use)] // because we of writeln!                               │
│    │                                                                                    │
│    │ //  * This file is part of the uutils coreutils package.                           │
│    │ //  *                                                                              │
│ 11 │ // * This file is part of the uutils coreutils package.                            │
│    │ // *                                                                               │
│    │ // * For the full copyright and license information, please view the LICENSE       │
│    │ // * file that was distributed with this source code.                              │
│ 12 │ /*                                                                                 │
│    │  * This file is part of the uutils coreutils package.                              │
│    │  *                                                                                 │
│    │  * For the full copyright and license information, please view the LICENSE         │
│ 13 │ // TODO fix broken links                                                           │
│    │ #![allow(rustdoc::broken_intra_doc_links)]                                         │
│    │ //! Macros for the uucore utilities.                                               │
│    │ //!                                                                                │
╰────┴────────────────────────────────────────────────────────────────────────────────────╯
```

**Comment by sylvestre** [comment]
thanks

**Pull request merged**
