### PR TITLE
sort: handle cases where the output file is also an input file

### PR DESCRIPTION
**Pull request by miDeb**
In such cases we have to create a temporary copy of the input file to prevent
overwriting the input with the output. This only affects merge sort, because it
is the only mode where we start writing to the output before having read all inputs.

I also included fixes for other bugs I encountered.

### CODE REVIEW

**Comment by sylvestre** [comment]
Could you please run rustfmt ? thanks

**Comment by sylvestre** [comment]
and fix the new conflict (sorry)

**Comment by sylvestre** [comment]
There are a few cases that code coverage isn't hitting, can you address this?

**Comment by miDeb** [comment]
I _think_ coverage should be happy now.

**Comment by sylvestre** [comment]
But freebsd isn't ;)

```

---- test_sort::test_verifies_out_file stdout ----
current_directory_resolved: 
run: /tmp/cirrus-ci-build/target/debug/coreutils sort -o nonexistent_dir/nonexistent_file
current_directory_resolved: 
run: /tmp/cirrus-ci-build/target/debug/coreutils sort -o nonexistent_dir/nonexistent_file
thread 'test_sort::test_verifies_out_file' panicked at 'failed to write to stdin of child: Broken pipe (os error 32)', tests/common/util.rs:974:21


failures:
    test_sort::test_verifies_out_file
```

**Pull request merged**
