### PR TITLE
Bump MSRV to 1.54.0

### PR DESCRIPTION
**Pull request by tertsdiepraam**
Drivers:
- `clap` 3 only supports 1.54 and up.
- Const generics MVP
- Arrays implement `IntoIterator`
- Or patterns
- Many standard library stabilizations 

It might be worth noting that this is ahead of Debian Bullseye's version of Rust (1.48). I left out improvements that could be made with this new Rust version to keep this PR simple.

### CODE REVIEW

**Comment by tertsdiepraam** [comment]
The fixed clippy lints are new in version `1.58` so I fixed them here so they won't appear in other PR's.

**Comment by rivy** [comment]
Let's release a version before merging this...

**Comment by sylvestre** [comment]
Good idea!

Le 15/01/2022 à 15:34, Roy Ivy III a écrit :
> Let's release a version before merging this...

Sylvestre

**Comment by tertsdiepraam** [comment]
Yeah, that's a good idea

**Comment by sylvestre** [comment]
Tag done:
https://github.com/uutils/coreutils/releases/tag/0.0.9

**Pull request merged**
