### PR TITLE
s/DESTDIR/PREFIX/g README.md

### PR DESCRIPTION
**Pull request by ebfe**

### CODE REVIEW

**Comment by Heather** [comment]
@ebfe why not `DESTDIR` ..?

**Comment by ebfe** [comment]
Because `make DESTDIR=/usr/local install` would install stuff into `$(DESTDIR)$(PREFIX)` which is `/usr/loca/usr/local` with the default prefix

**Comment by ebfe** [comment]
Also the instruction were originally `make PREFIX=...` changed in  5c88a52c2f, but that change was reverted in 0bb971b

**Comment by Heather** [comment]
right

**Pull request merged**
