### PR TITLE
Initial oranda setup

### PR DESCRIPTION
**Pull request by tertsdiepraam**
[oranda](https://opensource.axo.dev/oranda/) is a new tool by [axo](https://axo.dev/), which can generate pretty websites for projects, based on info from `Cargo.toml` and GitHub. Here is the blog post where they explain it: https://blog.axo.dev/2023/06/oranda.

I think it would be nice to replace [this page](https://uutils.github.io/) with the generated website. It contains a link to the docs, funding and changelog. It also renders the mdbook documentation with the same style as the rest of the website. It can also show installation options, but currently, that feature is not yet flexible enough for us. We could open some issues on their repo to discuss what we would need (they're really friendly).

We might need to either clean up the README or make a separate markdown document as landing page to make this even more useful, but I think this is a nice start.

I chose the light theme to start with, but we can customize the CSS any way we want.

You can test the website yourself by installing `oranda`:
```
cargo install oranda --locked --profile=dist
```
and then running it in `dev` mode in the root of the project:
```
oranda dev
```

<details>
<summary>Click here to see screenshots of the generated website</summary>

image
image
image
image

</details>

### CODE REVIEW

**Review by cakebaker — COMMENTED** [review]
Looks good :)  A detail: the "contributing"-link is broken.

**Comment by tertsdiepraam** [comment]
Yeah I noticed that too. I think I'll have to write a separate homepage that's not based on the README to make that work.

**Comment by sylvestre** [comment]
much better, thanks

**Comment by sylvestre** [comment]
I guess you will have to do something to update ?

https://uutils.github.io/

**Comment by tertsdiepraam** [comment]
Yes, but like I said in some other issue. I can't work on my laptop at the moment. I'll pick it back up once it's repaired.

**Pull request merged**
