### PR TITLE
test: implement user, group ownership checks

### LINKED ISSUE #2337: `test -O foo` is failing
GNU:
```
       -O FILE
              FILE exists and is owned by the effective user ID
```

```
$ RUST_BACKTRACE=1 ./target/debug/test -O foo
thread 'main' panicked at 'explicit panic', src/uu/test/src/test.rs:109:22
stack backtrace:
   0: std::panicking::begin_panic
             at /home/sylvestre/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:519:12
   1: uu_test::eval
             at ./src/uu/test/src/test.rs:109:22
   2: uu_test::uumain::{{closure}}
             at ./src/uu/test/src/test.rs:20:51
   3: core::result::Result<T,E>::and_then
             at /home/sylvestre/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/result.rs:704:22
   4: uu_test::uumain
             at ./src/uu/test/src/test.rs:20:18
   5: test::main
             at ./src/uu/test/src/main.rs:1:1
   6: core::ops::function::FnOnce::call_once
             at /home/sylvestre/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### PR DESCRIPTION
**Pull request by drocco007**
closes #2337

### CODE REVIEW

**Comment by drocco007** [comment]
Well drat. It appears that the tests run as `root`/`wheel` on FreeBSD, foiling my attempt at a negative test (-O/-G of a file I do _not_ own).

**Comment by sylvestre** [comment]
Could you please ignore the test on freebsd?

**Comment by sylvestre** [comment]
Seems that we are getting one more tests working

`GNU testsuite = TOTAL: 601 / PASS: 160 / FAIL: 331 / ERROR: 20`
=>
`GNU testsuite = TOTAL: 601 / PASS:  161 / FAIL:  330 / ERROR: 20`

**Comment by drocco007** [comment]
@sylvestre sorry, I’ve been travelling. I’ll ignore those failing tests on FreeBSD.

**Review by tertsdiepraam — COMMENTED** [review]
Thanks for sticking with this! The spell-checker is complaining about `euid` and `egid`. Could you add those to the `spell-checker:ignore` lines at the top of the files?

**Comment by drocco007** [comment]
@tertsdiepraam sure thing!

**Comment by drocco007** [comment]
@sylvestre @tertsdiepraam it appears to be working now. The failed check looks unrelated: it appears to be random failure of one of the `sort` tests on Windows.

**Comment by tertsdiepraam** [comment]
We do indeed have some unrelated failures sometimes. Thanks for your contribution!

**Pull request merged**
