### PR TITLE
du: fix --apparent-size on ext4

### LINKED ISSUE #1292: du --apparent-size very not accurate
Using GNU du, if I check the size of a certain directory I get a report of 4.4G, if I use --apparent-size it shows up as 4.1G. If I use uutils du I get 4.4G, in line with GNU du, but if I use --apparent-size I get 44.9G. In another directory GNU du reports 216M with and without --apparent-size, while uutils du reports 215.7M without, and 1.1G with. Multiple other directories have very large discrepancies like this when using uutils du --apparent-size.

### PR DESCRIPTION
**Pull request by JJJollyjim**
Fixes #1292

### CODE REVIEW

**Comment by Arcterus** [comment]
Have you tested this on e.g. macOS?

**Comment by Snuggle** [comment]
The bug was also present in MacOS and the pull request fixes it for me, tested just now.

**Comment by cnd** [comment]
@JJJollyjim by that logic and with that PR https://github.com/uutils/coreutils/pull/1297 it will work same way as with `-b` not sure if that should be so.

**Comment by E5ten** [comment]
@JJJollyjim I think this needs to be rebased before they can merge it?

**Comment by Arcterus** [comment]
Sorry it's taken so long to get back to this.  I'll be going through the other PRs and issues in the next few days.  Closed due to merging #1311.

**Pull request closed without merging**
