### PR TITLE
Implement stat

### PR DESCRIPTION
**Pull request by knight42**
Finally made it! Many times of refactoring... Orz. There is some remaining work though.

TODO:
* [x] More test cases
* [x] Clean up the code
* [x] Add entry in Cargo.toml
* [x] Behave the same as the `stat` on OS X (won't fix at present)
* [x] Make CI happy :/

@Heather Maybe a code review? I am inexperienced in Rust. Any suggestion would be appreciated :-D

### CODE REVIEW

**Comment by Heather** [comment]
@jbcrail may you review this

**Comment by jbcrail** [comment]
@Heather thanks, will do.

@knight42, this looks great! The code is easy to read and extend. 👍 

I've grouped my suggestions into different categories. I thought this would be easier than individually commenting on each line.

---
###### Add `stat` to `Cargo.toml` and `Makefile`

This will add the program to the rest of the utilities. This will help Travis CI and AppVeyor build and test the new program.

Also, add `stat` to the Unix-only section in `Makefile`, since the program is specific to Unix at this time.

###### Add integration tests to `tests/test_stat.rs`

###### Wrap body of macros with braces, instead of just parentheses

```
#[macro_export]
macro_rules! has {
    ($mode:expr, $perm:expr) => ({
         $mode & $perm != 0
    })
}
```

This will keep any local variables from leaking outside the macros.

###### Define permissions mode as `mode_t` instead of `u32`, which is system-specific

Also, update `meta.mode()` to `meta.mode() as mode_t`.

###### Add conditional compilation for `libc::statfs`

OS X doesn't have `f_namelen` or `f_frsize` in the `libc::statfs` structure.

**Comment by knight42** [comment]
@jbcrail Thanks for your pratical advice! I will fix these problems ASAP, but I have two exams this week and next week :sob: , so it may be delayed... 

On the other hand, I find out that I can no longer test a single utility as before, using `make UTILS=stat test`. I got the error message:
```
cargo build   -p stat
   Compiling libc v0.2.11 
   Compiling winapi v0.2.7 
   Compiling winapi-build v0.1.1 
   Compiling getopts v0.2.14 
   Compiling kernel32-sys v0.2.2 
   Compiling users v0.5.1 
   Compiling time v0.1.35 
   Compiling uucore v0.0.1 
   Compiling stat v0.0.1 
cargo test  --test stat --features "stat " --no-default-features 
error: no test target named `stat`
Makefile:251: recipe for target 'test_integration_stat' failed
make: *** [test_integration_stat] Error 101
```
Since the current Cargo.toml specifies the test name, cargo cannot find the desired test as before. Shall we drop the `--test` option but keep the name in [this line](https://github.com/uutils/coreutils/blob/master/Makefile#L203)?

If so, then comes the second problem. Crate `uu_tail` is required in `tests/tests.rs` which  conflicts with the option `--no-default-features`. 

In fact, I have been confused about where should we place the function-level or module-level integration tests. Is there any guidelines?

**Comment by knight42** [comment]
The behaviour of stat on OS X seems quite different from its GNU version.

I won't fix this at present.

**Comment by Heather** [comment]
LGTM 👍

**Pull request merged**
