### PR TITLE
Move parse_relative_time from touch into uucore + tests and extend it

### PR DESCRIPTION
**Pull request by sylvestre**

### CODE REVIEW

**Comment by sylvestre** [comment]
@tertsdiepraam I am not sure why #[cfg(feature = "time")] is necessary in parse_relative_time.rs 
any idea why ? :)

**Comment by sylvestre** [comment]
unrelated, maybe it should be shipped as a new crate, wdyt ?

**Comment by sylvestre** [comment]
it is what I did :)
https://crates.io/crates/humantime_to_duration

**Comment by sylvestre** [comment]
https://github.com/uutils/coreutils/pull/4778

**Comment by Joining7943** [comment]
@sylvestre I think `fundu` could be capable of parsing this kind of relative times.

**Comment by tertsdiepraam** [comment]
It's your crate so up to you, but it seems out of scope for `fundu`. The full suite of possibilities that GNU support is quite complex and probably best left to another crate.

**Comment by tertsdiepraam** [comment]
> unrelated, maybe it should be shipped as a new crate, wdyt ?

Excellent :)

**Pull request closed without merging**
