### PR TITLE
test: implement parenthesized expressions, additional tests

### PR DESCRIPTION
**Pull request by drocco007**
* Replace the parser with a recursive descent implementation that handles parentheses and produces a stack of operations in postfix order. Parsing now operates directly on OsStrings passed by the uucore framework.

* Replace the dispatch mechanism with a stack machine operating on the symbol stack produced by the parser.

* Add many tests, including tests for parenthesized expressions.

### CODE REVIEW

**Comment by sylvestre** [comment]
wahou!
did you compare with GNU's tests?

**Comment by drocco007** [comment]
Hey @sylvestre!

I dropped the output from GNU `tests/misc/test.pl` [into this gist](https://gist.github.com/drocco007/c441b3595bbb5e9279d363fc1bed5eea).

Tests run with

```
make TESTS=tests/misc/test.pl SUBDIRS=. check
```

test_master.log is the output with a release build from the master branch; test_2159.log uses the version in this PR.

146 more of the GNU tests pass with this version

```
$ rg failed test_master.log | wc -l
208
$ rg failed test_2159.log | wc -l
62
$ rustup show
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/drocco/.rustup

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu
1.32.0-x86_64-unknown-linux-gnu
1.33.0-x86_64-unknown-linux-gnu
1.40.0-x86_64-unknown-linux-gnu (default)

active toolchain
----------------

1.40.0-x86_64-unknown-linux-gnu (default)
rustc 1.40.0 (73528e339 2019-12-16)
```

**Comment by sylvestre** [comment]
Well, bravo :)
this is impressive work!

**Comment by drocco007** [comment]
Thank you!

**Pull request merged**
