### PR TITLE
seq: handle scientific notation with uppercase 'E'

### LINKED ISSUE #6925: seq: padding of `-w` is incorrect if scientific notation uses `E` instead of `e`
I noticed that when using `-w`/`--equal-width`, the output is correct with `e` but not with `E`:

```
$ cargo run -q seq -w 0e15 1
0000000000000000
0000000000000001
$ cargo run -q seq -w 0E15 1
0000000000000000
0001
$ seq -w 0e15 1
0000000000000000
0000000000000001
$ seq -w 0E15 1
0000000000000000
0000000000000001
```

### PR DESCRIPTION
**Pull request by artP2**
Fixes #6925.

### CODE REVIEW

**Comment by sylvestre** [comment]
could you please add a test to make sure we don't regress? thanks

**Comment by artP2** [comment]
Is this enough?

**Comment by sylvestre** [comment]
almost, please also add an example here: https://github.com/uutils/coreutils/blob/main/tests/by-util/test_seq.rs

**Comment by artP2** [comment]
Done

**Comment by cakebaker** [comment]
Thanks for your PR!

**Pull request merged**
