### PR TITLE
factor: Refactor the factoring logic

### PR DESCRIPTION
**Pull request by nbraud**
- [x] Separate the data structure and factoring logic (`uu_factor::factor`) from the CLI code and I/O.
   Improves maintainability and readability.
- [x] Avoid moving data around (~1% runtime improvements, reduction in memory usage) 
- [x] ~~Refactor things so factoring algorithms return a factor (or `None`) to `factor`.~~
  This refactoring will enable implementing multiple factoring methods (and dynamically selecting the best one based on smoothness etc.)

On its own, the performance improvement compared to `master` is pretty negligible, but when combined with #1554 we get another ~15% improvement.

### CODE REVIEW

**Comment by nbraud** [comment]
@Arcterus (or any other maintainer) : this fails to build because of the `uucore_procs::main!` invocation, and I have no idea where that macro is documented; could you suggest a fix so I can make further progress on this?

**Comment by Arcterus** [comment]
That’s in the `uucore` repo at the moment.  I think the path is something like `src/uucore_procs/src/lib.rs` or something like that.  If you can wait until tomorrow (or I guess later today at this point...), I can suggest a fix.

**Comment by nbraud** [comment]
> If you can wait until tomorrow (or I guess later today at this point...), I can suggest a fix.

Yes, don't stress out about it  :)
It's not as if I didn't have another draft PR to work on, or a bunch of other local branches  :sweat_smile:

**Comment by nbraud** [comment]
I think this is ready for review as-is.

I did not (yet) move the factoring functionality to its own crate, as I realised it's not obvious where to put it, how to integrate with the release process for `coreutils`, etc...

**Comment by nbraud** [comment]
Found a couple minor improvements, should now be clean on Clippy.

I'm not doing the last change I mentioned (making `find_factor` return an `Option<u64>` instead of looping until success) quite yet, as it doesn't make sense without also implementing another factor-finding algorithm (which is entirely out-of-scope for this PR)

**Comment by nbraud** [comment]
I just rebased on `master` and added further testsuite improvements, shaking a couple more bugs lose (one of which was also caught in #1554).

Regarding performance, the improvement compared to `master` is pretty negligible (~1% on its own), but when combined with #1554 we get another ~15% improvement (compared to #1554 alone, which is already 2× faster than `master`)

**Pull request merged**
