### PR TITLE
Create the mergify configuration

### PR DESCRIPTION
**Pull request by sylvestre**

### CODE REVIEW

**Comment by rivy** [comment]
I'm definately for good automation, but I've never used `mergify`. After reading through the configuration file docs, I'm not sure what the line `- 'status-success=ci/circleci'` is doing.

I'd expect that it would be correct to require all checks pass. But from the docs, that doesn't seem possible, and it looks like each GHA job and other CI step needs to be listed separately(`CICD / Style (ubuntu-latest, unix)`, `CICD / Style (macos-latest, unix)`, ...,  `CICD / Build (ubuntu-16.04, x86_64-unknown-linux-gnu, feat_os_unix, use-cross)`, ..., `continuous-integration/appveyor/branch`, `continuous-integration/appveyor/pr`, `continuous-integration/travis-ci/pr`, `continuous-integration/travis-ci/push`, `stable x86_64-unknown-freebsd-12`).

Is that true? And so, do we need to add all the jobs?

**Comment by sylvestre** [comment]
@jd Do we need to add every job to have mergify to act? thanks :)

**Comment by jd** [comment]
Yes, you do. As explained here: https://doc.mergify.io/conditions.html#validating-all-status-check

**There is no such thing as “every status check” in GitHub.**

If you are able to programmatically generate the list of status checks that is being reported, you can probably write a little script that keeps that in sync with e.g. your GitHub actions list.

**Comment by rivy** [comment]
From looking at this bot, I think we should look a bit further for alternate automation before commiting to it.

**Pull request closed without merging**
