### PR TITLE
MSRV 1.56

### PR DESCRIPTION
**Pull request by tertsdiepraam**
Fixes https://github.com/uutils/coreutils/issues/3342

We need to bump to 1.56 for the dependencies mentioned in that issue. However, because of how editions work, we don't necessarily need to switch to the 2021 edition for the dependencies to use the 2021 edition, so I left that out of this PR. I would propose that we switch soon after merging this though.

I have also included fixes for two places where a comment mentioned that it could be cleaned up once the MSRV would be bumped up.

Do we want to tag a new release before merging this?

### CODE REVIEW

**Comment by sylvestre** [comment]
Yeah, tagging and upload would be great :)
do you want to do it?

**Comment by rivy** [comment]
> Do we want to tag a new release before merging this?

Yes, please.

**Comment by tertsdiepraam** [comment]
> do you want to do it?

Never done it, but I'll try to do it in a bit!

**Comment by sylvestre** [comment]
I am using util/update-version.sh & util/publish.sh   to publish a new version
they are both terrible but are doin 90% of the work

**Comment by tertsdiepraam** [comment]
Alright! I couldn't find the time to do it today, but I'll do it tomorrow.

**Pull request merged**
