### PR TITLE
Updated sha1 crate from 0.6 to 0.10

### PR DESCRIPTION
**Pull request by Aman-Mandal**

### CODE REVIEW

**Comment by tertsdiepraam** [comment]
Thanks! Looking at the CI it seems like the `sha1` crate had some breaking changes that make this fail. You can check the CI output youself: https://github.com/uutils/coreutils/runs/4995785438?check_suite_focus=true

**Comment by Aman-Mandal** [comment]
I am lil confused right now! Why these errors are occuring?

**Comment by sylvestre** [comment]
well, you should try to compile your changes before pushing them for review ;)

**Comment by Aman-Mandal** [comment]
> well, you should try to compile your changes before pushing them for review ;)

Okayyy Sir :)   I will fix this asap!

**Comment by sylvestre** [comment]
Sorry but because of the lack of activity, we merged
https://github.com/uutils/coreutils/pull/3110
instead

**Pull request closed without merging**
