### PR TITLE
 unexpand: should allow multiple files #5852 and  unexpand: show error message if a directory is specified #5845 

### PR DESCRIPTION
**Pull request by biplab5464**
fix the issue for allowing multiple files and showing error message when unexpand args is directory or file doesn't exist

### CODE REVIEW

**Comment by biplab5464** [comment]
i the above test failing nothing do with my code ?

**Comment by cakebaker** [comment]
No, the failing Android test is not related to this PR.

Can you please rebase your PR? It contains many unrelated commits...

**Comment by biplab5464** [comment]
can you guide me how to rebase you PR i tried to find it on internet and but it didn't work

**Comment by biplab5464** [comment]
hello i got to know that you can rebase with update button but it is showing "this branch cannot be rebase due to conflicts"

**Pull request closed without merging**
