### PR TITLE
dircolors: fix loop where filter_map ignores errors

### LINKED ISSUE #4573: `dircolors` on a folder causes an infinite loop
Similar to https://github.com/uutils/coreutils/issues/4539, with a very similar cause.

These two lines found with `rg -F ".filter_map(Result::ok)"` ignore errors and make the iterators which makes the iterators get stuck in an infinite loop:
```
uu/dircolors/src/dircolors.rs
142:        result = parse(fin.lines().filter_map(Result::ok), &out_format, files[0]);
147:                result = parse(fin.lines().filter_map(Result::ok), &out_format, files[0]);
```

GNU just seems to ignore the error:
```shell
$ dircolors src
LS_COLORS='';
export LS_COLORS 
```

See https://github.com/uutils/coreutils/issues/4539#issuecomment-1479217834 for a possible way to fix this.

### PR DESCRIPTION
**Pull request by daviddwk**
Fixes #4573 by using replacing filter_map with map_while to catch errors. Specifically, resolves an infinite loop when reading a directory.

### CODE REVIEW

**Review by tertsdiepraam — COMMENTED** [review]
Nice! Thanks! Could you add test for this in https://github.com/uutils/coreutils/blob/main/tests/by-util/test_dircolors.rs?

**Comment by sylvestre** [comment]
Fails on Windows:
```

failures:

---- test_dircolors::test_dir stdout ----
mkdir: C:\Users\RUNNER~1\AppData\Local\Temp\.tmpSl43EE\dir
run: D:\a\coreutils\coreutils\target\debug\coreutils.exe dircolors dir
thread 'test_dircolors::test_dir' panicked at 'Command was expected to succeed.
stdout = 
 stderr = dircolors: dir: Access is denied. (os error 5)
', tests\by-util\test_dircolors.rs:215:10
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/1db9c061d387a66ab16a90ec5a1b90adf216e2da/library\std\src\panicking.rs:579
   1: core::panicking::panic_fmt
             at /rustc/1db9c061d387a66ab16a90ec5a1b90adf216e2da/library\core\src\panicking.rs:64
   2: tests::common::util::CmdResult::success
             at .\tests\common\util.rs:385
   3: tests::common::util::UCommand::succeeds
             at .\tests\common\util.rs:1552
   4: tests::test_dircolors::test_dir
             at .\tests\by-util\test_dircolors.rs:213
   5: tests::test_dircolors::test_dir::closure$0
             at .\tests\by-util\test_dircolors.rs:210
   6: core::ops::function::FnOnce::call_once<tests::test_dircolors::test_dir::closure_env$0,tuple$<> >
             at /rustc/1db9c061d387a66ab16a90ec5a1b90adf216e2da\library\core\src\ops\function.rs:250
   7: core::ops::function::FnOnce::call_once
             at /rustc/1db9c061d387a66ab16a90ec5a1b90adf216e2da/library\core\src\ops\function.rs:250
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    test_dircolors::test_dir
```

**Comment by sylvestre** [comment]
@daviddwk ping? thanks

**Comment by sylvestre** [comment]
please reopen when it is ready

**Pull request closed without merging**
