### PR TITLE
Remove unnecessary dependencies of getopts & libc for utilities.

### PR DESCRIPTION
**Pull request by antiagainst**

### CODE REVIEW

**Comment by mpkh** [comment]
I need to check... what's wrong with Linux travis...

**Comment by mpkh** [comment]
Thanks for clean up!

**Comment by antiagainst** [comment]
The buildbot was failing before my pull request, I think.

**Comment by ebfe** [comment]
mountpoint for /dev/zero is wrong in the stat test. Unrelated to this PR.

**Pull request merged**
