### PR TITLE
Fix unittests not running in CI

### PR DESCRIPTION
**Pull request by tertsdiepraam**
Might fix https://github.com/uutils/coreutils/issues/3260

### CODE REVIEW

**Comment by tertsdiepraam** [comment]
It's unveiled some errors 😄

**Comment by sylvestre** [comment]
very interesting finding, (and oups :)

**Comment by sylvestre** [comment]
excited to see what the coverage is going to look like :)

**Comment by tertsdiepraam** [comment]
Interesting, it's reporting -4.33%. That seems really odd, cause we're supposed to be running the same tests as before and some more

**Comment by sylvestre** [comment]
because " GnuTests / Run GNU tests with coverage (pull_request)" is still running

**Comment by sylvestre** [comment]
Fun, it doesn't change:
` codecov/project Successful in 1s — 73.60% (+0.00%) compared to ad237f8 `

maybe these tests aren't instrumented?!

**Pull request merged**
