### PR TITLE
#834: Change license.

### LINKED ISSUE #834: Bug: Not GPL. :-)
Hi,

I love this project, but infrastructural software really should be under the GPL. It's very important that distributed software can be fixed by the end user, which the MIT licenses & friends doesn't require.

Please consider releasing as GPL.

Regards,
Paul

### PR DESCRIPTION
**Pull request by ivegotasthma**
Closes #834 . `src/sync/sync.rs` is still MIT but that shouldn't be much of an issue for now.

### CODE REVIEW

**Comment by ebfe** [comment]
You can't simply do that without consent of every contributor. Please proof me wrong, thanks.

**Comment by ivegotasthma** [comment]
@ebfe Where is it said that I need the consent of every contributor?

**Comment by Heather** [comment]
@ebfe you're right, feel free close this PR for now because it's not contribution, it's actually something very doubtful

**Comment by ebfe** [comment]
> @ebfe Where is it said that I need the consent of every contributor?

As a thought experiment: If you can change the license on other peoples
code like you wish, why do they exist in the first place?

**Comment by ivegotasthma** [comment]
@ebfe As a thought experiment: If you put out your code under a license with no restrictions on usage and no further explanation of what constitutes abuse, what makes you think I can't do that?

The only copyright mention is that it belongs to `Jordi Boggiano` so if he chooses to merge it, then it works.

**Comment by Heather** [comment]
@ivegotasthma yes, sure, if I choose to merge it - it will work either but only in case when we don't respect each other

**Comment by ivegotasthma** [comment]
@Heather It's your project, I am trying to understand your position. What does this have to do with respect?

**Comment by Heather** [comment]
@ivegotasthma it's not my project, I'm just contributor with push access

**Pull request closed without merging**
