### PR TITLE
who: move from getopts to clap (#2124)

### LINKED ISSUE #2124: who: move from getopts to clap
Code is in:
https://github.com/uutils/coreutils/blob/master/src/uu/who/src/who.rs

Tests:
https://github.com/uutils/coreutils/blob/master/tests/by-util/test_who.rs

As example:
https://github.com/uutils/coreutils/commit/9081e120d6b866c94679d9e29c7bdb17ccccb4d0

### PR DESCRIPTION
**Pull request by jhscheer**
* move from getopts to clap (closes #2124)
* add more tests

Clap `v3.0.0-beta.2` was needed instead of the latest stable `2.33.3` in order to be able to use `Arg::visible_short_alias`.
Otherwise the use of multiple short flags for the same option would have required an ugly work around with an additional `App::arg` for every short flag alias.

Since all other ports use clap `2.33`, I'm unsure if it's okay to use a non stable Clap?
There are other uutils that would benefit from `Arg::visible_short_alias`, e.g. `rm -r` / `rm -R` (#1834), etc.

### CODE REVIEW

**Comment by sylvestre** [comment]
I would rather not rely on non stable version. Sorry
do we have an eta clap3 btw?

**Comment by jhscheer** [comment]
Okay then `2.33.3` it is.
I also wonder about the ETA for Clap 3.0.

**Comment by ycd** [comment]
I think there is at least 6 months before Clap 3.0, see https://github.com/clap-rs/clap/issues/1037

**Comment by jhscheer** [comment]
@sylvestre this is ready to review/merge

**Comment by sylvestre** [comment]
@jhscheer it is failing on travis
https://travis-ci.org/github/uutils/coreutils/jobs/769608125

```
---- test_who::test_lookup stdout ----

current_directory_resolved: 

run: /home/travis/build/uutils/coreutils/target/debug/coreutils who --lookup
current_directory_resolved: 
run: who --lookup
thread 'test_who::test_lookup' panicked at 'assertion failed: `(left == right)`
Diff < left / right > :
<"travis   pts/0        2021-05-05 21:03 (\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}10)\n"
>"travis   pts/0        2021-05-05 21:03 (10.16.5.10)\n"
', tests/common/util.rs:205:9

```

Could you please have a look? thanks

**Comment by sylvestre** [comment]
@jhscheer opened: https://github.com/uutils/coreutils/issues/2181

**Pull request merged**
