### PR TITLE
install: remove / from end of path if it exists so as not to mess with .exists()

### PR DESCRIPTION
**Pull request by mtimaN**
#5720 fix.
I figured paths ending in "/" make .exists() not work properly so I added a check as to remove the / if there is one.

### CODE REVIEW

**Comment by cakebaker** [comment]
The change unfortunately breaks the `test_install_creating_leading_dirs_with_single_source_and_target_dir` test :|

**Comment by mtimaN** [comment]
> The change unfortunately breaks the `test_install_creating_leading_dirs_with_single_source_and_target_dir` test :|

I'll look into it. Thanks for the support.

**Comment by mtimaN** [comment]
@cakebaker should be alright now. Let me know what else I have to do before the merge.

**Comment by sylvestre** [comment]
could you please add a test ? thanks

**Comment by mtimaN** [comment]
> could you please add a test ? thanks

Done.

**Comment by cakebaker** [comment]
Thanks for your PR :)

**Pull request merged**
