### PR TITLE
clippy: fix warnings introduced with Rust 1.78

### PR DESCRIPTION
**Pull request by cakebaker**
This PR fixes the clippy warnings introduced with Rust 1.78. In two cases I used `#[allow(clippy::assigning_clones)]` because the suggested changes didn't work.

### CODE REVIEW

**Comment by cakebaker** [comment]
Changes since last push:

* fixed warning in `df` unit test

**Comment by sylvestre** [comment]
> the suggested changes didn't work.

do you have details ?
it might interest @samueltardieu

**Comment by cakebaker** [comment]
Changes since last push:

* reversed change from previous push, used `#[allow(assigning_clones)]` instead

**Comment by samueltardieu** [comment]
Indeed, it looks like `assigning_clones` is a false positive here, as the entity is reassigned to the result of a computation on itself and is thus borrowed. I'll check that this has been properly registered as a bug on Clippy side.

**Pull request merged**
