### PR TITLE
tests: add some basic chmod tests

### PR DESCRIPTION
**Pull request by ebfe**

### CODE REVIEW

**Comment by Heather** [comment]
@Arcterus @ebfe having broken travis is bad idea thought

**Comment by Arcterus** [comment]
In my opinion, it's better to have tests that break Travis than to not have tests.  At least this way everyone knows chmod is broken.

**Comment by ebfe** [comment]
Alternativelt #788 and #789

**Comment by ebfe** [comment]
@Arcterus On the other hand broken tests make it more difficult to spot new failures in pull request. Not sure whats the best path.

**Comment by Arcterus** [comment]
That's true.  I'm not really sure either, but we can disable the test for now.

**Comment by Heather** [comment]
in my opinion we should not break travis with such reason, it's our validation friend, not our todo list thing

**Pull request merged**
