### PR TITLE
Speed up factor::numeric::gcd

### PR DESCRIPTION
**Pull request by nbraud**
- [x] Add a [criterion]-powered benchmark for `factor::numeric::gcd`.
- [x] Replace its implementation with Stein's binary GCD algorithm
      ~50-65% faster (on the GCD computations themselves)
- [x] Test against a reference implementation (Euclidean algorithm) 

[criterion]: https://bheisler.github.io/criterion.rs/

### CODE REVIEW

**Comment by nbraud** [comment]
Can someone rerun `CICD / Style (macos-latest, macos)` ?
I still do not understand why we run the code style check on 3 different platforms, to be honest.

**Comment by rivy** [comment]
> Can someone rerun `CICD / Style (macos-latest, macos)` ?

The GHA jobs will sometimes crash for various, seemingly chaotic, reasons. If the crashing job is just style, I'd ignore a be about my day. For other jobs, you can push an amended commit (with no changes) to trigger a rebuild.

> I still do not understand why we run the code style check on 3 different platforms, to be honest.

Different platforms expose/use different code.

**Comment by nbraud** [comment]
> > I still do not understand why we run the code style check on 3 different platforms, to be honest.
> 
> Different platforms expose/use different code.

I'm aware, but that doesn't affect the code formatting and linting tools.

**Comment by rivy** [comment]
> > Different platforms expose/use different code.
> 
> I'm aware, but that doesn't affect the code formatting and linting tools.

I understand your point, but the "Style" check does frequently produce different warnings on different platforms (probably different compiler warnings; see warnings for https://github.com/uutils/coreutils/actions/runs/177424066).

**Comment by nbraud** [comment]
> I understand your point, but the "Style" check does frequently produce different warnings on different platforms

Exciting  :( 

Anyhow, this discussion is probably way out of scope for this PR, but I should mention I did rebase the branch now that #1554 landed.  :)

**Comment by nbraud** [comment]
Build failed on AppVeyor (Rust stable, Windows x64, GNU ABI) because the DNS resolution for `static.rust-lang.org` failed...

**Comment by nbraud** [comment]
I made `cargo fmt` happy (accidentally put 2 `use` statements out-of-order when resolving the merge conflict)

**Pull request merged**
