### PR TITLE
du: add --app as alias of --apparent-size to match GNU

### PR DESCRIPTION
**Pull request by sylvestre**

### CODE REVIEW

**Comment by tertsdiepraam** [comment]
This seems to be a case of something we're currently missing on all utils:
```
   Most programs that accept long options recognize unambiguous
abbreviations of those options.  For example, ‘rmdir
--ignore-fail-on-non-empty’ can be invoked as ‘rmdir --ignore-fail’ or
even ‘rmdir --i’.  Ambiguous options, such as ‘ls --h’, are identified
as such.
```

Clap doesn't seem to have support for that yet. There is an open issue from April 2020: https://github.com/clap-rs/clap/issues/1786. We could try to implement it there and use it once Clap 3 is released.

For now, we could just add these aliases of course.

**Comment by sylvestre** [comment]
yeah, for now, I just want to fix GNU tests :)

**Comment by tertsdiepraam** [comment]
I've opened a PR to Clap for this feature: https://github.com/clap-rs/clap/pull/2525. Let's hope it it will get merged and we'll be able to use it soon.

**Comment by sylvestre** [comment]
it didn't fix GNU tests but it showing some different errors

**Review by tertsdiepraam — APPROVED** [review]

**Comment by sylvestre** [comment]
don't hesitate to merge then directly btw ;)

**Pull request merged**
