### PR TITLE
Bump of the dependencies

### PR DESCRIPTION
**Pull request by sylvestre**
and do the necessary adjustment.

Only warning left:
```
warning: use of deprecated item 'rand::Rng::shuffle': use SliceRandom::shuffle instead
   --> src/uu/shred/src/shred.rs:432:28
    |
432 |         rand::thread_rng().shuffle(&mut pass_sequence[..]); // randomize the order of application
    |                            ^^^^^^^
    |
    = note: `#[warn(deprecated)]` on by default
```

### CODE REVIEW

**Comment by rivy** [comment]
I'm not in favor of increasing the MinSRV, unless we have a specific reason. Some platforms can't easily upgrade versions. For widest compatibility, we should keep it as low as possible. `Rust 2018` (v1.31) is a good, stable resting point for the code base until there's something we need in a more current version. And, so, I'm only in favor of upgrading dependencies when it doesn't affect the current code.

And, I like "MinSRV", it's a slightly longer, more obvious (and somewhat common) variant of the, admittedly, more prevalent "MSRV" abbreviation. I felt it hit a nice middle ground.

And, at a minimum, I'd like to defer any of this until I can get the code base into a state that's releasable on `crates.io`.

**Comment by sylvestre** [comment]
I do not agree with you on "MinSRV", it is very cryptic and I had at look at the CICD configuration to understand what it means. If you want to keep it short, "MinRustV" is only two more letters and more explicit.

About bumping the minimal version, it isn't what I had in mind, I was just trying to see if it would fix an issue I had. Nix needs a quite recent version of the compiler. I will see to lower this dep.

**Comment by rivy** [comment]
> I do not agree with you on "MinSRV", it is very cryptic and I had at look at the CICD configuration to understand what it means. If you want to keep it short, "MinRustV" is only two more letters and more explicit.

Agree to disagree, but I'm good with the `MinRustV` as a compromise, if you are?

> About bumping the minimal version, it isn't what I had in mind, I was just trying to see if it would fix an issue I had. Nix needs a quite recent version of the compiler. I will see to lower this dep.

👍 

What issue?

**Comment by rivy** [comment]
Closing this as dependencies are currently up-to-date on 'master'. We can re-open as another PR if/when needed.

**Pull request closed without merging**
