### PR TITLE
Replace deprecated value_of() with get_one()

### PR DESCRIPTION
**Pull request by cakebaker**
This PR replaces the usage of clap's deprecated `value_of()` with `get_one()`.

### CODE REVIEW

**Review by tertsdiepraam — COMMENTED** [review]
Can we change some of the `get_one::<String>` to `get_one::<&str>` to avoid some unecessary cloning? That might also get rid of some of the `.map(|s| s.as_str())` calls.

**Review by sylvestre — DISMISSED** [review]
see previous comment

**Comment by tertsdiepraam** [comment]
I tried this myself and got kinda stuck... Unless I'm missing something this API seems very weird. The use case we have most is that we just need some `&str` and that seems to be impossible because `get_one::<T>` returns `&T` and we can't move out of that reference. `T` can also not be `str` (without `&`), because that doesn't implement `Clone`. So we need `to_owned()` and `cloned()` calls all over the place, which defeats the purpose of using `&str` over `String` in the first place.

**Review by sylvestre — CHANGES_REQUESTED** [review]
Looks like it needs some conflict fixing :)

**Comment by tertsdiepraam** [comment]
I'm sure there are a lot of cases where we can use a more specific value parser instead, but that will require more work to get right.

**Pull request merged**
