### PR TITLE
df: some option changes

### PR DESCRIPTION
**Pull request by xxyzz**

### CODE REVIEW

**Comment by sylvestre** [comment]
Please add tests to cover all the changes like in
https://github.com/uutils/coreutils/blob/main/tests/by-util/test_df.rs

and please run rustfmt :)

**Comment by xxyzz** [comment]
`df --output -i` should fail, maybe it's clap's bug?

**Comment by rivy** [comment]
@xxyzz , for simple conflicts and when reasonably possible, please rebase instead of using internal merges of 'main'.
When commit lists with internal merges are finally merged back into 'main', it causes lots of unneeded tangling and "spaghettification" of the project commit graph. 

And thanks for your contributions!

**Review by jfinkels — APPROVED** [review]
This is adding some constraints to the command-line argument parsing to match the constraints of GNU df. Makes sense to me.

**Pull request merged**
