### PR TITLE
Clap 3

### PR DESCRIPTION
**Pull request by tertsdiepraam**
This is going to fail a lot of tests, but I tried to port everything to `clap` 3 all at once. I did this very naively with a lot of search & replace, so with the help of the CI, I try to fix the utils before marking this as ready.

### CODE REVIEW

**Comment by tertsdiepraam** [comment]
@sylvestre I just realized that `clap`'s MSRV is 1.54. Any chance we can bump our MSRV up?

**Comment by sylvestre** [comment]
yeah, clap is probably a good reason

**Comment by sylvestre** [comment]
/me is staring at the CI result :)

**Comment by tertsdiepraam** [comment]
That was interesting, the unit tests in `od` were using a mock object that was no longer valid with the new clap implementation, but the clap implementation was still correct. I removed the mock object and replaced it with the actual app.

**Comment by tertsdiepraam** [comment]
Well, a few GNU tests are broken with this one. I'll look into those later:
```
Error: GNU test failed: tests/misc/chcon-fail. tests/misc/chcon-fail is passing on 'master'. Maybe you have to rebase?
Error: GNU test failed: tests/rm/dangling-symlink. tests/rm/dangling-symlink is passing on 'master'. Maybe you have to rebase?
Error: GNU test failed: tests/rm/dir-no-w. tests/rm/dir-no-w is passing on 'master'. Maybe you have to rebase?
Error: GNU test failed: tests/rm/rm2. tests/rm/rm2 is passing on 'master'. Maybe you have to rebase?
```

**Comment by tertsdiepraam** [comment]
I have filed an issue with clap for 3 leading hyphens in options (https://github.com/clap-rs/clap/issues/3309), but I also found a workaround, which I will push.

**Comment by tertsdiepraam** [comment]
Only this GNU test is left (ignoring `rm2`):
```
tests/misc/chcon-fail.sh
```
Locally, it didn't seem to work either, until I did `cargo build --release` in `src/uu/chcon` and then it did work. I'm not sure what's going on...

**Comment by tertsdiepraam** [comment]
@sylvestre do you think we can merge this regardless of the failing GNU test? If not, then I need some help figuring out what's going wrong :)

**Comment by sylvestre** [comment]
@tertsdiepraam yeah, no big deal :)
Do you want me to merge it?

**Pull request merged**
