### PR TITLE
New release

### PR DESCRIPTION
**Pull request by sylvestre**

### CODE REVIEW

**Comment by sylvestre** [comment]
@tertsdiepraam you were planning to publish help_parser a new crate?
  no matching package named `help_parser` found

**Comment by tertsdiepraam** [comment]
Yes, `help_parser` should be published for everything to work I think. We could give it a prefix first (`uuhelp_parser`, `uucore_help_parser`, or something like that).

**Comment by tertsdiepraam** [comment]
I wonder if something like this could work for us: https://lib.rs/crates/cargo-smart-release

**Comment by sylvestre** [comment]
Let's do it!

**Pull request merged**
