### PR TITLE
Change target_os = "macos" to target_vendor = "apple"

### PR DESCRIPTION
**Pull request by aspenluxxxy**
Should cover all Darwin/XNU-based operating systems, as they are all effectively intercompatible.

Goes with https://github.com/uutils/coreutils/pull/1835 for iOS support.

### CODE REVIEW

**Comment by aspenluxxxy** [comment]
FYI, tests fail due to OOMing it seems? Don't think it's my fault

```
FAIL: tests/factor/t36.sh
gawk: cmd. line:1: (FILENAME=- FNR=168) fatal: node.c:415:make_str_node: r->stptr: can't allocate -2147483645 bytes of memory (Cannot allocate memory)
make[4]: *** [Makefile:13235: tests/test-suite.log] Error 1
```

**Comment by sylvestre** [comment]
correct, not your fault
@nbraud could you please look at this ? it has been failing since I accepted your patch ;)

**Comment by nbraud** [comment]
@sylvestre Is that the test failure you sent me?

**Comment by sylvestre** [comment]
@nbraud  oui, désolé!

**Pull request merged**
