### PR TITLE
Version 0.0.13

### PR DESCRIPTION
**Pull request by tertsdiepraam**

### CODE REVIEW

**Comment by tertsdiepraam** [comment]
To be sure about the next steps: when this is merged we tag the release on GitHub and run the `publish.sh` script, right? The build artifacts should be added automatically to the GitHub release, correct?

**Comment by sylvestre** [comment]
Please wait before you tag it
publish.sh shows sometimes some unexpected errors (remember uu_stdbuf_libstdbuf ;) )
So, you might have to push some configuration changes in the repo. Tag only when https://crates.io/crates/coreutils is at the right version (it means that the whole process worked)

TBH, I am quite ashamed of this :) (I am almost the only author, so, not blaming anyone else :)

**Comment by sylvestre** [comment]
(btw glad we are now using the same version of uucore & others :)

**Review by sylvestre — APPROVED** [review]

**Comment by tertsdiepraam** [comment]
Alright, so publish first, fix any errors and once that's done tag it on GitHub. Can I publish from this branch or do we need to merge it first?

**Comment by sylvestre** [comment]
From this branch is fine. In the past, I think I pushed the version change only when live

**Comment by tertsdiepraam** [comment]
@sylvestre Ah I need to receive an owner invite on crates.io, first. Could you send me one?

**Comment by sylvestre** [comment]
@tertsdiepraam I added you to the github group; I think you should have the right permissions

**Comment by tertsdiepraam** [comment]
@sylvestre Almost all packages have been upgraded, except `basenc`, `dd`, `chcon`, `csplit`, `pr` & `runcon`. uutils/maintainers are not set as the owner of these packages. See for instance https://crates.io/crates/uu_basenc.

**Comment by sylvestre** [comment]
@tertsdiepraam fixed!

**Pull request merged**
