### PR TITLE
dircolors: update internal db

### PR DESCRIPTION
**Pull request by cakebaker**
This PR updates the internal db of dircolors so that `-b`, `-c`, and `-p` return the same outputs as GNU dircolors.

### CODE REVIEW

**Comment by sylvestre** [comment]
Looks good.
Could you please document the update process in src/uu/ls/README.md?
thanks

**Comment by cakebaker** [comment]
Hm, why in `src/uu/ls/README.md`? Shouldn't it be in `src/uu/dircolors`?

**Comment by sylvestre** [comment]
oh yeah, sorry :)

**Comment by sylvestre** [comment]
thanks :)

**Pull request merged**
