### PR TITLE
who: fix `--lookup`

### LINKED ISSUE #2181: "who --lookup" is failing on travis CI
caused by https://github.com/uutils/coreutils/pull/2138

Log:
https://travis-ci.org/github/uutils/coreutils/jobs/769608125

```
---- test_who::test_lookup stdout ----

current_directory_resolved: 

run: /home/travis/build/uutils/coreutils/target/debug/coreutils who --lookup
current_directory_resolved: 
run: who --lookup
thread 'test_who::test_lookup' panicked at 'assertion failed: `(left == right)`
Diff < left / right > :
<"travis   pts/0        2021-05-05 21:03 (\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}10)\n"
>"travis   pts/0        2021-05-05 21:03 (10.16.5.10)\n"
', tests/common/util.rs:205:9
```

### PR DESCRIPTION
**Pull request by jhscheer**
This closes #2181.

`who --lookup` is failing with a runtime panic (double free).
Since `crate::dns-lookup` already includes a safe wrapper for `getaddrinfo`
I used this crate instead of further debugging the existing code in
utmpx::canon_host().

### CODE REVIEW

**Comment by jhscheer** [comment]
It looks like `socket2` which needs `libc ^0.2.86` can't be compiled on CICD MInRustV.
(libc was constraint to `<0.2.85` before this PR)

**Comment by sylvestre** [comment]
can you try to use an older version of socket2?

**Comment by jhscheer** [comment]
The dependency issues are now fixed.

**Comment by sylvestre** [comment]
Looking here https://github.com/uutils/coreutils/pull/2210/files
we can see that many lines aren't covered by tests, is that expected? thanks

**Comment by jhscheer** [comment]
I was wondering about that too.
It's weird because the test for `who --lookup` which reaches the lines the warning is complaining about, for `utmpx.rs` and for `who.rs`, is no longer set to ignore.
Also I added a test for `pinky` without flags which reaches the line the warning is complaining about.

**Pull request merged**
