### PR TITLE
shred: Implemented --force option

### PR DESCRIPTION
**Pull request by ajanicij**

### CODE REVIEW

**Comment by sylvestre** [comment]
Looks good but please add tests for this.
without the option => fails because of permission
with the option => works
thanks

**Review by sylvestre — CHANGES_REQUESTED** [review]
@ajanicij sorry but I need tests to merge it!

**Comment by ajanicij** [comment]
My test for shred --force is failing for Windows and FreeBSD, but I can't see why. I only have Ubuntu 18.04 and there the test is passing.

**Comment by sylvestre** [comment]
MS provides Windows images 
https://developer.microsoft.com/en-us/windows/downloads/virtual-machines/
(I have been using that for Windows work)
The error is:
```

---- test_shred::test_shred_remove stdout ----
current_directory_resolved: 
touch: C:\Users\RUNNER~1\AppData\Local\Temp\.tmpnbW4hh\test_shred_remove_a
touch: C:\Users\RUNNER~1\AppData\Local\Temp\.tmpnbW4hh\test_shred_remove_b
run: D:\a\coreutils\coreutils\target\x86_64-pc-windows-msvc\debug\coreutils.exe shred -u test_shred_remove_a
thread 'test_shred::test_shred_remove' panicked at 'assertion failed: self.success', tests\common\util.rs:149:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
you should disable stderr & stdout. Usually, it is giving enough information

See
https://github.com/uutils/coreutils/blob/master/tests/by-util/test_install.rs#L196-L201

**Comment by ajanicij** [comment]
The test is failing for FreeBSD. Unless someone has a better idea, I will have to install FreeBSD somewhere (DigitalOcean maybe) and see what is going on.

**Comment by sylvestre** [comment]
don't run the test on freebsd for now and create an issue to keep track of this :)

**Comment by ajanicij** [comment]
Skipping test_shred_force on freebsd. I have created issue #2061 for this problem.

**Pull request merged**
