### PR TITLE
tr: correctly handle multibyte octal sequences

### PR DESCRIPTION
**Pull request by andrewliebenow**

### CODE REVIEW

**Comment by andrewliebenow** [comment]
Partly resolves the last issue listed in https://github.com/uutils/coreutils/issues/6777.

I'm not sure how to perform logging inside the nom parsing code without the messages being printed twice.

**Comment by andrewliebenow** [comment]
First and last issues in #6777 are now addressed by this

**Comment by RenjiSann** [comment]
Hi, I've played a bit with octal parsing as well, and I come to the same conclusion as you, which is that the logging of a warning is impossible to do because it is executed several times.

The solutions I see are the following:
- Use some sort of global value to memoize the fact that this warning was already displayed (which is a terrible idea)
- Introduce a lexer before the parser to handle escape sequences (which is nice, but is also a much bigger change)

What do you think ?

**Comment by andrewliebenow** [comment]
@RenjiSann The least-bad idea I could think of was changing the return type of all of these functions to allow returning a warning to print, but that would be kind of ugly considering that it's only this one path that would actually return one.

I should probably remove my commented-out code, so we can at least get the main fix merged in (albeit without the warning).

**Comment by RenjiSann** [comment]
> @RenjiSann The least-bad idea I could think of was changing the return type of all of these functions to allow returning a warning to print, but that would be kind of ugly considering that it's only this one path that would actually return one.
I am not convinced this would efficiently solve the problem, it would keep
 
> I should probably remove my commented-out code, so we can at least get the main fix merged in (albeit without the warning).
Let's do this, and maybe open an issue for handling the warning correctly later

**Pull request merged**
