### PR TITLE
Fix gnu tests

### PR DESCRIPTION
**Pull request by jaggededgedjustice**
Ok, I am now confident that the tests are running against the rust code, new results:
```
 # TOTAL: 613
# PASS:  139
# SKIP:  87
# XFAIL: 0
# FAIL:  348
# XPASS: 0
# ERROR: 39
```
Also the running time is now at ~45 minutes.
It would be good if someone could review the results to make sure they are reasonable.

### CODE REVIEW

**Comment by sylvestre** [comment]
That makes way more sense :)
Many thanks!

**Comment by sylvestre** [comment]
Note that it didn't complete:
```

FAIL: tests/factor/t36.sh
make[4]: *** Deleting file 'tests/misc/sort.log'
make[4]: *** wait: No child processes.  Stop.
make[4]: *** Waiting for unfinished jobs....
make[4]: *** wait: No child processes.  Stop.
```

and we don't see the detailed output of the error, right?

**Comment by jaggededgedjustice** [comment]
Irritating, cos the run on my branch of the last commit worked: https://github.com/jaggededgedjustice/coreutils/actions/runs/535223948
I'll try and find out what went wrong.

**Comment by jaggededgedjustice** [comment]
Ok, tests don't hang now. If something does hang the SIGKILL from timeout will stop make deleting the log files.

**Comment by sylvestre** [comment]
looks great now! but scary!

**Comment by tdulcet** [comment]
The tests for these utilities will succeed because they either have not yet been implemented by uutils or the binaries are not created under the correct names, so the test suite is actually testing the GNU version:
```
[
b2sum
basenc
chcon
dd
dir
md5sum
pr
runcon
sha1sum
sha224sum
sha256sum
sha384sum
sha512sum
stty
vdir
```
For the `*sum` programs, it should be as simple as duplicating the uutils `hashsum` binary after the build.

I am not sure why we are deleting so many of the currently failing tests instead of just letting them fail. The `ulimit -t` command would have killed most of them if they hang (see #1431), although the limit argument needed to be higher (see https://github.com/uutils/coreutils/pull/1701#issuecomment-765465427). The `timeout` command is not a replacement for `ulimit`, since it does not apply to subprocesses.

**Comment by jaggededgedjustice** [comment]
The tests being deleted are only ones that hang, `ulimit` by itself is not always able to kill hung processes. For example if tests gget stuck waiting on IO they use no cpu time which means the ulimit doesn't trigger. Also, there's a risk that running tests known to hang will just end up filling the disk and stopping the tests part way through, since the ulimit is applied per-process and for example `tests/misc/seq.pl` will invoke seq multiple times and I'm not sure how many of those invocations would get stuck (there were 3 before I stopped checking, though I did find a new way to hang seq in addition to the large numbers issue). It would also increase the runtime significantly. So these tests need to be run with a timeout to prevent a run being stuck forever.
If you feel strongly about this I can add the ulimit back in and see which of those tests can be re-added safely.

**Comment by tdulcet** [comment]
The main problem is that the tests will likely not be reenabled after the issues are fixed. For example, #1708 was fixed in #1725, but the `numfmt` tests are still disabled. In addition, when the tests are disabled people may not realize there are any known issues the respective programs and developers will not know if their PRs fix those issues or cause regressions.

> For example if tests gget stuck waiting on IO they use no cpu time which means the ulimit doesn't trigger.

There were only a few of these cases and I believe most of them have since been fixed (such as #1704 and #1708).

>  for example `tests/misc/seq.pl` will invoke seq multiple times and I'm not sure how many of those invocations would get stuck (there were 3 before I stopped checking, though I did find a new way to hang seq in addition to the large numbers issue)

Yes, there were a half dozen or so `seq` commands that got into an infinite loop (see that file [here](https://github.com/coreutils/coreutils/blob/master/tests/misc/seq.pl)), but the `ulimit` command successfully killed them all. You just fixed some of these cases in #1731 and the rest should be addressed soon (https://github.com/uutils/coreutils/issues/1703#issuecomment-781091615).

> So these tests need to be run with a timeout to prevent a run being stuck forever.

Most of the individual tests currently have no timeout. Some of the test files you are deleting have hundreds of individual tests and generally, it is only a few of those at most that hang. If `ulimit` does not work because the test hangs waiting for IO, another option would be to just prefix the problematic test/utility with the `timeout` command. The advantage to this is that you can tailor the timeout duration to the specific test/utility, which would decrease the runtime.

The unimplemented utilities I listed above should probably be symbolically linked to the `false` program so that the respective tests will correctly fail.

**Comment by jaggededgedjustice** [comment]
I agree the current setup will leave tests no being re-enabled and hiding the true state. I'll see what I can do to improve things.

**Pull request merged**
