### PR TITLE
Improve utmpx

### PR DESCRIPTION
**Pull request by knight42**
Also enable users to conditioanlly use different features of `uucore`.

### CODE REVIEW

**Comment by knight42** [comment]
This is quite a big change. Are there any problems?

**Comment by mpkh** [comment]
LGTM

**Comment by nathanross** [comment]
regarding conditionally enabling different features, I thought rust already has pretty tree shaking - is the purpose of the the feature gating to document the dependencies?

**Comment by knight42** [comment]
@nathanross Yes, and not to download and compile redundant crates. After all, I don't want to pay for what I don't need.

**Comment by nathanross** [comment]
ohhhh.... neat

**Pull request merged**
