### PR TITLE
include io-blksize parameter

### LINKED ISSUE #2864: split: implement undocumented option ---io-blksize
GNU split has an undocumented command-line option `---io-blksize` (note three dashes, not two). For example:
```
$ split ---io-blksize=1 infile
```
I don't know what the option does, but the GNU test suite uses this option in some places so we'll need to at least accept it in order for the test suite to pass.

### PR DESCRIPTION
**Pull request by DevSabb**
Closes #2864

### CODE REVIEW

**Review by tertsdiepraam — APPROVED** [review]
Nice! Thanks for adding tests for this too!

**Comment by DevSabb** [comment]
Is there something I need to do to close this pull request?

**Comment by tertsdiepraam** [comment]
No, I should've merged this 8 days ago :)

**Comment by alextibbles** [comment]
FYI I noticed this test failure today:

```
failures:

---- test_split::test_split_number_with_io_blksize stdout ----
current_directory_resolved: 
run: /home/alex/code/rust/coreutils/target/debug/coreutils split -n 5 asciilowercase.txt ---io-blksize 1024
open: /tmp/user/1000/.tmpM2oq8D/xaa
open: /tmp/user/1000/.tmpM2oq8D/xab
open: /tmp/user/1000/.tmpM2oq8D/xac
open: /tmp/user/1000/.tmpM2oq8D/xad
open: /tmp/user/1000/.tmpM2oq8D/xae
thread 'test_split::test_split_number_with_io_blksize' panicked at 'assertion failed: `(left == right)`
  left: `"uvwxyz\n"`,
 right: `"uvwxyz"`', /home/alex/code/rust/coreutils/tests/by-util/test_split.rs:466:5
```
Running my system split manually it looks like the behavior is correct, so the expectation should be updated to include the \n.

**Comment by DevSabb** [comment]
@alextibbles Good catch. Looks like one of the previous commit changes lost during this merge.

@tertsdiepraam Should I just repush the changes as a commit?

**Comment by DevSabb** [comment]
@alextibbles Good catch. I have to update a newly introduced test case to incorporate some changes between the commit and the merge.

**Comment by DevSabb** [comment]
I created a pull request #3140. Please take a look.

**Pull request merged**
