### PR TITLE
change tempfile crate version to 3

### PR DESCRIPTION
**Pull request by OHNONOTAMOTH**

### CODE REVIEW

**Comment by sylvestre** [comment]
Please merge the 4 commits into one and give a better commit name :)

**Comment by OHNONOTAMOTH** [comment]
> Please merge the 4 commits into one and give a better commit name :)

id how to do that

**Comment by sylvestre** [comment]
please investigate a bit more before asking questions ;)

**Comment by OHNONOTAMOTH** [comment]
Do I have to close the pull request to do that?

**Comment by sylvestre** [comment]
no

**Comment by OHNONOTAMOTH** [comment]
sorry im a noob

**Comment by OHNONOTAMOTH** [comment]
I changed the title, idk how to merge the commits

**Comment by sylvestre** [comment]
> sorry im a noob

we all have been beginners ;)
my advice is that you spend time looking at docs.

**Pull request merged**
