### PR TITLE
test(expand): Add some tests for expand

### PR DESCRIPTION
**Pull request by sylvestre**

### CODE REVIEW

**Comment by sylvestre** [comment]
> I want to look at this a bit more ... I'd like to be more explicit about the contents of the fixtures.

What do you mean?

> Also, needs a `cargo make format`.

oh, bizarre, done

**Comment by rivy** [comment]
I just wanted to think about how to best signal the required white space in the fixture files.
There are a couple of comments, but I'm not sure what the files need to contain (or do contain) from just the visible code/comments.

I was having some initial thoughts about adding some more detailed commentary.

**Comment by sylvestre** [comment]
> I just wanted to think about how to best signal the required white space in the fixture files.
> There are a couple of comments, but I'm not sure what the files need to contain (or do contain) from just the visible code/comments.
> 
> I was having some initial thoughts about adding some more detailed commentary.

OK, done! is that ok with you?

**Comment by sylvestre** [comment]
the ci is green, it is a ci issue, not with this patch

**Comment by sylvestre** [comment]
Auto merge my PR, it is just tests and we didn't have any before

**Comment by rivy** [comment]
I added some additional commentary, emphasizing signficant whitespace, and squashed it into the fix.

**Pull request merged**
