### PR TITLE
install: support of `-d dir/.` to match GNU's

### PR DESCRIPTION
**Pull request by sylvestre**

### CODE REVIEW

**Comment by tertsdiepraam** [comment]
There are probably more cases like this throughout GNU, so maybe we should put this in a function in `uucore`? We could for instance make a wrapper around `create_dir` that has this behaviour.

**Comment by sylvestre** [comment]
Great idea, I will do that :)
Thanks

**Comment by sylvestre** [comment]
From a previous run:

`Warning: Congrats! The gnu test tests/install/d-slashdot is no longer failing!`

**Comment by sylvestre** [comment]
Still green Warning: Congrats! The gnu test tests/install/d-slashdot is no longer failing!

**Review by jfinkels — APPROVED** [review]

**Pull request merged**
