### PR TITLE
touch: Implement -d now

### PR DESCRIPTION
**Pull request by hbina**
And a test for it.

Closes: https://github.com/uutils/coreutils/issues/3964

Signed-off-by: Hanif Bin Ariffin <hanif.ariffin.4326@gmail.com>

### CODE REVIEW

**Comment by sylvestre** [comment]
I think the test could be improved to verify that the date is indeed correctly set

Also, `touch -d yesterday`, `touch -d "next Thursday" foo`, etc also work :)

**Comment by hbina** [comment]
The GNU manual describes their date input formats here: https://www.gnu.org/software/coreutils/manual/html_node/Date-input-formats.html

Apparently, various (if not all) GNU utils accept these format. Is there prior art for this thing in other tools here?

**Comment by tertsdiepraam** [comment]
There is _some_ prior art but not much, because I think everyone's a bit daunted by the task. There's this note in `touch.rs`:
```
// This isn't actually compatible with GNU touch, but there doesn't seem to
    // be any simple specification for what format this parameter allows and I'm
    // not about to implement GNU parse_datetime.
    // http://git.savannah.gnu.org/gitweb/?p=gnulib.git;a=blob_plain;f=lib/parse-datetime.y
```

There's also `uucore/src/parser/parse_time.rs` with some function for parsing time, which also comes nowhere close to `parse_datetime` from GNU.

**Comment by hbina** [comment]
Apparently there's a crate for something _like_ this already: https://crates.io/crates/interim and its predecessor https://github.com/stevedonovan/chrono-english.

I am currently looking at the GNU docs mentioned and the implementation of the crates and see if they are okay.

**Comment by coffee-is-power** [comment]
> Apparently there's a crate for something _like_ this already: https://crates.io/crates/interim and its predecessor https://github.com/stevedonovan/chrono-english.
> 
> I am currently looking at the GNU docs mentioned and the implementation of the crates and see if they are okay.

We definitely don't want to implement parse datetime in rust so that's the best option, we can make a fork, modify it and  use it by linking it on cargo.toml if any feature is missing or if we're not happy about something

**Comment by hbina** [comment]
I think implementing a bare bone `parse_datetime` is reasonable. Tokenization and dates can be done using `nom` and `chrono`/`time` respectively. Do you have a preference for which date crate to use? I did some basic grep and we seems to use both `time` and `chrono`. Should I create a new issue to expand `src/uucore/src/lib/parser/parse_time.rs`?

**Comment by tertsdiepraam** [comment]
`chrono` was unmaintained for a while, which is why we started using `time` more, but new maintainers have now continued development. You can use whichever you find more convenient.

**Comment by sylvestre** [comment]
@hbina any plan for this PR ? :)

**Comment by sylvestre** [comment]
no activity, closing. please reopen when ready

**Pull request closed without merging**
