### PR TITLE
mv: log proper error message when permission error occurs

### PR DESCRIPTION
**Pull request by ycd**
Closes: #2255

### CODE REVIEW

**Comment by sylvestre** [comment]
According to the log, we are still getting:
```
2021-05-24T19:43:42.2295532Z -mv: cannot move 'no-write/dir' to './dir': Permission denied
2021-05-24T19:43:42.2296430Z +mv: error: cannot move ‘no-write/dir’ to ‘./dir’: Permission denied

```

**Comment by tertsdiepraam** [comment]
@sylvestre I think that's because our `show_error!` macro adds `error:` automatically. Changing that should probably be done in another PR that then also fixes the relevant tests for all other utils that use that macro.

**Comment by sylvestre** [comment]
i think we should have show_error and show_error_explicit or something like that.

Trying
```
diff --git a/src/uucore/src/lib/macros.rs b/src/uucore/src/lib/macros.rs
index 637e91f8..a452384d 100644
--- a/src/uucore/src/lib/macros.rs
+++ b/src/uucore/src/lib/macros.rs
@@ -25,7 +25,7 @@ macro_rules! executable(
 #[macro_export]
 macro_rules! show_error(
     ($($args:tt)+) => ({
-        eprint!("{}: error: ", executable!());
+        eprint!("{}: ", executable!());
         eprintln!($($args)+);
     })
 );

```

Caused the number of pass tests from 138 to 113

**Comment by sylvestre** [comment]
@ycd could you please take care of that? thanks

**Comment by ycd** [comment]
@tertsdiepraam sure, if that's okay i can definitely do that.

**Comment by tertsdiepraam** [comment]
Of course! The current usage of these macros is actually very inconsistent right now. There is `show_info`, `show_warning` and `show_error`, but `show_info` is only used for showing errors as far as I can see, for example (output from `ripgrep`):
```
uu/nohup/src/nohup.rs
125:            show_info!("ignoring input and appending output to '{}'", NOHUP_OUT);
131:                    show_info!("failed to open '{}': {}", NOHUP_OUT, e1);
146:                    show_info!("ignoring input and appending output to '{}'", homeout_str);
150:                    show_info!("failed to open '{}': {}", NOHUP_OUT, e1);
151:                    show_info!("failed to open '{}': {}", homeout_str, e2);
```
Also `show_error_custom_description` is only used to specify paths:
```
uu/head/src/head.rs
431:                                show_error_custom_description!(prefix, "No such file or directory");
434:                                show_error_custom_description!(prefix, "Permission denied");
437:                                show_error_custom_description!(prefix, "{}", err);
460:            show_error_custom_description!(prefix, "Input/output error");

uu/du/src/du.rs
311:                            show_error_custom_description!(description, "{}", error_message)

uu/wc/src/wc.rs
271:            show_error_custom_description!(path, "Is a directory");
274:            show_error_custom_description!(path, "No such file or directory");
```

So, if you're going to refactor this anyway, I would suggest the following:
* Remove `show_info`, `show_warning`, `show_error_custom_description` and use `show_error` instead
* Remove the `error:` from `show_error`

This keeps the `crash` and `show_usage_error` intact and feels the most intuitive to me.

**Comment by ycd** [comment]
@tertsdiepraam Huh! Looks like we need a general refactor rather than just refactoring `show_error` and i completely support that. 

But IMO having `error:` is not that bad(Is it?), it is just inconsistent. 

As you already pointed out, that `show_info` is only used for showing errors and i can't see a legitimate reason to keep them both. 

I think we should go with `show_error` but i'm not sure should we delete the `error:` prefix on `show_error` WDYT?

**Comment by sylvestre** [comment]
I think getting closer to the GNU testsuite results is key for the adoption of this project.
So, we should probably follow GNU's output

**Pull request merged**
