### PR TITLE
head: add abstractions for "all but last n lines"

### PR DESCRIPTION
**Pull request by jfinkels**
This pull request adds some abstractions to simplify the `rbuf_but_last_n_lines()` function, which implements the "take all but the last `n` lines" functionality of the `head` program. This commit adds

- `RingBuffer`, a fixed-size ring buffer,
- `ZLines`, an iterator over zero-terminated "lines",
- `TakeAllBut`, an iterator over all but the last `n` elements of an iterator.

These three together make the implementation of `rbuf_but_last_n_lines()` concise.

I also adding a missing test case, for using `-z` with `-n -NUM` (as opposed to `-n NUM`).

Future pull requests could improve the following areas:

- Improving the space- and time-efficiency of scanning for lines.
- Refactoring common code from `head` and `tail`. For example, this pull request *copies* and adapts the `RingBuffer` code from `tail/src/ringbuffer.rs` into `head/src/ringbuffer.rs`. (If someone could provide me with instructions for how to put this common module into the `uucore` crate, I could do that in this pull request, I just wasn't sure how to do it.) And the `ZLines` iterator will be useful for several other coreutils commands.

### CODE REVIEW

**Comment by jhscheer** [comment]
> * Refactoring common code from `head` and `tail`. 
> For example, this pull request _copies_ and adapts the `RingBuffer` code from `tail/src/ringbuffer.rs` into `head/src/ringbuffer.rs`. 
> (If someone could provide me with instructions for how to put this common module into the `uucore` crate, I could do that in this pull request, I just wasn't sure how to do it.) 
> And the `ZLines` iterator will be useful for several other coreutils commands.

I just did something similar myself (#2199).
1.  Move `head/ringbuffer.rs` to (for example) `uucore/src/lib/features/ringbuffer.rs`. 
2. Add the new feature to `head/Cargo.toml`, add feature and dependencies to `uucore/Cargo.toml`. 
3. Add `use uucore::ringbuffer` to `head.rs` and fix stuff until everything works.
2. Move/Merge `tail/ringbuffer.rs` into `uucore/ringbuffer.rs`.
3. Repeat 2. and 3. for `tail.rs`.

**Comment by jfinkels** [comment]
Thank you, I will try that and comment again when it is done.

**Comment by jfinkels** [comment]
I have added a commit that refactors the `ringbuffer.rs` file from `head/src/ringbuffer.rs` and `tail/src/ringbuffer.rs` to the `uucore` crate. If you confirm I have done it correctly, then I will resolve the merge conflicts, rebase, and squash commits.

**Comment by sylvestre** [comment]
could you please rebase the patch ? I will have a look later :)

**Comment by jfinkels** [comment]
It is updated.

**Comment by sylvestre** [comment]
terrific, thanks

**Pull request merged**
