### PR TITLE
Bump MSRV to 1.43.1

### PR DESCRIPTION
**Pull request by tertsdiepraam**
Closes https://github.com/uutils/coreutils/issues/2282

I hope I did not miss any important steps but based on the previous version bump and checking where 1.40 was mentioned, I think this is all that needs to change.

### CODE REVIEW

**Comment by sylvestre** [comment]
Please update:
https://github.com/uutils/coreutils/blob/master/Cargo.toml#L346-L347

**Comment by miDeb** [comment]
I left some comments around in the code with notes about what could be improved with a higher MSRV, but I could make those changes in a different PR.

**Comment by tertsdiepraam** [comment]
@sylvestre I updated the tempfile dependency. Is that what you meant?

**Comment by sylvestre** [comment]
yeah, exactly, thanks :)

**Pull request merged**
