### PR TITLE
Refactor/code quality

### PR DESCRIPTION
**Pull request by danieleades**
Addresses a number of code quality lints.

I haven't added any additional lints/checks to *enforce* these changes. Is that something that you want?

### CODE REVIEW

**Comment by sylvestre** [comment]
I like most of the change. thanks :)
However, I am not convinced by the match => if
In general, I prefer the match 

Could you please remove this commit from the pr?
thanks

**Comment by danieleades** [comment]
> I like most of the change. thanks :) However, I am not convinced by the match => if In general, I prefer the match
> 
> Could you please remove this commit from the pr? thanks

sure thing. I've removed that commit.

**Comment by tertsdiepraam** [comment]
Hey! Great job! This is getting pretty big, let's split it here and put further changes in another PR

**Comment by danieleades** [comment]
> Hey! Great job! This is getting pretty big, let's split it here and put further changes in another PR. Oh you we're faster than me :)

sure. happy to slice and dice this however you like! Will move further changes to a stacked PR

**Review by tertsdiepraam — APPROVED** [review]
Looks all good to me!

> I haven't added any additional lints/checks to enforce these changes. Is that something that you want?

Possibly, though probably not for *all* of these changes. For example, always using `Default` might hurt readability in some cases, because it's less explicit and requires contributors to know the default value for a lot of (possibly obscure) types. I'm fine with sticking to `clippy`'s default settings for now.

**Comment by danieleades** [comment]
CI failures...
I don't *think* they're related to this PR. how stable is the CI normally?

**Comment by tertsdiepraam** [comment]
It's pretty stable these days, but it fails every once in a while. It seems unrelated indeed. I'll rerun the CI

**Comment by danieleades** [comment]
> It's pretty stable these days, but it fails every once in a while. It seems unrelated indeed. I'll rerun the CI

loads of failures in GnuTests job. Still think it's unrelated to this PR? I can split the commits into separate PRs if it helps?

**Comment by tertsdiepraam** [comment]
> loads of failures in GnuTests job

That's to be expected. This tests against all GNU tests and we are not 100% compatible. The job will fail if there are any tests that pass on `main` but not on the PR.

**Comment by tertsdiepraam** [comment]
I've created an issue for the test that failed: https://github.com/uutils/coreutils/issues/2969

**Comment by danieleades** [comment]
@tertsdiepraam
finished! that's some epic CI

**Comment by sylvestre** [comment]
what tool did you use for that btw?

**Comment by danieleades** [comment]
> what tool did you use for that btw?

it was about 5% manual effort, and about 95% `clippy`

**Comment by sylvestre** [comment]
I guess it is with inactivated options of clippy as we have it in the CI?
Could you please update the CI to enable them?
thanks

**Pull request merged**
