### PR TITLE
hashsum: switch from getopts to clap

### PR DESCRIPTION
**Pull request by Arcterus**
Additionally, slightly refactor.  This commit will be the first of a series of commits refactoring (at the very least) `hashsum`.

This can be merged now, but I plan to add more commits in a few days.

### CODE REVIEW

**Comment by Arcterus** [comment]
Also note that non-UTF-8 file paths should work now.

**Comment by sylvestre** [comment]
Could you please rustfmt the changes ? 

In some others programs, we used OPT_OPTIONX to avoid duplication of the strings
ex: https://github.com/uutils/coreutils/blob/master/src/uu/df/src/df.rs#L92-L98
I don't have a strong opinion here but we should be consistent. WDYT ?

**Comment by Arcterus** [comment]
This commit wasn't really meant to be much of a refactor, it's more or less a direct translation with some minor changes (like reducing the arity of the `hashsum` function...).  I was planning to add those constants in later commits.

**Comment by Arcterus** [comment]
The failure seems to be spurious.  It just couldn't download `lazy_static`.

**Pull request merged**
