### PR TITLE
Add non-UTF-8 support to utils

### PR DESCRIPTION
**Pull request by Arcterus**
### DO NOT MERGE YET!!!

I am planning on rewriting all the utils to have at least basic support for non-UTF-8 arguments and such, addressing #203, #554, #699, #1006, and #1050 (there may be more, but this is what I found after a quick check).  This pull request is to keep track of my progress.

Generally, adding support entails switching from `getopts` to `clap` and converting `String`-based arguments to `OsString`.  Some utilities require more in-depth changes as they either mess with the arguments or retrieve OS-specific data (which we currently convert to `String`s).

If anyone is interesting in helping, you should probably start from the top as I am pretty much starting from the end of the list.

## Progress (some utils are likely not marked):

* [ ] arch
* [ ] base32
* [ ] base64
* [ ] basename
* [ ] cat
* [ ] chgrp
* [ ] chmod
* [ ] chown
* [ ] chroot
* [ ] cksum
* [ ] comm
* [ ] cp
* [ ] cut
* [ ] dircolors
* [ ] dirname
* [ ] du
* [ ] echo
* [ ] env
* [ ] expand
* [ ] expr
* [ ] factor
* [ ] false
* [ ] fmt
* [ ] fold
* [ ] groups
* [ ] hashsum
* [ ] head
* [ ] hostid
* [ ] hostname
* [ ] id
* [ ] install
* [ ] kill
* [ ] link
* [ ] ln
* [ ] logname
* [ ] ls
* [ ] mkdir
* [ ] mkfifo
* [ ] mknod
* [ ] mktemp
* [ ] mv
* [ ] more (in progress, needs lots of work)
* [ ] nice
* [ ] nl
* [ ] nohup
* [ ] nproc
* [ ] od (almost complete, `--strings` and 128-bit datatypes are missing)
* [ ] paste
* [ ] pathchk
* [ ] pinky
* [ ] printenv
* [ ] printf
* [ ] ptx
* [ ] pwd
* [ ] readlink
* [ ] realpath
* [ ] relpath
* [x] rm (although `Path::display()` probably uses `to_string_lossy()` behind-the-scenes)
* [ ] rmdir
* [ ] seq
* [ ] shred
* [ ] shuf
* [x] sleep
* [ ] sort
* [ ] split
* [ ] stat
* [ ] stdbuf
* [ ] sum
* [ ] sync
* [ ] tac
* [ ] tail
* [ ] tee
* [ ] test
* [ ] timeout
* [ ] touch
* [ ] tr
* [ ] true
* [ ] truncate
* [ ] tsort
* [ ] tty
* [ ] uname
* [ ] unexpand
* [ ] uniq
* [ ] unlink
* [ ] uptime
* [ ] users
* [x] uutils
* [ ] wc
* [ ] who
* [x] whoami (not sure if username in `/etc/passwd` is ever non-UTF-8?)
* [x] yes

### CODE REVIEW

**Comment by Phlosioneer** [comment]
To make helping easier, there should be some basic tests included to generate non-UTF-8 filenames and sample arguments. At the very least, a file or Gist with a bunch of non-UTF-8 names that can be copied and pasted would help.

**Comment by Phlosioneer** [comment]
Found a good such file: http://www.cl.cam.ac.uk/~mgk25/ucs/examples/UTF-8-test.txt

**Comment by Phlosioneer** [comment]
I'm unable to compile your patch's yes crate. And, while trying to implement a non-UTF-8 echo, the clap crate seems to be unable to handle non-utf-8 inputs; it crashes at runtime in App::get_matches_from.

**Comment by Arcterus** [comment]
Yes, I was planning on adding a test file later.  Thanks for the link. :)

What platform are you on?  It seems `clap` may not support Windows according to [this](https://kbknapp.github.io/clap-rs/clap/enum.AppSettings.html), although perhaps I am missing something.  If it doesn't, we may have to switch to some other argument parser.

What error are you getting for `yes`?  I probably forgot to change something while updating it to use `OsString`/`OsStr`.

**Comment by Phlosioneer** [comment]
Windows 10. I also had compile errors for rm.

For yes, I'm getting an error at the line byte_print!() in exec(). It seems to dislike `&output`, rather than just `output`, though I'm not sure.

**Comment by Arcterus** [comment]
I'll try to figure something out for Windows.  In the meantime, does `yes` work if you change `&output` to `&output[..]`?

I'll take a look at `rm` (I probably messed up on something similar...).

**Comment by shutefan** [comment]
@Arcterus Just a suggestion: why not create a separate issue and PR for each util, maybe associated with a milestone? That way you could still keep track of the progress but visibility of this topic would be greater and you could integrate into master more often, thus avoiding rebases if things change there...

**Comment by Arcterus** [comment]
@shutefan I think I'm going to do that.  The original plan was to just do this within a week or two, but it seems that idea fell through.  I'll start making separate PRs once finals are over.

**Comment by Arcterus** [comment]
So I'm gonna close this in favor of updating everything in a series of steps.  The first step will be to convert everything that uses `getopts` to use `clap`, which will then be followed by switching the utils to use `Vec<OsString>` instead of `Vec<String>` as the arguments.  After this, each util will need to updated to make use of `OsString` rather than `String`.

**Pull request closed without merging**
