### PR TITLE
Fix clippy::implicit_clone

### PR DESCRIPTION
**Pull request by Statheres**
Enabled clippy::implicit_clone checkes and fixed all warnings

### CODE REVIEW

**Comment by sylvestre** [comment]
Thanks!

for other curious like me
https://rust-lang.github.io/rust-clippy/master/#/implicit_clone

**Comment by Statheres** [comment]
Oh, sorry!
Will add the link next time :)

**Comment by sylvestre** [comment]
oh, don't be sorry :)

**Comment by cakebaker** [comment]
Thanks for your PR!

**Pull request merged**
