### PR TITLE
Implement chgrp

### LINKED ISSUE #224: Implement chgrp
Attempting to implement `chgrp(1)`

### PR DESCRIPTION
**Pull request by knight42**
Fix #224, close #802

### CODE REVIEW

**Comment by knight42** [comment]
@Arcterus could you add our team to your appveyor, so that I can cancel some useless tests?

**Comment by Arcterus** [comment]
I think I've updated it, but I'm not totally sure (not that familiar with AppVeyor).  Let me know if it works.

**Comment by knight42** [comment]
@Arcterus It seems that the changes didn't work for me. I still cannot interrupt the test building in appveyor. Have you granted us the correct permission?

**Comment by Arcterus** [comment]
@knight42 Alright try it now.

**Pull request merged**
