### PR TITLE
#3505 touch date parsing

### PR DESCRIPTION
**Pull request by dgunay**
Taking a stab at #3505

### CODE REVIEW

**Comment by dgunay** [comment]
OK. This is a real tricky one, it appears the `time` crate doesn't have something like this.

**Comment by tertsdiepraam** [comment]
Yeah it's really tricky. I'd advise to do this incrementally. I think we first need to figure out what all the formats are that GNU supports and then we can tick them of one by one, possibly in separate PRs.

**Comment by sylvestre** [comment]
And/or fill a feature request on the time crate

**Comment by sylvestre** [comment]
(and before, investigate if there isn't a crate doing it already)

**Comment by sylvestre** [comment]
Closing for now, please reopen when it is ready to be reviewed

**Pull request closed without merging**
