### PR TITLE
Implement `pr` (resurrection of the resurrected PR)

### PR DESCRIPTION
**Pull request by tertsdiepraam**
A re-resurrection of https://github.com/uutils/coreutils/pull/1918 by @MaxSem and @tilakpatidar. Let's get this merged after 2.5 years :)

I've brought it up to date with recent changes, fixed clippy lints and cleaned some of the code up. I think we can create a good first issue to move it to `clap` once this is merged.

### CODE REVIEW

**Comment by tertsdiepraam** [comment]
Marking as draft because code coverage should be improved before merging.

**Comment by sylvestre** [comment]
Expected: the gnu tests aren't running correctly  but not a big deal:
```

2021-05-29T18:48:23.8713639Z 
2021-05-29T18:48:23.8714036Z FAIL: tests/pr/pr-tests
2021-05-29T18:48:23.8714334Z =======================
2021-05-29T18:48:23.8714516Z 
2021-05-29T18:48:23.8714753Z 1b...
2021-05-29T18:48:23.8715137Z pr: test 1b failed: exit status mismatch:  expected 0, got 1
2021-05-29T18:48:23.8715532Z 1b.r...
2021-05-29T18:48:23.8715925Z pr: test 1b.r failed: exit status mismatch:  expected 0, got 1
2021-05-29T18:48:23.8716328Z 1b.p...
[...]
```

**Comment by tertsdiepraam** [comment]
It seemed to be missing in the GNUMakefile, which should be fixed now, so hopefully it works now.

**Comment by tertsdiepraam** [comment]
Test coverage is not going to be great, but a lot will be fixed when we move this to `clap`. Most options are tested. I tried adding some tests, but got slightly different results than GNU, so it might be better to just open issues instead of making incorrect tests.

**Comment by sylvestre** [comment]
Test coverage is rarely (never?) perfect ;)

**Comment by sylvestre** [comment]
With 64 commits, I think it is time to land it :)

**Pull request merged**
