### PR TITLE
wc: add lines() method for iterating over lines

### PR DESCRIPTION
**Pull request by jfinkels**
This pull request adds the `WordCountable::lines()` method that returns an iterator over lines of a file-like object. This mirrors the
`std::io::BufRead::lines()` method, with some minor differences due to the particular use case of `wc`. This eliminates the need for the `WordCountable::get_buffered()` method, since the `WordCountable::lines()` implementation handles creating the appropriate `BufferedReader`.

This commit also creates a new module, `countable.rs`, to contain the `WordCountable` trait and the new `Lines` struct returned by `lines()`.

### CODE REVIEW

**Comment by sylvestre** [comment]
Would it be possible to add some tests to cover some untested cases ?

**Comment by jfinkels** [comment]
Yes, I'd be happy to. Is there anything specific you'd like to see? If you're just looking for more tests in general, I can add some tests for other boundary cases, like empty lines, long lines, long files, etc.

**Comment by jfinkels** [comment]
I added a few tests for reading from a file. There's a slight issue in the output of `wc` when reporting two or more numbers for a file. I've created issue #2173 for that, and left a comment referencing it inside each test I added here.

**Comment by sylvestre** [comment]
thanks :)

**Pull request merged**
