### PR TITLE
Group OPT_ARGUMENTS into mods

### PR DESCRIPTION
**Pull request by FelipeLema**
Group `OPT_SOME_CLI_OPTION` into `options::SOME_CLI_OPTION`

This pull request does not intend to end all re-ordering of options, but rather establish a norm to follow in all tools/commands.

I'm grouping several related options into sub-mods. They can be improved by pointing them out here, in this PR, or later in the future

### CODE REVIEW

**Comment by sylvestre** [comment]
wahou, I love it :)
bravo

Let me know if you want me to merge now or not ?

**Comment by FelipeLema** [comment]
@sylvestre let me do some more files… will @ you when it's ready

**Comment by sylvestre** [comment]
oh, I missed the draft, sorry :)

**Comment by FelipeLema** [comment]
@sylvestre ready now for review

**Comment by sylvestre** [comment]
This is just great, many thanks!

**Pull request merged**
