### PR TITLE
split: catch broken pipe error for round robin strategy

### LINKED ISSUE #5191: split: reading from STDIN is broken with some options
It works when data piped from stdin is small, but fails if it is large  or something continuous like `yes`  
For example, 
This works:
`ls -alrt | wc -l`
39
`ls -alrt | timeout 5 split --filter='head -c1 >$FILE.n' -n r/1 -`

This fails:
`wc -l Cargo.lock`
3617 Cargo.lock
`cat Cargo.lock | timeout 5 split --filter='head -c1 >$FILE.n' -n r/1 -`
split: Broken pipe

`yes | timeout 5 split --filter='head -c1 >$FILE.n' -n r/1 -`
split: Broken pipe

### PR DESCRIPTION
**Pull request by granquet**
The broken pipe error is not handled in the case of the round robin strategy (typically used with --filter).

Align to the other strategies to silence that error in that use case too.

fixes #5191

### CODE REVIEW

**Comment by cakebaker** [comment]
Can you please add a test so we won't regress in the future? And there is also a clippy warning. Thanks :)

**Comment by granquet** [comment]
I've spent some time trying to write a test for this, it's not as easy as it seems in "pure rust".
I'll get back to you when I get something that works.

**Comment by granquet** [comment]
you actually don't need to create a pipe and all of that jazz to reproduce the issue as stated in issue #5191 
using --filter and -r on a big file also provokes the issue on its own.

So this simplifies the test (a lot!).

**Comment by cakebaker** [comment]
Thanks :)

**Pull request merged**
