### PR TITLE
tsort: returns error when input is dir - same as GNU tsort

### PR DESCRIPTION
**Pull request by SaHHiiLL**
fix: #5853

### CODE REVIEW

**Comment by cakebaker** [comment]
Can you please add a test so we don't regress in the future?

**Comment by SaHHiiLL** [comment]
sure!

**Comment by SaHHiiLL** [comment]
lmk if there's something else I can put instead of `.` for the test

**Comment by cakebaker** [comment]
I think `.` is fine.

If you want to specify a concrete directory name, you can use something like:
```
let (at, mut ucmd) = at_and_ucmd!();
at.mkdir("dirname");
```
And then use `ucmd` instead of `new_ucmd!`.

**Comment by SaHHiiLL** [comment]
Alright, That seems to work. Thanks for the help!!

**Review by cakebaker — APPROVED** [review]

**Comment by cakebaker** [comment]
Thanks for your PR :)

**Pull request merged**
