### PR TITLE
ls: correct output width

### PR DESCRIPTION
**Pull request by miDeb**
- Correct fallbacks (command line argument -> termsize -> environment variable -> 80)
- Print a single line when the width is 0

### CODE REVIEW

**Comment by sylvestre** [comment]
image
interesting results ;)

**Comment by miDeb** [comment]
Nice, this actually revealed another bug!

**Comment by sylvestre** [comment]
`Congrats! The gnu test tests/ls/x-option is now passing!`

Well done :)

**Comment by miDeb** [comment]
fyi: this also made `tests/chgrp/basic` pass when it was merged (in combination with https://github.com/uutils/coreutils/pull/2564)

**Pull request merged**
