### PR TITLE
kill: print signals vertically when using --list flag

### PR DESCRIPTION
**Pull request by m-haisham**
> Environment: Ubuntu 20.04, uutils main branch (git commit https://github.com/uutils/coreutils/commit/415de28fedcd66ae3482f22d4ba274fe77c9d3d8), GNU coreutils version 9.5.3-8f39 (from git commit https://github.com/coreutils/coreutils/commit/8f3989d586a88d182700050b435d2f6c393ec27b).

See #6197 for more details.

### CODE REVIEW

**Review by BenWiederhake — APPROVED** [review]
Hah! Short and sweet :D

**Comment by m-haisham** [comment]
Accidentally pushed table formatting code to this branch, I've rolled it back.

**Review by BenWiederhake — APPROVED** [review]
Looks good.

**Comment by m-haisham** [comment]
Failed check does not seem to be related to this tool. @BenWiederhake

**Comment by BenWiederhake** [comment]
Thank you!

**Comment by sylvestre** [comment]
it would have been nice to have a test to make sure we don't regress in the future

**Comment by BenWiederhake** [comment]
You're right!

**Pull request merged**
