### PR TITLE
hostname: refactor a bit

### PR DESCRIPTION
**Pull request by Arcterus**

### CODE REVIEW

**Comment by Arcterus** [comment]
Maybe I should just disable Codecov entirely until the embedding interface is done... lol

**Comment by Arcterus** [comment]
@mpkh as far as I can tell, the failures are from Codecov, so they can be ignored if the code seems fine.  If Codecov keeps failing things like this I may disable it until it provides accurate results.

**Comment by mpkh** [comment]
ah I though you've fixed those problems by codecov config

**Comment by Arcterus** [comment]
I thought so too but apparently it’s still not working.

**Pull request merged**
