### PR TITLE
ls,more,csplit,sort,od,dd: fix clippy complaints

### PR DESCRIPTION
**Pull request by jfinkels**
These were causing CI failures

### CODE REVIEW

**Comment by sylvestre** [comment]
Many jobs are failing, could you please fix that? thanks

**Comment by jfinkels** [comment]
I have updated it, let's see if they are fixed now.

**Comment by sylvestre** [comment]
Looks much better!
Just these:
```

error: only a `panic!` in `if`-then statement
  --> src\uu\dd\src\parseargs\unit_tests.rs:38:5
   |
38 | /     if !succeeded.is_empty() {
39 | |         panic!(
40 | |             "The following flags did not panic as expected: {:?}",
41 | |             succeeded
42 | |         );
43 | |     }
   | |_____^
   |
   = note: `-D clippy::if-then-panic` implied by `-D warnings`
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#if_then_panic
help: try
   |
38 ~     assert!(succeeded.is_empty(), "The following flags did not panic as expected: {:?}",
39 +             succeeded);
   |

error: only a `panic!` in `if`-then statement
  --> src\uu\dd\src\parseargs\unit_tests.rs:67:5
   |
67 | /     if !succeeded.is_empty() {
68 | |         panic!(
69 | |             "The following flags did not panic as expected: {:?}",
70 | |             succeeded
71 | |         );
72 | |     }
   | |_____^
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#if_then_panic
help: try
   |
67 ~     assert!(succeeded.is_empty(), "The following flags did not panic as expected: {:?}",
68 +             succeeded);
   |
```

**Comment by jfinkels** [comment]
Okay, I updated `dd`, let's try again. I'm not sure why clippy is only reporting one of these issues at a time.

**Comment by sylvestre** [comment]
thanks :)

**Pull request merged**
