### PR TITLE
Run the release builds and store the size

### PR DESCRIPTION
**Pull request by sylvestre**
The goal is to use https://github.com/uutils/coreutils-tracking to graph the evolution

### CODE REVIEW

**Review by tertsdiepraam — APPROVED** [review]

**Comment by tertsdiepraam** [comment]
This might be kinda difficult to graph since the sizes probably vary a lot, but we should definitely try nonetheless

**Comment by sylvestre** [comment]
@tertsdiepraam 
Surprisingly stable: https://raw.githubusercontent.com/uutils/coreutils-tracking/main/size-results.png
;)

**Comment by sylvestre** [comment]
I guess the last increase is clap 3

**Comment by tertsdiepraam** [comment]
I meant vary between the utils. It'd be interesting to see the differences between them as well, but this is already great!

**Comment by sylvestre** [comment]
oh, sure :)

For now, I see this graph as a way to help with the rust & big changes (ex: clap 3). Not individual binaries 
but maybe could upgrade the CI to keep track of the size of each binary and warning if this becomes too big

**Pull request merged**
