### PR TITLE
Refactored ls.rs to fix cargo fmt

### PR DESCRIPTION
**Pull request by hbina**
`cargo fmt` have trouble formatting large `clap::Arg`.
This commit simply splits some stuff up so that the implementation details
can be formatted.

Signed-off-by: Hanif Bin Ariffin <hanif.ariffin.4326@gmail.com>

### CODE REVIEW

**Comment by sylvestre** [comment]
> cargo fmt have trouble formatting large clap::Arg.

Do you please explain this a bit more?
Are you sure it isn't this issue https://github.com/rust-lang/rustfmt/issues/3863 ?

Anyway, I don't think we should split the files just to make rustfmt happy?

@tertsdiepraam wdyt?

**Comment by tertsdiepraam** [comment]
I've seen in another PR that `rustfmt` fails if the help message is too long, so maybe we should just break those up. Example:
```rust
// From
.help("this message is a very very very long help message that doesn't fit")
// To
.help(
    "this message is a very very very \
    long help message that doesn't fit"
)
```
Most arguments in `ls` seem to have this already, but maybe they should be broken off earlier?

**Comment by tertsdiepraam** [comment]
I do actually think this should be broken up though, but I would wait for https://github.com/uutils/coreutils/pull/2414 to get merged and work from there.

**Comment by hbina** [comment]
Okay, I will try to refactor the constants first. Maybe by making `options` a file of its own. I am also thinking of grouping the flags and their help/after_help description together.

**Pull request closed without merging**
