### PR TITLE
install: implement copying from streams

### LINKED ISSUE #5080: `install`: Accept special files like `/dev/stdin`
GNU coreutils accepts special files like `/dev/stdin` without any issues, for e.g.:
```
$ echo 'foo' | install /dev/stdin test
```

That creates a file called `test` with `foo\n` as its contents, which isn't surprising.

However our coreutils fail with the same usage with this error:
```
install: cannot install '/dev/stdin' to 'test': Invalid input parameter
```

This issue doesn't effect `cp`, however it might effect other utils which haven't been tested.

### PR DESCRIPTION
**Pull request by DaringCuteSeal**
This PR resolves #5080 and #4387 by copying `cat`'s logic to copy from stream to a file.

However, I'm not sure about testing the cases for each stream type (other than standard input which I had provided in the test). I think it's better to be done in a future refactor where the logic for copying files (and streams) are combined into a single common utility.

### CODE REVIEW

**Comment by DaringCuteSeal** [comment]
yikes, seems like it's failing on Android. i'll look into that

**Comment by DaringCuteSeal** [comment]
okay fixed the unit test, the Android emulator seem to have `/dev/stdin` missing so I used `/dev/fd/0` instead. should be good now

**Comment by DaringCuteSeal** [comment]
oh yeah forgot to ask again. are there anything else i need to add or remove?

**Comment by sylvestre** [comment]
looks good to me :)
Could we refactor this code to share it with cat?

**Comment by DaringCuteSeal** [comment]
> Could we refactor this code to share it with cat?

Maybe we put splice.rs inside uucore. That good?

**Comment by DaringCuteSeal** [comment]
@sylvestre hey i'd love this to get merged since this bug is literally making my kernel disappear after every kernel upgrade :rofl: 

the pattern `install /dev/stdin` seem to be a lot more common than i thought--it's also part of Arch Linux's pacman hook for the Linux kernel packages.

I will look into putting squashing stream-copying functions into uucore--maybe also using it for `cp` since as of now it doesn't support copying special files (differs from GNU's coreutils).

**Comment by sylvestre** [comment]
Yeah
Sorry, I was waiting for this :) thanks

**Comment by sylvestre** [comment]
i guess you noticed that a few jobs are failing :)

**Comment by DaringCuteSeal** [comment]
> i guess you noticed that a few jobs are failing :)

sorry, dont have like 10 virtual machines yet to check my code :} are CI checks discouraged here?

**Comment by sylvestre** [comment]
nope, this is fine :)

**Comment by sylvestre** [comment]
once it will be ready to be merged, it would be nice to separate the uucore changes into a separate PR  to make the change more atomic
thanks :)

**Comment by DaringCuteSeal** [comment]
@sylvestre the newly made `splice` module depends on the `pipes` module from uucore, how do i add to its dependency??

**Comment by sylvestre** [comment]
in the feature - features = ["splice"] } ?

**Comment by DaringCuteSeal** [comment]
```
     Compiling uucore v0.0.28 (/home/runner/work/coreutils/coreutils/src/uucore)
  error[E0432]: unresolved imports `crate::pipes::splice`, `crate::pipes::splice_exact`
    --> src/uucore/src/lib/features/splice.rs:18:26
     |
  18 | use crate::pipes::{pipe, splice, splice_exact};
     |                          ^^^^^^  ^^^^^^^^^^^^ no `splice_exact` in `features::pipes`
     |                          |
     |                          no `splice` in `features::pipes`
     |
     = help: consider importing this module instead:
             crate::features::splice
  note: found an item that was configured out
    --> src/uucore/src/lib/features/pipes.rs:38:8
     |
  38 | pub fn splice(source: &impl AsFd, target: &impl AsFd, len: usize) -> Result<usize> {
     |        ^^^^^^
  note: the item is gated here
    --> src/uucore/src/lib/features/pipes.rs:37:1
     |
  37 | #[cfg(any(target_os = "linux", target_os = "android"))]
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  note: found an item that was configured out
    --> src/uucore/src/lib/features/pipes.rs:48:8
     |
  48 | pub fn splice_exact(source: &impl AsFd, target: &impl AsFd, len: usize) -> Result<()> {
     |        ^^^^^^^^^^^^
  note: the item is gated here
    --> src/uucore/src/lib/features/pipes.rs:47:1
     |
  47 | #[cfg(any(target_os = "linux", target_os = "android"))]
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  
  For more information about this error, try `rustc --explain E0432`.
```

**Comment by DaringCuteSeal** [comment]
nvm works now. my bad, i wrote unix instead of linux & android

**Comment by DaringCuteSeal** [comment]
i'm opening separate PRs i guess

**Comment by sylvestre** [comment]
yeah, it will help with the review, thanks :)

**Pull request closed without merging**
