### PR TITLE
parser: fix index out of bounds error

### LINKED ISSUE #4479: parse_glob function fuzzing fails quickly on `index out of bounds: the len is 4 but the index is 4`
With:
https://github.com/uutils/coreutils/pull/4389
$ cargo +nightly fuzz run fuzz_parse_glob -- -max_total_time=60 -detect_leaks=0 
fails quickly

```
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 1219054654
INFO: Loaded 1 modules   (128943 inline 8-bit counters): 128943 [0x559ad077c740, 0x559ad079beef),
INFO: Loaded 1 PC tables (128943 PCs): 128943 [0x559ad079bef0,0x559ad09939e0),
target/x86_64-unknown-linux-gnu/release/fuzz_parse_glob: Running 1 inputs 1 time(s) each.
Running: artifacts/fuzz_parse_glob/minimized-from-5de326e0e773a6510221e6c4316da011f688b224
thread '<unnamed>' panicked at 'index out of bounds: the len is 4 but the index is 4', /home/sylvestre/dev/debian/coreutils/src/uucore/src/lib/parser/parse_glob.rs:14:54
```

### PR DESCRIPTION
**Pull request by papparapa**
Fixes #4479 

This PR fixes index out of bounds in `parse_glob::fix_negation`.

### CODE REVIEW

**Comment by sylvestre** [comment]
Could you please add a test to make sure we don't regress in the future?

**Comment by sylvestre** [comment]
(thanks ;)

**Comment by tertsdiepraam** [comment]
Some comment explaining what's going on would also be nice!

**Comment by sylvestre** [comment]
I landed the fuzzers and rebuild on top of this PR and we are getting:
```
thread '<unnamed>' panicked at 'index out of bounds: the len is 11 but the index is 11', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/uucore-0.0.17/src/lib/parser/parse_glob.rs:14:54
```

**Comment by papparapa** [comment]
Added a comment and a test.

@sylvestre
> I landed the fuzzers and rebuild on top of this PR and we are getting:
> 
> ```
> thread '<unnamed>' panicked at 'index out of bounds: the len is 11 but the index is 11', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/uucore-0.0.17/src/lib/parser/parse_glob.rs:14:54
> ```

Did it use the old file in cargo registry?

**Comment by sylvestre** [comment]
yeah, i guess it was the issue
i saw that you are not using the workspace too  (i did it here too: https://github.com/uutils/coreutils/pull/4495 )
it is clearly fixed:
https://github.com/uutils/coreutils/actions/runs/4384176388/jobs/7675329815
Done 1439932 runs in 61 second(s)
bravo

**Pull request merged**
