### PR TITLE
refactor(df): use number_prefix like 'ls'

### PR DESCRIPTION
**Pull request by sylvestre**

### CODE REVIEW

**Comment by rivy** [comment]
I've made a couple of corrections (windows import issues, cosmetic display issue, build issue).

It now will build with `cargo build -pdf` (or `cargo make util df`).

The code still has an odd issue that I missed when I merged the initial `df` PR. It won't build under windows as an independent crate.

```shell
C:\...\coreutils> cd src\uu\df
C:\...\coreutils\src\uu\df> cargo build
   Compiling df v0.0.1 (C:\Users\Roy\OneDrive\Projects\rust\coreutils\src\uu\df)
error[E0308]: mismatched types
   --> src\uu\df\src/df.rs:616:36
    |
616 |         if INVALID_HANDLE_VALUE == find_handle {
    |                                    ^^^^^^^^^^^ expected enum `winapi::ctypes::c_void`, found enum `libc::c_void`
    |
    = note: expected raw pointer `*mut winapi::ctypes::c_void`
               found raw pointer `*mut libc::c_void`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0308`.
error: could not compile `df`.

To learn more, run the command again with --verbose.
```

I'm not currently sure how to fix it. (And it looks like `sync` has a similar problem.)

**Comment by sylvestre** [comment]
Yeah, agreed. I already create a new issue.
if we care about independent crates, we should have some CI task to verify this too

**Comment by rivy** [comment]
Well, we'll have to care about them as independent crates. They have to be for `coreutils` to be able to publish to crates.io. 

That's the process I'm working through right now with that WIP. I'll likely have a preliminary draft PR 
for the WIP in a couple of days.

I'm not sure how to test them as individual crates with PRs to `coreutils`, but I'll think about it. It might be too slow. But the publish process for all the sub-crates will have to have that as a step. That might be enough.

**Comment by rivy** [comment]
Ok, I'll merge this and work on the problem via #1496.

**Pull request merged**
