### PR TITLE
Remove unused dependencies by individual crates

### PR DESCRIPTION
**Pull request by bnjbvr**
Using a small tool of my creation to remove unused dependencies; I've seen that `cargo-udeps` was used, but I've found that it has a few imperfections, as it cannot detect unused dependencies of individual crates within a common workspace. This shouldn't bring large build time improvements, but it change the graph of crate dependencies and thus cause some little wins due to cargo pipelining effects. I haven't observed any improvement outside the range of noise here, unfortunately.

The tool I'm using can be imprecise, so I'm curious to see if CI will be happy with the changes...

### CODE REVIEW

**Comment by tertsdiepraam** [comment]
Excellent! Have you made the tool public?

**Comment by sylvestre** [comment]
Works great, many thanks :)

Maybe it is going to have a positive impact on:
https://github.com/uutils/coreutils-tracking/#binary-size-evolution
(refreshed tomorrow)

**Comment by bnjbvr** [comment]
> Excellent! Have you made the tool public?

It's open source and in my repos :eyes: but not yet officially public! I've wanted to write a small blog post announcement, explaining how it works and its limitations first.

**Comment by tertsdiepraam** [comment]
Very cool! Looking forward to it!

**Pull request merged**
