### PR TITLE
Clippy suggestions

### PR DESCRIPTION
**Pull request by kralo**
ran clippy with clippy::range-plus-one, clippy::redundant-closure-for-method-calls and fix those where I was confident this is

a) improvement to the reader
b) does not make lines longer, no additional imports

### CODE REVIEW

**Comment by sylvestre** [comment]
could you please update the CI to run these too ?
https://github.com/uutils/coreutils/blob/main/.github/workflows/code-quality.yml#L124

**Comment by kralo** [comment]
I left open what should happen with extremely long `redundant closures`.

Cases like these,
```
warning: redundant closure
   --> src/uu/tail/src/args.rs:197:22
    |
197 |                 .map(|s| s.as_str()),
    |                      ^^^^^^^^^^^^^^ help: replace the closure with the method itself: `std::string::String::as_str`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#redundant_closure_for_method_calls
    = note: requested on the command line with `-W clippy::redundant-closure-for-method-calls`

```

To my eyes, `std::string::String::as_str` is neither more readable, nor shorter.

**Comment by kralo** [comment]
> could you please update the CI to run these too ? https://github.com/uutils/coreutils/blob/main/.github/workflows/code-quality.yml#L124

done for the trivial ones currently passing

**Comment by sylvestre** [comment]
thanks :)

**Pull request merged**
