### PR TITLE
nice: adjust a test to make it pass

### PR DESCRIPTION
**Pull request by sylvestre**

### CODE REVIEW

**Comment by sylvestre** [comment]
`
Congrats! The gnu test tests/misc/nice-fail is no longer failing!
`

**Comment by tertsdiepraam** [comment]
This one might be more important to actually fix that some of the others, because the current implementation makes it impossible to distinguish between the exit codes of `nice` and of the command it runs. From the docs:

> 0 if no COMMAND is specified and the niceness is output
> 125 if ‘nice’ itself fails
> 126 if COMMAND is found but cannot be invoked
> 127 if COMMAND cannot be found
> the exit status of COMMAND otherwise

I'll see if I can get come up with an ergonomic workaround for that clap issue next week.

**Comment by sylvestre** [comment]
Sure thanks :)

**Comment by sylvestre** [comment]
@tertsdiepraam have you been able to investigate? thanks

**Comment by tertsdiepraam** [comment]
Not yet, I'm not sure when I'll get to it, but hopefully soon :)

**Comment by tertsdiepraam** [comment]
As soon as I posted that reply, I couldn't resist working on it immediately :) https://github.com/uutils/coreutils/pull/3457

**Comment by tertsdiepraam** [comment]
We can close this one now right? The test should be passing now or is there something I missed in the exit code PR?

**Comment by sylvestre** [comment]
yeah, thanks

**Pull request closed without merging**
