### PR TITLE
Format everything using rustfmt

### PR DESCRIPTION
**Pull request by Arcterus**
I ran everything through `rustfmt`, and it produced this ridiculous number of changes.  I would like to add `rustfmt` to the CI, but I will need to test whether it works correctly on Linux as on my Windows computer I needed to work around a variety of things to make `rustfmt` actually work correctly.

### CODE REVIEW

**Comment by Arcterus** [comment]
If there are any comments about the style feel free to say something.  There are some things that I thought actually looked nicer originally, so I am debating changing the configuration (or, more accurately, adding one).

**Comment by mpkh** [comment]
well I personally prefer 2 spaces indent and coma first multi-line lists but it's more up to you

**Comment by Arcterus** [comment]
I actually like using 3 spaces, but practically no one else does 😞.  Honestly I'm not even sure if comma-first is an option in `rustfmt`.  I don't think I've seen that in Rust code before.

**Comment by sean-** [comment]
Thank you for using an automated tool for managing code formatting.

**Comment by Arcterus** [comment]
No problem! :smile:

I think it was inevitable given that the code in one utility was sometimes formatted in a wildly different style than that of another utility due to the way the language developed.

**Pull request merged**
