### PR TITLE
shuf: accept multiple occurances of head-count argument

### LINKED ISSUE #3328: shuf: Accept multiple occurrences of head count argument
GNU accepts multiple occurrences of head count argument and chooses the min value among them. 

uutils does not accept multiple occurrences of head count argument.

GNU
```
shuf -i10-200 -n5 -n10
162
144
165
96
62

```

uutils
```
./target/debug/shuf -i10-200 -n5 -n10
error: The argument '--head-count <COUNT>' was provided more than once, but cannot be used multiple times

USAGE:
    ./target/debug/shuf [OPTION]... [FILE]
    ./target/debug/shuf -e [OPTION]... [ARG]...
    ./target/debug/shuf -i LO-HI [OPTION]...

For more information try --help

```

### PR DESCRIPTION
**Pull request by DevSabb**
Closes #3328

### CODE REVIEW

**Comment by DevSabb** [comment]
I am not sure why the `cargo fmt` is failing in CICD. I don't see any issues locally. Any suggestions?

```
Run ## `cargo fmt` testing of integration tests
Diff in /home/runner/work/coreutils/coreutils/tests/by-util/test_shuf.rs at line 202:
     let result = new_ucmd!()
         .args(&["-i10-200", "-n", "10", "-n", "5"])
         .succeeds();
-    result.no_stderr();    
+    result.no_stderr();
     let result_seq: Vec<&str> = result
         .stdout_str()
         .split('\n')
Error: ERROR: `cargo fmt`: style violation (file:'tests/by-util/test_shuf.rs', line:202; use `cargo fmt "tests/by-util/test_shuf.rs"`)
Error: Process completed with exit code 1.
```

**Comment by sylvestre** [comment]
tab vs space?

**Comment by DevSabb** [comment]
> tab vs space?

No. All spaces locally. I am running `cargo fmt` locally and not getting any changes. I'll merge the last line per suggestion and see what happens.

**Comment by sylvestre** [comment]
Is that expected?

`Error: GNU test failed: tests/misc/shuf. tests/misc/shuf is passing on 'main'. Maybe you have to rebase?`

**Comment by DevSabb** [comment]
> Is that expected?
> 
> `Error: GNU test failed: tests/misc/shuf. tests/misc/shuf is passing on 'main'. Maybe you have to rebase?`

Nope. Let me check.

**Comment by DevSabb** [comment]
> Is that expected?
> 
> `Error: GNU test failed: tests/misc/shuf. tests/misc/shuf is passing on 'main'. Maybe you have to rebase?`

We can see from the issue #3320 that tests/misc/shuf is marked as ERROR (in main). I am assuming the changes in this PR is marking the test as FAILED and hence the message in CICD. 

We could see from below that the FAIL count is increased with the decrease of ERROR count. The message above is misleading. The test was not passing on main rather it was in error.

```
Reference SHA1/ID: 6910b655322894ad898c8aad42302a12aa182012  reference/test-summary/gnu-result.json
Warning: Changes from main: PASS +0 / FAIL +1 / ERROR -1 / SKIP +0 
```

**Comment by sylvestre** [comment]
> We can see from the issue https://github.com/uutils/coreutils/issues/3320 that tests/misc/shuf is marked as ERROR (in main). I am assuming the changes in this PR is marking the test as FAILED and hence the message in CICD.

Oh, yeah, right. it is mentioned here:
https://github.com/uutils/coreutils/issues/3320

well done :)

**Pull request merged**
