### PR TITLE
touch: Respect -h when getting metadata

### PR DESCRIPTION
**Pull request by ysthakur**
Currently, if the `stat` function in the `touch` crate is used on a symlink, it will first try to get the metadata of the destination, even if the `follow` parameter is `false`. It will not get the metadata of the symlink itself if the symlink is not broken. It should now check `follow` first.

Minor change: the `failed to get attributes for {path}` context isn't currently being added to the error if the first `fs::metadata` call fails and `follow` is `true`. But this PR makes it so all errors have that context added to them. However, at some point in the past, it seems like all errors had that context added to them, so I figured it'd be fine (@tertsdiepraam tracked down [this commit](https://github.com/uutils/coreutils/commit/c3656e561cde70c2a860d11a5747c24387105b20) fixing an earlier issue).

<s>The tests I added should maybe not run on FreeBSD because there's apparently an issue with nanoseconds or something? I have no idea what the difference there is, but I figured I'd set the nanoseconds field to 0 and let the CI run, just in case that works.</s> Never mind, I added `#[cfg(not(target_os = "freebsd"))]` since there's not much chance of the specific behavior being tested here being different on FreeBSD.

### CODE REVIEW

**Comment by ysthakur** [comment]
@tertsdiepraam I don't know why some of the workflows are failing, but the failures don't seem to be related to `touch`?

**Comment by tertsdiepraam** [comment]
We'll see what this run does :)

We do get unrelated errors quite often unfortunately. Recently especially on windows. But don't worry, we'll still look at the PR if there are some failures.

**Comment by ysthakur** [comment]
Welp, still failing, but at least the failures on that run were only on Windows.

**Comment by tertsdiepraam** [comment]
Windows has been having problems recently. No need to worry about it (for you) 😄

**Comment by ysthakur** [comment]
Yay! Can we merge now?

**Pull request merged**
