### PR TITLE
ls improvments

### PR DESCRIPTION
**Pull request by pokeylope**
As a project to learn Rust, I've been working on making some improvements to ls. This adds a bunch of options such as color and sorting, improves the output, and cleans up a few other things.

Apologies for the mega-commit; since this was a learning effort, the full commit history was sort of a mess.

### CODE REVIEW

**Comment by mpkh** [comment]
`#![feature(slice_patterns)]` is some very new feature? @knight42 @jbcrail what do you think, it breaks stable travis, maybe there is some replacement for stable?

**Comment by jbcrail** [comment]
Feature extensions only work on nightly. We minimize their use when possible.

In this case, it looks like the slice pattern:
```
if let [k, v] = p[..] {
    map.insert(k,v);
```
can be replaced with:
```
if p.len() == 2 {
    map.insert(p[0], p[1]);
```

Not the prettiest, but it works.

**Comment by mpkh** [comment]
@jbcrail btw can we somehow #ifdef compiler version in code to write both realizations?

**Comment by jbcrail** [comment]
It looks we could, but the code needs to be in a function, instead of arbitrary expressions. [[Source]](https://chrismorgan.info/blog/rust-cfg_attr.html)
```
#![cfg_attr(feature = "nightly", feature(slice_patterns))]
fn foo() {
    if let [k, v] = p[..] {
        map.insert(k, v);
    }
}

#[cfg(not(feature = "nightly"))]
fn foo() {
    if p.len() == 2 {
        map.insert(p[0], p[1]);
    }
}
```

**Comment by knight42** [comment]
@mpkh @jbcrail 
Perhaps we can pass `--features=nightly` to cargo when building with nightly rustc?

**Comment by mpkh** [comment]
@knight42 how that can help? problems are in stable and beta builds

**Comment by knight42** [comment]
@mpkh Oh... I mean by passing `--features=nightly` to cargo, we are able to know that we are using nightly rustc in program and conditionally use some fansy features without breaking the builds.

**Comment by mpkh** [comment]
@knight42 I see. @pokeylope may you replace nightly features as @jbcrail suggested? (though it also would be nice to keep them conditionally as in this example https://github.com/uutils/coreutils/pull/926#issuecomment-236102395

**Comment by pokeylope** [comment]
Updated. Using slice patterns doesn't really improve things enough to justify the additional complexity of conditional compilation, so I just rewrote it as @jbcrail suggested.

**Comment by mpkh** [comment]
Thank you

**Pull request merged**
