### PR TITLE
`dd`: unset O_DIRECT flag on last chunk if irregular sized

### PR DESCRIPTION
**Pull request by cre4ture**
addresses #6078 (detailed, please read)

### CODE REVIEW

**Comment by sylvestre** [comment]
> GNU testsuite comparison:
> 
> ```
> Congrats! The gnu test tests/dd/direct is no longer failing!
> ```

nice :)

**Comment by sylvestre** [comment]
is it possible to add a test for this? thanks

**Comment by cre4ture** [comment]
sure. I can do that.
But I have a generaö question:
Is the gnu test enough? Or should we ensure that each functionality that the GNU test-suite validates is also validated by our own test suite?

**Comment by sylvestre** [comment]
> Is the gnu test enough? Or should we ensure that each functionality that the GNU test-suite validates is also validated by our own test suite?

We want to test it with own first. It is much faster to run ours. And way easier to hack.

**Comment by sylvestre** [comment]
could you please rebase this PR? thanks

**Comment by cre4ture** [comment]
I will rebase it. But the tests on android are not yet green. Merging needs to wait...

**Pull request closed without merging**
