### PR TITLE
add kill -l final new line #2644

### PR DESCRIPTION
**Pull request by Smicry**
Before this change:
```
$ /kill -l
EXIT HUP INT QUIT ILL TRAP ABRT EMT FPE KILL BUS SEGV SYS PIPE ALRM TERM URG
STOP TSTP CONT CHLD TTIN TTOU IO XCPU XFSZ VTALRM PROF WINCH INFO USR1 USR2 
```

After this change:
```
$ ./kill -l
EXIT HUP INT QUIT ILL TRAP ABRT EMT FPE KILL BUS SEGV SYS PIPE ALRM TERM URG STOP TSTP CONT CHLD TTIN TTOU IO XCPU XFSZ VTALRM PROF WINCH INFO USR1 USR2
```

### CODE REVIEW

**Comment by sylvestre** [comment]
Looks good but please add a test to make sure we don't regress. thanks

**Comment by sylvestre** [comment]
Failed on Windows:

```
---- test_kill::test_kill_list_final_new_line stdout ----
current_directory_resolved: 
run: /home/runner/work/coreutils/coreutils/target/debug/coreutils kill -l
---- test_kill::test_kill_list_final_new_line stderr ----
thread 'main' panicked at 'Stdout does not match regex:
EXIT HUP INT QUIT ILL TRAP ABRT BUS FPE KILL USR1 SEGV USR2 PIPE ALRM TERM STKFLT CHLD CONT STOP TSTP TTIN TTOU URG XCPU XFSZ VTALRM PROF WINCH POLL PWR SYS
', tests/common/util.rs:401:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


```

**Comment by Smicry** [comment]
> Failed on Windows:
> 
> ```
> ---- test_kill::test_kill_list_final_new_line stdout ----
> current_directory_resolved: 
> run: /home/runner/work/coreutils/coreutils/target/debug/coreutils kill -l
> ---- test_kill::test_kill_list_final_new_line stderr ----
> thread 'main' panicked at 'Stdout does not match regex:
> EXIT HUP INT QUIT ILL TRAP ABRT BUS FPE KILL USR1 SEGV USR2 PIPE ALRM TERM STKFLT CHLD CONT STOP TSTP TTIN TTOU URG XCPU XFSZ VTALRM PROF WINCH POLL PWR SYS
> ', tests/common/util.rs:401:13
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> ```

**Comment by Smicry** [comment]
> Failed on Windows:
> 
> ```
> ---- test_kill::test_kill_list_final_new_line stdout ----
> current_directory_resolved: 
> run: /home/runner/work/coreutils/coreutils/target/debug/coreutils kill -l
> ---- test_kill::test_kill_list_final_new_line stderr ----
> thread 'main' panicked at 'Stdout does not match regex:
> EXIT HUP INT QUIT ILL TRAP ABRT BUS FPE KILL USR1 SEGV USR2 PIPE ALRM TERM STKFLT CHLD CONT STOP TSTP TTIN TTOU URG XCPU XFSZ VTALRM PROF WINCH POLL PWR SYS
> ', tests/common/util.rs:401:13
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> ```

i'm checking it, i test it on linux , maybe the regex wrong.

**Comment by Smicry** [comment]
Tests/FreeBSD test suite failed.
```
error: could not compile `uu_stdbuf`

Caused by:
  process didn't exit successfully: `rustc --crate-name uu_stdbuf --edition=2018 src/uu/stdbuf/src/stdbuf.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 -C metadata=71ce057af4b25fdf -C extra-filename=-71ce057af4b25fdf --out-dir /Users/runner/work/coreutils/coreutils/target/debug/deps -C incremental=/Users/runner/work/coreutils/coreutils/target/debug/incremental -L dependency=/Users/runner/work/coreutils/coreutils/target/debug/deps --extern clap=/Users/runner/work/coreutils/coreutils/target/debug/deps/libclap-1971e6c6a73ab6fa.rmeta --extern tempfile=/Users/runner/work/coreutils/coreutils/target/debug/deps/libtempfile-54156030c5da4b9c.rmeta --extern uucore=/Users/runner/work/coreutils/coreutils/target/debug/deps/libuucore-696a0b1cb5b33b74.rmeta --extern uucore_procs=/Users/runner/work/coreutils/coreutils/target/debug/deps/libuucore_procs-366b997d72d61dc5.so` (signal: 9, SIGKILL: kill)
warning: build failed, waiting for other jobs to finish...
error: build failed
Error: The process '/usr/bin/ssh' failed with exit code 101
```

**Comment by Smicry** [comment]
fixed #2644

**Pull request merged**
