### PR TITLE
tee: add --no-stdout option

### PR DESCRIPTION
**Pull request by ghuls**
A --no-stdout option to tee to not write to standard output is quite useful when using tee to pipe the same input to multiple process substitutions.

It allows to write the following:

    zcat file.gz | coreutils tee --no-stdout >(wc -l -) >(wc -c -) >(md5sum - )

instead of needing to work around the fact that tee will always write to standard out:

    zcat file.gz | coreutils tee >(wc -l -) >(wc -c -) | md5sum -

or:

    zcat file.gz | coreutils tee >(wc -l -) >(wc -c -) >(md5sum - ) > /dev/null

### CODE REVIEW

**Comment by ghuls** [comment]
I don't expect it to be merged as it is not part of GNU coreutils, but I wished normal `tee` had this functionality nonetheless.

**Comment by tertsdiepraam** [comment]
In case someone else is as confused as I am: this does not work in fish, you need bash or zsh 😄

This is interesting, I'm not really against including it, since we already have a few extensions over GNU in uutils. I'm just not entirely convinced of how useful it is? Both alternatives seem pretty good to me? Has something like this ever been proposed in other projects?

You could even make a fairly simple function to do get this behaviour:
```bash
function mytee() {
    tee $@ > /dev/null
}
```

**Comment by ghuls** [comment]
No it is not proposed to other projects yet. I was hoping to find a `tee` like command that would write stdin to multiple filehandle only, but couldn't find one so far.

I had this issue a while back where it would be nice if all "files" could be process substitutions without needing the last command to be reading from stdout pipe of tee or redirecting the output to `/dev/null` as the inpu file can be several 10's of GB in compressed form.

```bash
# Get mapping statistics from BAM file:
#   - Read BAM file and write uncompressed BAM (still in binary format).
#   - Uncompressed BAM file is written to each samtools command with tee (writes to each specified file and stdout).
#   - samtools commands:
#       - Get samtools statistics with:
#           samtools stat "${bam}" > "${sampleId}.stat"
#       - Uniquely mapped reads (BWA):
#           samtools view -c -F 0x4 -F 0x100 -F 0x800 -e '! [XA] && ! [SA]' "${bam}"
#       - Fraction of total read pairs mapped confidently to genome (>30 mapq):
#           samtools view -c -F 0x4 -F 0x100 -F 0x800 -q 30 "${bam}"
#   - Only use threads for "samtools stat". Using it with any of the other samtools commands
#     makes everything slower than not using any threads at all.
samtools view -u "${bam}" \
  | tee \
        >(samtools view -c -F 0x4 -F 0x100 -F 0x800 -e '! [XA] && ! [SA]' - > "${sampleId}.uniquely_mapped_reads.txt") \
        >(samtools view -c -F 0x4 -F 0x100 -F 0x800 -q 30 - > "${sampleId}.fraction_total_read_pairs.txt") \
  | samtools stat -@ 2 - > "${sampleId}.stat"


# It would be much nicer to be able to write this instead as visually it is clearer that all process substitutions get the same decompressed BAM file as input.
samtools view -u "${bam}" \
  | coreutils tee --no-stdout \
        >(samtools view -c -F 0x4 -F 0x100 -F 0x800 -e '! [XA] && ! [SA]' - > "${sampleId}.uniquely_mapped_reads.txt") \
        >(samtools view -c -F 0x4 -F 0x100 -F 0x800 -q 30 - > "${sampleId}.fraction_total_read_pairs.txt") \
        >(samtools stat -@ 2 - > "${sampleId}.stat")
```

https://github.com/aertslab/PUMATAC/blob/main/src/bwamaptools/bin/mapping_summary.sh#L24-L28

**Comment by tertsdiepraam** [comment]
Are you expecting a performance benefit over the `/dev/null` approach with large files? I'd expect `/dev/null` to be handled pretty efficiently by kernel anyway. It should be close to a no-op right? There's probably _some_ redundant moving of data happening, but probably not significantly. I'd be great if you could do some comparisons with this patch and `/dev/null` using hyperfine!

**Comment by ghuls** [comment]
Seems indeed that `/dev/null` overhead is quite small:

```bash
# Commands with just cat:
tee_no_stdout () {
    bam='sample_id.bam'
    sampleId='sample_id'
    
    cat "${bam}" \
      | coreutils tee --no-stdout \
        >(cat - > "${sampleId}.uniquely_mapped_reads.txt") \
        >(cat - > "${sampleId}.fraction_total_read_pairs.txt") \
        >(cat - > "${sampleId}.fraction_total_read_pairs_q35.txt") \
        >(cat - > "${sampleId}.fraction_total_read_pairs_q37.txt")
}

tee_dev_null () {
    bam='sample_id.bam'
    sampleId='sample_id'
    
    cat "${bam}" \
      | coreutils tee \
        >(cat - > "${sampleId}.uniquely_mapped_reads.txt") \
        >(cat - > "${sampleId}.fraction_total_read_pairs.txt") \
        >(cat - > "${sampleId}.fraction_total_read_pairs_q35.txt") \
        >(cat - > "${sampleId}.fraction_total_read_pairs_q37.txt") \
        > /dev/null
}

tee_dev_null_gnu () {
    bam='sample_id.bam'
    sampleId='sample_id'
    
    cat "${bam}" \
      | tee \
        >(cat - > "${sampleId}.uniquely_mapped_reads.txt") \
        >(cat - > "${sampleId}.fraction_total_read_pairs.txt") \
        >(cat - > "${sampleId}.fraction_total_read_pairs_q35.txt") \
        >(cat - > "${sampleId}.fraction_total_read_pairs_q37.txt") \
        > /dev/null
}

export -f tee_no_stdout
export -f tee_dev_null
export -f tee_dev_null_gnu

❯  hyperfine -S bash tee_no_stdout tee_dev_null tee_dev_null_gnu
Benchmark 1: tee_no_stdout
  Time (mean ± σ):     16.874 s ±  0.184 s    [User: 0.413 s, System: 17.519 s]
  Range (min … max):   16.618 s … 17.107 s    10 runs
 
Benchmark 2: tee_dev_null
  Time (mean ± σ):     17.173 s ±  0.149 s    [User: 0.624 s, System: 17.594 s]
  Range (min … max):   16.905 s … 17.402 s    10 runs
 
Benchmark 3: tee_dev_null_gnu
  Time (mean ± σ):     17.138 s ±  0.182 s    [User: 0.549 s, System: 17.566 s]
  Range (min … max):   16.927 s … 17.518 s    10 runs
 
Summary
  'tee_no_stdout' ran
    1.02 ± 0.02 times faster than 'tee_dev_null_gnu'
    1.02 ± 0.01 times faster than 'tee_dev_null'
```

```bash
# Commands with slower troughput than cat:
tee_no_stdout () {
    bam='sample_id.bam'
    sampleId='sample_id'
    
    samtools view -u "${bam}" \
      | coreutils tee --no-stdout \
        >(samtools view -c -F 0x4 -F 0x100 -F 0x800 -e '! [XA] && ! [SA]' - > "${sampleId}.uniquely_mapped_reads.txt") \
        >(samtools view -c -F 0x4 -F 0x100 -F 0x800 -q 30 - > "${sampleId}.fraction_total_read_pairs.txt") \
        >(samtools view -c -F 0x4 -F 0x100 -F 0x800 -q 35 - > "${sampleId}.fraction_total_read_pairs_q35.txt") \
        >(samtools view -c -F 0x4 -F 0x100 -F 0x800 -q 37 - > "${sampleId}.fraction_total_read_pairs_q37.txt")
}


tee_dev_null () {
    bam='sample_id.bam'
    sampleId='sample_id'
    
    samtools view -u "${bam}" \
      | coreutils tee \
        >(samtools view -c -F 0x4 -F 0x100 -F 0x800 -e '! [XA] && ! [SA]' - > "${sampleId}.uniquely_mapped_reads.txt") \
        >(samtools view -c -F 0x4 -F 0x100 -F 0x800 -q 30 - > "${sampleId}.fraction_total_read_pairs.txt") \
        >(samtools view -c -F 0x4 -F 0x100 -F 0x800 -q 35 - > "${sampleId}.fraction_total_read_pairs_q35.txt") \
        >(samtools view -c -F 0x4 -F 0x100 -F 0x800 -q 37 - > "${sampleId}.fraction_total_read_pairs_q37.txt") \
      > /dev/null
}


tee_dev_null_gnu () {
    bam='sample_id.bam'
    sampleId='sample_id'
    
    samtools view -u "${bam}" \
      | tee \
        >(samtools view -c -F 0x4 -F 0x100 -F 0x800 -e '! [XA] && ! [SA]' - > "${sampleId}.uniquely_mapped_reads.txt") \
        >(samtools view -c -F 0x4 -F 0x100 -F 0x800 -q 30 - > "${sampleId}.fraction_total_read_pairs.txt") \
        >(samtools view -c -F 0x4 -F 0x100 -F 0x800 -q 35 - > "${sampleId}.fraction_total_read_pairs_q35.txt") \
        >(samtools view -c -F 0x4 -F 0x100 -F 0x800 -q 37 - > "${sampleId}.fraction_total_read_pairs_q37.txt") \
      > /dev/null
}

export -f tee_no_stdout
export -f tee_dev_null
export -f tee_dev_null_gnu

❯  hyperfine -S bash tee_no_stdout tee_dev_null tee_dev_null_gnu
Benchmark 1: tee_no_stdout
  Time (mean ± σ):     125.590 s ±  0.769 s    [User: 87.872 s, System: 113.330 s]
  Range (min … max):   124.853 s … 127.584 s    10 runs
 
Benchmark 2: tee_dev_null
  Time (mean ± σ):     124.985 s ±  0.406 s    [User: 89.045 s, System: 116.838 s]
  Range (min … max):   124.358 s … 125.817 s    10 runs
 
Benchmark 3: tee_dev_null_gnu
  Time (mean ± σ):     125.515 s ±  1.202 s    [User: 89.292 s, System: 117.374 s]
  Range (min … max):   124.452 s … 128.704 s    10 runs
 
Summary
  'tee_dev_null' ran
    1.00 ± 0.01 times faster than 'tee_dev_null_gnu'
    1.00 ± 0.01 times faster than 'tee_no_stdout'
```

**Comment by sylvestre** [comment]
I am sorry but, for now, I would like focus as much as possible on the GNU compat :(

**Comment by tertsdiepraam** [comment]
I agree, though it's a fun and nice addition, it's easy to work around without a performance hit. Thanks anyway!

**Pull request closed without merging**
