### PR TITLE
Disable test_when_piped_input_then_no_broken_pipe by default

### PR DESCRIPTION
**Pull request by sylvestre**
It is blocking the executions of the tests and I suspect it is breaking android

### CODE REVIEW

**Comment by sylvestre** [comment]
Android is green again \o/

**Comment by Joining7943** [comment]
Sorry. Yes, this test is pretty expensive and brute force. Perhaps, there is a more specific problem behind the randomness of the failures?

**Comment by sylvestre** [comment]
dunno but I haven't seen it failed for a while :)

**Comment by Joining7943** [comment]
However, nice :) 

Maybe it helps. At the time of writing the test in #3910, I haven't figured out why it actually failed. The fix attached to the test just stopped it failing with `tail` but also with `head` when both tools were expected to produce no output with options like `-c -0`.

**Pull request merged**
