### PR TITLE
split: return UResult from uumain() function

### PR DESCRIPTION
**Pull request by jfinkels**
See #2464.

### CODE REVIEW

**Comment by jfinkels** [comment]
Hmm this is not yet ready for merge; there are a few more `crash!()` calls in the Windows-specific part of this code.

**Comment by sylvestre** [comment]
is it now ok ? :)
thanks

**Comment by sylvestre** [comment]
it is now conflicting

**Comment by jfinkels** [comment]
I have resolved the style issue I mentioned in my previous comment and rebased on master.

**Comment by jfinkels** [comment]
Okay now it is ready to review again. Sorry about that.

**Pull request merged**
