### PR TITLE
Printf: Fix printf hex alternate zero

### PR DESCRIPTION
**Pull request by spineki**
# Summary

- Fixed case where giving only 0 would crash printf due to an attempt to read it as an octal
- Fixed wrong prefix for lower and upper hex alternative format. Now, the "0x" is not shown when the value is 0.

## Code
```
GNU:
> printf %#x 0
0

uutils: fails
now shows 0
```

Fixed an 

## Related issues:
original : https://github.com/uutils/coreutils/issues/5810
part of other changes (PR): https://github.com/uutils/coreutils/pull/5794
part of other changes: https://github.com/uutils/coreutils/issues/5709
octal similar problem: https://github.com/uutils/coreutils/issues/5807

### CODE REVIEW

**Comment by samueltardieu** [comment]
I would prefer this PR not to be merged as-is if the larger #5783 PR is merged, as it rewrites the parser used in `printf` and it doesn't have of the single 0 interpreted as octal already.

**Comment by tertsdiepraam** [comment]
@samueltardieu I agree. For clarity, you're suggesting to only keep the `0x` fix from this, right?

**Comment by samueltardieu** [comment]
> @samueltardieu I agree. For clarity, you're suggesting to only keep the `0x` fix from this, right?

Yes, and the associated tests.

**Comment by samueltardieu** [comment]
The failing test on MacOS/x86_64 seems unrelated.

**Comment by spineki** [comment]
I did the octal fix in the first place because `printf` would fail before reaching the 0x-prefix fix.
Thus, amonst the four new tests, those named xxxx_0 will fail without the octal fix, even if the prefix fix is kept.

It means that if you want to keep a subset of this PR without the octal fix, you can
- keep tests on lower hex and upper hex (not the 0 variant), but the prefix fix for 0 will not be tested.
- keep the 4 tests, but the xxx_0 tests variants will fail.

**Comment by tertsdiepraam** [comment]
Maybe we could try to merge @samueltardieu's PR first and then merge this. That should make everything alright, shouldn't it?

**Comment by tertsdiepraam** [comment]
I've rebased this on top of main after merging https://github.com/uutils/coreutils/pull/5783.

**Review by tertsdiepraam — APPROVED** [review]

**Pull request merged**
