### PR TITLE
maint/dev ~ merge 'uucore' back into 'coreutil'

### PR DESCRIPTION
**Pull request by rivy**

### CODE REVIEW

**Comment by rivy** [comment]
I'm just mopping up the residue of some experiments.
I will probably mark this ready for review in an hour or so.

Once it's merged, I should be able to update the version of everything together and publish it all fairly easily (🤞).

**Comment by rivy** [comment]
I'd like to have a better solution for the clippy complaint `temporary_cstring_as_ptr`, "fixed" by 2b4b31a9eec2c03805703a54e4510f79c35882ed. But, as discussed in the commit message, my straight-forward solution caused multiple failures for 'utmpx' users (specifically, `who`).

Any suggestions?

**Comment by rivy** [comment]
@uutils/maintainers , any other concerns?

If not, I’ll plan to merge tomorrow afternoon.

**Comment by sylvestre** [comment]
I think you can make it now :)
No need to wait.
I guess you did an import, adjust paths + some clippy fixes

**Review by sylvestre — APPROVED** [review]

**Pull request merged**
