### PR TITLE
Reorganize tests

### PR DESCRIPTION
**Pull request by knight42**

### CODE REVIEW

**Comment by Heather** [comment]
Appveyor is still being unhappy

**Comment by knight42** [comment]
@Heather 

Sorry for the delay. The latest failed test on linux(rust:beta) is caused by `test_tail::test_follow_multiple stdout`. Let's see if I can tackle this.

cc @mdsn BTW

**Comment by Heather** [comment]
@knight42 note travis build is buggy atm, sometimes it just needs the restart

**Comment by knight42** [comment]
:sweat: Anyway, they all got passed now.

**Pull request merged**
