### PR TITLE
expr: update onig crate to 6.3

### PR DESCRIPTION
**Pull request by alextibbles**
2nd attempt. Sorry for the noise.

### CODE REVIEW

**Comment by alextibbles** [comment]
```
error: failed to run custom build command for `onig_sys v69.7.1`
Error: failed to run custom build command for `onig_sys v69.7.1`
Caused by:
  process didn't exit successfully: `/target/release/build/onig_sys-86089fb6af0f65ce/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'Unable to find libclang: "couldn't find any valid shared libraries matching: ['libclang.so', 'libclang-*.so', 'libclang.so.*', 'libclang-*.so.*'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [])"', /cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.56.0/src/lib.rs:1922:31
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
Warning: error: build failed
Error: The process 'cross' failed with exit code 101
```

onig_sys changed from 69.1.0 to 69.7.1 in this PR.
https://github.com/rust-onig/rust-onig/issues/109

**Comment by alextibbles** [comment]
The alternative to the approach of supplying the libclang dependency seems to be to change usage of onig to disable the bindgen at build-time as of onig v5.
https://github.com/rust-onig/rust-onig/pull/126/files
```

[dependencies]
...
onig = { version = "~6.3", default-features = false }
```

A local test suggest this also works. Would you think this is preferable to adding a prerequisite?

**Comment by rivy** [comment]
> The alternative to the approach of supplying the libclang dependency seems to be to change usage of onig to disable the bindgen at build-time as of onig v5. https://github.com/rust-onig/rust-onig/pull/126/files
> 
> ```
> 
> [dependencies]
> ...
> onig = { version = "~6.3", default-features = false }
> ```
> 
> A local test suggest this also works. Would you think this is preferable to adding a prerequisite?

Yes, I think without a libclang dep.

[Onig docs](https://github.com/rust-onig/rust-onig#build-errors-caused-by-libclangllvm) say that  it's "faster and more reliable" compilation with "default-features = false". Sounds better all around.

**Comment by alextibbles** [comment]
I made the changes to disable bindgen etc. Only one failure in CI remaining:
```
 ---- test_ls::test_ls_indicator_style stdout ----
current_directory_resolved: 
mkdir: /tmp/.tmpsjvkpa/directory
touch: /tmp/.tmpsjvkpa/link-src
symlink: /tmp/.tmpsjvkpa/link-src,/tmp/.tmpsjvkpa/link-dest.link
is_symlink: /tmp/.tmpsjvkpa/link-dest.link
mkfifo: /tmp/.tmpsjvkpa/named-pipe.fifo
run: /home/runner/work/coreutils/coreutils/target/debug/coreutils ls --indicator-style=classify
run: /home/runner/work/coreutils/coreutils/target/debug/coreutils ls --ind=classify
run: /home/runner/work/coreutils/coreutils/target/debug/coreutils ls --indicator-style=file-type
run: /home/runner/work/coreutils/coreutils/target/debug/coreutils ls --ind=file-type
run: /home/runner/work/coreutils/coreutils/target/debug/coreutils ls --indicator-style=slash
run: /home/runner/work/coreutils/coreutils/target/debug/coreutils ls --ind=slash
run: /home/runner/work/coreutils/coreutils/target/debug/coreutils ls --classify
run: /home/runner/work/coreutils/coreutils/target/debug/coreutils ls --classify=always
run: /home/runner/work/coreutils/coreutils/target/debug/coreutils ls --classify=yes
run: /home/runner/work/coreutils/coreutils/target/debug/coreutils ls --classify=force
run: /home/runner/work/coreutils/coreutils/target/debug/coreutils ls --class
run: /home/runner/work/coreutils/coreutils/target/debug/coreutils ls --file-type
run: /home/runner/work/coreutils/coreutils/target/debug/coreutils ls --file
run: /home/runner/work/coreutils/coreutils/target/debug/coreutils ls -p
run: /home/runner/work/coreutils/coreutils/target/debug/coreutils ls --indicator-style=none
run: /home/runner/work/coreutils/coreutils/target/debug/coreutils ls --ind=none
run: /home/runner/work/coreutils/coreutils/target/debug/coreutils ls --classify=none
run: /home/runner/work/coreutils/coreutils/target/debug/coreutils ls --classify=never
thread 'test_ls::test_ls_indicator_style' panicked at ''lr-x------ 1 runner docker 64 Feb 14 00:05 /dev/fd/25000 -> pipe:[49079]
' contains '/' but should not', tests/common/util.rs:406:9


failures:
    test_ls::test_ls_indicator_style
```

This comes from tests/by-util/test_ls.rs:1583
It doesn't appear to be one of the files generated as test data "directory", "link-src", etc. It's a /dev file descriptor for the runner piping output somewhere, or test data from another case? I can't reproduce locally, with more parallelization than the CI runner admittedly.

**Comment by alextibbles** [comment]
I can't spot a relationship between a test failure in dd on Windows and the change here. Is there anything more I can do here?

**Comment by rivy** [comment]
> I can't spot a relationship between a test failure in dd on Windows and the change here. Is there anything more I can do here?

Transient failure. 
It's happening more recently (GitHub hardware issue?).

Ok on re-run.

**Pull request merged**
