### PR TITLE
mkdir: recursive reporting of created directories in verbose mode

### PR DESCRIPTION
**Pull request by 353fc443**
Related to #3214.

### CODE REVIEW

**Comment by sylvestre** [comment]
Could you please add a test to make sure we don't regress? Thanks

**Comment by 353fc443** [comment]
@sylvestre What is it about the test failure?

**Comment by 353fc443** [comment]
These GNU tests were failing previously 
> Error: GNU test failed: tests/mkdir/p-1. tests/mkdir/p-1
> Error: GNU test failed: tests/mkdir/p-2. tests/mkdir/p-2 

Fixed with 57b1121

Thanks :)

**Comment by sylvestre** [comment]
Are you sure? I only see
`Warning: Congrats! The gnu test tests/mkdir/p-v is now passing!`
(but still great :)

**Comment by 353fc443** [comment]
Nevermind It was for the previous tests. Thanks :)

**Pull request merged**
