### PR TITLE
Use `clap::ArgAction` in `true` and `false`

### LINKED ISSUE #3769: `true` and `false` can be simplified with `clap::ArgAction`
In `true` and `false`, we override clap's default help and version arguments. With clap 3.2, this can probably be simplified by using `clap::ArgAction::{Help, Version}`.

### PR DESCRIPTION
**Pull request by jarkonik**
Closes #3769

### CODE REVIEW

**Comment by jarkonik** [comment]
Seems like using `.action(ArgAction::Help)` on clap command builder cancels command conflict validation set with `.exclusive(true)`. Looks like it should be fixed upstream.

**Comment by tertsdiepraam** [comment]
Oh that's unfortunate. Could you make an issue in the clap repo with a minimal reproduction?

**Review by sylvestre — DISMISSED** [review]
not ready

**Comment by tertsdiepraam** [comment]
On second thought, I wonder if exclusive is the right thing to do here. Maybe we should just check whether the the number of arguments (i.e. argc) is 2 and check for `--help` and `--version`only if that's the case.

**Comment by tertsdiepraam** [comment]
Given the outcome of the issue on clap, I think my previous comment is the right way forward.

**Comment by jarkonik** [comment]
I've reimplemented the behaviour using argument count instead of `exclusive` flag as suggested

**Review by tertsdiepraam — APPROVED** [review]
Looks great!

**Pull request merged**
