### PR TITLE
cp: fix for gnu test case i-2 compatibility for `mv`

### PR DESCRIPTION
**Pull request by matrixhead**
fix for #6658 contains #6599

**Behaviors changed:**
- When the destination file is read-only and the `-i` flag is given, instead of prompting with something like `cp: overwrite 'f'?` cp will prompt with `unwritable 'f' (mode 0000, ---------); try anyway?`
-  When the destination file is read-only and the `-i` and `-f` flags are given, instead of prompting with something like `cp: overwrite 'f'?` cp will prompt with `cp: replace 'f', overriding mode 0000 (---------)?`. Additionally, this operation will no longer fail.
-

### CODE REVIEW

**Comment by sylvestre** [comment]
please let us know when it is ready to be reviewed

**Comment by sylvestre** [comment]
```
Congrats! The gnu test tests/cp/cp-i is no longer failing!
Congrats! The gnu test tests/mv/i-2 is no longer failing!
Congrats! The gnu test tests/mv/mv-n is no longer failing!
Congrats! The gnu test tests/mv/update is no longer failing!
```

Impressed by this btw
I don't remember the last time we fixed that many tests at the same time :)

**Comment by matrixhead** [comment]
😊 Thanks, that means a lot! Would it be possible to get a review for #6599? I know these PRs are a bit scattered—should I try to clean them up a bit more?

**Comment by sylvestre** [comment]
@matrixhead i am sorry, it is conflicting, could you please have a look ? sorry

**Comment by matrixhead** [comment]
@sylvestre Please don't be! It looks like #6700 offers a more refined solution to this problem. Thanks for the heads-up—I'll take a look and resolve the conflicts. 🙂

**Comment by matrixhead** [comment]
It looks like #6712 (which is a continuation of #6700) would fix the same issue this PR was intended to solve. Since #6700 has been merged, I think it would be better to close this PR in favor of #6712.

**Comment by matrixhead** [comment]
It looks like #6712 (which is a continuation of #6700) would fix the same issue this PR was intended to solve. Since #6700 has been merged, I think it would be better to close this PR in favor of #6712.

**Pull request closed without merging**
