### PR TITLE
add option to pass an input file of filenames to paste

### PR DESCRIPTION
**Pull request by julibeg**
Sometimes I need to merge a large number of files (tens of thousands), which usually gives `Argument list too long at` errors. Therefore, it would be nice if an input file holding a list of filenames could be passed to `paste` in addition to reading the filenames from the command line. This PR adds a CLI parameter `-f` for this behavior.

### CODE REVIEW

**Comment by julibeg** [comment]
I am aware that GNU `paste` does not have this functionality (which is a little annoying). Please delete this PR if you don't want to deviate from GNU `paste` (even though some tools in `coreutils` do.

**Comment by sylvestre** [comment]
I don't think we are ready to cross that bridge, sorry :(
(in parallel, it would need a test :)

**Comment by julibeg** [comment]
no worries!


>  (in parallel, it would need a test :)

yeah I wanted to wait and see if you'd incorporate it before writing the test haha

**Comment by tertsdiepraam** [comment]
I agree with Sylvestre. It might also just be asking a bit too much from a single command? Have you seen solutions like this? https://unix.stackexchange.com/questions/205642/combining-large-amount-of-files#205646

**Comment by julibeg** [comment]
> Have you seen solutions like this? https://unix.stackexchange.com/questions/205642/combining-large-amount-of-files#205646

I have, but my problem is not the maximum number of open files (I will need to change `ulimit -n` anyway), but rather that the command gets too long for the command line when bash expands a glob like `paste /my/dir/*.txt` (which throws `Argument list too long` errors -- these can be circumvented with setting `ulimit -s unlimited` to a certain extent, but at at some point the expanded command line is longer than `MAX_ARG_PAGES`, which is a kernel parameter and can't really be changed). Therefore, making this rather small change to `paste` itself was the simplest solution for me.

**Pull request closed without merging**
