### PR TITLE
Improve support on Windows/Redox

### PR DESCRIPTION
**Pull request by Arcterus**
There is only support for running `arch` on x86/x86_64 at the moment.

### CODE REVIEW

**Comment by mpkh** [comment]
```
error[E0432]: unresolved import `self::platform`
 --> src/uucore/utsname.rs:9:15
  |
9 | pub use self::platform::*;
  |               ^^^^^^^^ Could not find `platform` in `self`
```

strange error on nightly

**Comment by Arcterus** [comment]
Yeah, I need to add support for Redox.  I’ll probably do that tomorrow because I am currently busy.

**Comment by Arcterus** [comment]
`uname` now builds on Redox as well.

**Comment by Arcterus** [comment]
@mpkh this should be fine now.  You can ignore the `FIXME` in `utsname.rs` for now as I am currently moving the code into a separate crate and am in the process of fixing it.

Also I am not sure what's up with `codecov/patch` marking the commit as a failure, but given that the code is fine everywhere else I wouldn't worry about it right now.

**Pull request merged**
