### PR TITLE
Updated chgrp & chown

### LINKED ISSUE #982: Fix chgrp
I am on mobile, so please forgive my bad bug report.

Inside chgrp the check for root is not sufficent:
if f == "/" && self.preserve_root && self.recursive {

One also has to check for // since that will be translated to / as well.

### PR DESCRIPTION
**Pull request by knight42**
Fix #982

### CODE REVIEW

**Comment by Anachron** [comment]
Hey @Knight42 sorry for the delay. Indeed this is the correct way of handling it by traversing the file system and checking if there is a parent left.

I didnt test it yet but did you check if edge-cases like "/etc/../" are covered too?

**Comment by knight42** [comment]
@Anachron Ooops! An  edge-case like "/etc/../" wasn't covered, since "/etc/../" is independent to current dir hence considered absolute.

I will fix that in a new PR. BTW, could you think of other edge-cases?

**Comment by wimh** [comment]
@knight42 can you also verify if something like "/../" is handled correctly? (including "../.." when the current directory is "/tmp").

**Comment by Anachron** [comment]
@Knight42 I would also rule out situations like "//etc//..//." There are quite a few things to take care of. Maybe read the pathspec? I forgot quite a few things since I read it last time so my help may not be perfect.

**Pull request merged**
