### PR TITLE
github action: split the run of the fuzzers

### LINKED ISSUE #5443: github action: split the run of the fuzzers
Currently, we run all the fuzzers in the same task
image

instead, we should do:
* build the fuzzers into a dedicated task
* save the binaries as artifact
* run them into dedicated tasks (one per fuzzer)

### PR DESCRIPTION
**Pull request by tommady**
fix #5443
according to
- https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs
- https://docs.github.com/en/actions/examples/using-concurrency-expressions-and-a-test-matrix

### CODE REVIEW

**Comment by sylvestre** [comment]
Sorry, i didn't merge it
it is great. I am just a bit sad that we have to recompile it every time (3 minutes instead 1)
would it be possible to have the task running one after the other in the same VM ?

**Comment by tommady** [comment]
> Sorry, i didn't merge it it is great. I am just a bit sad that we have to recompile it every time (3 minutes instead 1) would it be possible to have the task running one after the other in the same VM ?

yes it can be, but if we do that it will miss the goal:
```
run them into dedicated tasks (one per fuzzer)
```
which I understand is running all the fuzz tests in parallel.
right?

**Comment by tommady** [comment]
or let me think of a way to reduce the compile time.

**Comment by tommady** [comment]
oh I am sorry, the fuzz test already using the 
```
- uses: Swatinem/rust-cache@v2
```
so I think there is nothing I can do right now 😞

**Comment by tommady** [comment]
Hi @sylvestre 
how about this
image

sorry for the misunderstanding
I thought the Swatinem/rust-cache@v2 action could cache everything,
but after reading the doc and the cargo-fuzz doc,
I found out I was so wrong.

please review this PR again while you have time.
thanks

**Comment by sylvestre** [comment]
This is perfect, many thanks

**Pull request merged**
