### PR TITLE
fsext solaris/illumos build fix

### PR DESCRIPTION
**Pull request by devnexen**

### CODE REVIEW

**Comment by sylvestre** [comment]
Looks great but would it be possible to add a github action task to make sure we don't regress? thanks

**Comment by sylvestre** [comment]
thanks for the CI, it fails with:
`E: Unable to locate package gar`

**Comment by devnexen** [comment]
ah I m not sure it s a fixable problem as such.

While other oses run under their own respective proper environments, github workflow does not support illumos image. gar stands for GNU ar which exists indeed under illumos. Plus it requires to pull numerous illumos libraries.

**Comment by sylvestre** [comment]
OK, let's just remove the CI patch then 
I will just take the patch and wait for new PR if it breaks :)

**Pull request merged**
