### PR TITLE
tail: Implement `tail -z`.

### LINKED ISSUE #849: Implement `tail -z` for null terminated (instead of '\n' terminated) lines
From `tail`'s man pge:

```
       -z, --zero-terminated
              line delimiter is NUL, not newline
```

### PR DESCRIPTION
**Pull request by ProgVal**
This options makes tail use NULL instead of newline as a line delimiter.

Closes #849.

### CODE REVIEW

**Comment by Heather** [comment]
@ProgVal will it work fine with `CLRF`?

**Comment by ProgVal** [comment]
It should treat them like any other character, as I removed any special treatment of `\n` (and `\r` already wasn't a special character)

Do you want me to add a test?

**Comment by Heather** [comment]
no, it's fine

**Comment by fitzgen** [comment]
Thanks, @ProgVal!

**Pull request merged**
