### PR TITLE
Add darwin aarch64 for M1 Macs

### PR DESCRIPTION
**Pull request by jurgen-kluft**
A single line addition to CICD.yml

### CODE REVIEW

**Comment by sylvestre** [comment]
The issue is
`Warning: `cross` does not provide a Docker image for target aarch64-apple-darwin,`

**Comment by jurgen-kluft** [comment]
Yes, seems there are no docker images (yet) for 'aarch64-apple-darwin', so the build can compile but cannot be run.
If you want we can close this pull-request for now, until it becomes more clear how to actually test this target?

**Comment by tertsdiepraam** [comment]
I found this in the cross README: https://github.com/cross-rs/cross-toolchains.

They cite some licensing issues for not being able to distribute apple images, so I don't think they'll add them any time soon, but I think we could use the cross toolchains.

**Comment by jurgen-kluft** [comment]
The only action we could do here is to build it but not run the unit-tests and rely on the other ARM platforms to give us a direction of failing tests? And adding a note in the release notes and or documentation stating that M1 builds are not tested.

Let me know so that we can close this pull-request.

**Comment by tertsdiepraam** [comment]
I think just building it is a good temporary solution until GitHub provides M1 runners.

**Comment by jurgen-kluft** [comment]
I have looked through the CICD setup, but how do I exclude something from test?

**Comment by tertsdiepraam** [comment]
I don't think we have an option for that, but I imagine that you could add a new variable to the build matrix to specify whether tests should be run.

**Pull request closed without merging**
