### PR TITLE
publishing: check if the current version is already there or not

### PR DESCRIPTION
**Pull request by sylvestre**
This can happen when a publishing step failed

### CODE REVIEW

**Review by cakebaker — COMMENTED** [review]
The code itself looks fine. I'm not sure about the API access because according to https://crates.io/data-access they allow "[a] maximum of 1 request per second"

**Review by tertsdiepraam — APPROVED** [review]
I'd like to explore external tools for this process as well, but I think we can discuss that in another issue.

**Comment by sylvestre** [comment]
Having worked with @gankra before, I am sure https://github.com/axodotdev/cargo-dist is an excellent candidate for this :)

**Comment by tertsdiepraam** [comment]
I love everything this axo does, but I don't think `cargo-dist` is the full solution here. They even say in the docs that some steps should be left to `cargo-release` (https://opensource.axo.dev/cargo-dist/book/workspaces/cargo-release-guide.html). I'd still love to try out `cargo-dist` though! Especially with all the talk around Windows installers recently.

**Pull request merged**
