### PR TITLE
timeout: avoid panicking for empty string

### PR DESCRIPTION
**Pull request by 353fc443**
Related to #3040

### CODE REVIEW

**Comment by sylvestre** [comment]
Could you please add a test to make sure we don't regress in the future? thanks

**Comment by 353fc443** [comment]
Hi, I'm unable to invoke the error from #3040

**Comment by sylvestre** [comment]
```
#[test]
fn test_command_fail() {
    new_ucmd!()
        .args(&["\"\"", "\"\""])
        .fails()
        .stderr_contains("thread 'main' panicked at");
}
```
works for me in `tests/by-util/test_timeout.rs`
(just replace the error message by the new one)

**Comment by 353fc443** [comment]
Unfortunately the error is not produced using the above test also @sylvestre

**Comment by sylvestre** [comment]
ok, i will give it a try :)
thanks

**Comment by sylvestre** [comment]
I created this:
https://github.com/uutils/coreutils/pull/3218
(the \" were not necessary)

**Pull request merged**
