### PR TITLE
cp: implemented no-clobber, recursive, link, interactive

### PR DESCRIPTION
**Pull request by jerenept**
Soon to come:  
- Tests for these options!  
- backup (suffix) and update!

### CODE REVIEW

**Comment by nathanross** [comment]
Looks good. One item:

Please eliminate the following commits.

- Merge branch 'master' of https://github.com/uutils/coreutils
- committed changes from upstream

Use rebasing, or, if you have to, just make a new branch from uutils master and do a manual diff., committed changes from upstream.

Also, just a comment: Feel completely at liberty to do maintainability refactors of pertinent code in a utility implementation when adding new functionality. If the convention of the file before was to store everything in one big function. I'm not suggesting you should let this slow you down if you'd rather implement a few options first, but you're also completely welcome to take on implementation structure if you'd like.

**Comment by jerenept** [comment]
sure! You could say my knowledge of Git is basically "memorize these six commands", so I'll rebase in the future.
Also I fixed that test.
I'll probably look into refactoring it since yeah, it does seem kinda messy

**Comment by nathanross** [comment]
Once you have rebased, just reply to this thread to notify me (if its in a new branch, making the PR itself will notify me).

If you would like help rebasing, here is a guide I wrote to help you out. 

The steps for fixing this PR would look something like this:

First make a local copy of your git repo, as a backup, separate from the working directory you'll be doing this in.

```bash
cp tests/test_cp.rs ~/
git reset --hard HEAD~3
mv ~/test_cp.rs tests/
git add tests/tests_cp.rs
git commit -m 'tests/cp: fix tests'
```

Now we do ```git log``` and you will see the first commit you made has an id starting with 5e03. We can see the commit just before it has an id starting with 40ae

Git tells us we can't do an automatic "fast forward" (that is, git can't figure out how to automatically transpose these changes on top of upstream). So let's do a fully manual rebase. 

First lets see the files you changed

```bash
git diff --name-only 5e03 HEAD
```

so these are the files you need to copy
```
src/cp/Cargo.toml
src/cp/cp.rs
tests/fixtures/cp/hello_dir/hello.txt
tests/fixtures/cp/hello_dir_with_file/hello_world.txt
tests/fixtures/cp/hello_dir_with_file/not_hello_world.txt
tests/fixtures/cp/not_hello_world.txt
tests/test_cp.rs
```

that looks right. lets back them up

```bash
git diff --name-only 5e03 HEAD | xargs tar -cf ~/git_backup.tar
```

 Now we would do a hard reset to the last upstream commit in your "base"

```bash
git reset --hard 40ae
```

Now we can definitely fast forward.

```bash
git remote add upstream https://github.com/uutils/coreutils.git
git pull upstream master
```

At this point you're going to see ```Your branch is behind 'origin/master' by 11 commits, and can be fast-forwarded.``` Ignore that.

Double check that you have your backup repo, your backup acrhive, etc., then run the following command.

```bash
git push --force origin master
```

Great. Your repo's master branch is up to date, both in your current directory and on github. Now let's make a new branch for the feature you're developing. Using feature branches makes it easier to frequently, automatically rebase to avoid the manual rebasing we are doing now. It also makes it easier to develop multiple features at once.

```bash
#creates the branch
git branch cp-opts
#switches to working in the branch
git checkout cp-opts
```

Now because of the way we're doing this, all the commits you made are going to be "squashed" into one or two single commits. Let's make them two commits:

```bash
tar xvf ~/git_backup.tar
git add -A tests
git commit -m 'tests/cp: tests for -i, -l, -n, -r options'
git add -A src
git commit -m 'cp: impl for -i, -l, -n, -r options'
```

great, our feature branch is done. Let's push to github.

```bash
git push origin cp-opts
```

Now go to the repository on github (either uutils/coreutils or your own) and there should be a yellow bar that says "you just pushed commits to this branch cp-opts, would you like to make a pull request." Then make a pull request.

**Comment by wimh** [comment]
@jerenept here is (another) description how to rebase. I rebases your changes as an example, I [pushed](https://github.com/wimh/coreutils/tree/cp_jerenept) the result to github for reference.

First I needed your changes and create a branch;

````
git remote add jerenept https://github.com/jerenept/coreutils.git
git fetch jerenept master
git checkout jerenept/master 
git checkout -b cp_jerenept
````

For the rebase, I added to execute `make test` after each commit, to pause the rebase if the tests would fail. (And `git checkout -- Cargo.lock` to make sure Cargo.lock was not modified after the test).

````
git fetch upstream master
git rebase --interactive --exec "make test" --exec "git checkout -- Cargo.lock" upstream/master
````

I removed these 6 lines from the textfile, so they will not be included in the rebase.
````
pick 38ef21f committed changes from upstream
exec make test
exec git checkout -- Cargo.lock
pick 3a22b8c fixed broken test
exec make test
exec git checkout -- Cargo.lock
````

Also I changed `pick` into `reword` for some commits, because the commit summary was too long, or did not have an empty line after the summary.

This was the (only) merge conflict.

````
    assert!(result_from_dir.success);
<<<<<<< HEAD
    assert_eq!(at.read(TEST_HELLO_WORLD_DEST), "Hello, World!\n");
}
=======
    assert_eq!(at.read(TEST_HELLO_WORLD_DEST), HELLO_WORLD_TEXT);
}

.....(more lines).....

    assert_eq!(at.read(TEST_NOT_HELLO_WORLD), NOT_HELLO_WORLD_TEXT);
}
>>>>>>> 9458ffc... cp: added test for the -n/--no-clobber option, and
````

There are gui tools to handle merge conflicts. In this case the top change can be ignored. So that has to be removed, including the lines starting with `<<<<`, `====` and `>>>>`. 

Then confirm the fixed merge conflict, and continue the rebase:

````
git add tests/test_cp.rs 
git rebase --continue 
````

Now I got a compiler error during the `make test`:

````
tests/test_cp.rs:69:27: 69:36 error: unresolved name `UTIL_NAME` [E0425]
tests/test_cp.rs:69     let ts = TestSet::new(UTIL_NAME);
````

After fixing this, you have to manually run `make test` to check if everything is fine now. 
Then the change must be added to the previous commit:

````
git add tests/test_cp.rs 
git commit --amend
git rebase --continue 
````

Next there were two tests failing. As I did not want to debug, I just added `#[ignore]` to disable those tests for now. But normally they should be fixed instead.

After the rebase was finished, I noticed the two failing tests were working again, so they were fixed in a later commit. I also saw some warnings during the rebase. It is probably better to fix those too.

**Comment by wimh** [comment]
@jerenept While looking at the source of cp, I also noticed that it uses `panic!` in case of user errors. I think `panic` should only be used if an internal error (bug) is detected. For wrong user input, or even an I/O error, an error message should be displayed (`disp_err!`), and the program should exit with a non-zero return code. Would you be able to change that too? (of course if @nathanross agrees with me).

**Comment by nathanross** [comment]
exits should be used instead of panics for a few reasons (more control over output, lower binary size). The best macro to use in uutils in situations where you would panic is ```crash!```. [Here are some examples of its usage](https://github.com/uutils/coreutils/search?utf8=%E2%9C%93&q=crash%21).

I wouldn't consider the panics a blocker, as there are plenty of panics in the code base that need to be replaced already. But if @jerenept wants to replace them with exits in this PR that's great.

**Comment by jerenept** [comment]
I'm closing this PR 'cause 1. it's super old and 2. I made some other changes as well (mostly, changing to crash! and also getting rid of the merge conflicts)

I'm bookmarking this for whenever I need to do a proper rebase again (I imagine I'll need to at some point, it's useful)
new PR:

**Pull request closed without merging**
