### PR TITLE
`release-fast` and `release-small` profiles and a page on packaging in the docs.

### PR DESCRIPTION
**Pull request by tertsdiepraam**
Inspired by https://github.com/uutils/coreutils/pull/4436 and https://github.com/uutils/coreutils/issues/747.

In the comments of #4436, I did an exploration of the binary size by trying different settings in cargo. The conclusion was that we can get the binary size down by a lot (even smaller than GNU), but that this will make bug reports less useful. Therefore, we should leave the exact configuration up to package maintainers. To document that, I've written a page on packaging this project in the docs. This page explains the best practices for the package name (since we had some issues there) and how to configure the package.

Additionally, to quickly see what our best performance and smallest binary size is, I've created the `release-fast` and `release-small` profiles in addition to the standard `release` profile. The `release` profile also has `lto` enabled, because that (probably) gives a performance boost and reduces the binary quite a bit, without removing any debug info, but compilation takes a bit slower. (I haven't benchmarked the performance and compile time though)

The change in `stdbuf` is because it was using the `PROFILE` env variable, which can only be `release` or `debug` and does not become, for example, `release-fast` and was therefore failing to compile.

@sylvestre, since you're packaging expert; is there anything else we should mention on the packaging page?

### CODE REVIEW

**Comment by tertsdiepraam** [comment]
Btw, we might need to advertise these alternative profiles a bit more after this. It be nice to not have people complain about binary size for once when this project makes the rounds again 😄

**Comment by sylvestre** [comment]
I think it would be nice to test both of them in the CI, don't you think ? :)

**Comment by tertsdiepraam** [comment]
Yes, I'll add that too!

**Comment by tertsdiepraam** [comment]
On second thought, maybe it's not that helpful to add in the CI? Apart from the anomaly with stdbuf, the profile should have very little effect on whether or not it compiles.

**Comment by sylvestre** [comment]
ok, you are probably correct :)

**Comment by tertsdiepraam** [comment]
@sylvestre I think this causes problems after all. Lot's of builds failing because of stdbuf. We should probably revert this.

**Comment by sylvestre** [comment]
@tertsdiepraam it improves it significantly:
https://raw.githubusercontent.com/uutils/coreutils-tracking/main/size-results.png
;)

**Comment by tertsdiepraam** [comment]
Nice! And that's just the lto change too.

> On second thought, maybe it's not that helpful to add in the CI? Apart from the anomaly with stdbuf, the profile should have very little effect on whether or not it compiles.

I'm not so sure about this anymore, it would be interesting to add it to the CI just for tracking the size.

**Pull request merged**
