### PR TITLE
gh action: fix the GNU testsuite job

### PR DESCRIPTION
**Pull request by sylvestre**

### CODE REVIEW

**Comment by nbraud** [comment]
@sylvestre That doesn't fix the fundamental flakiness problem with this testsuite.  I will just “work” until GNU pushes something to *their* coreutils repo that breaks it.

**Comment by sylvestre** [comment]
Sure but it doesn't have to be perfect. Many other testsuites have flaky tests

**Comment by nbraud** [comment]
So... the answer is to teach people to ignore CI because it sometimes breaks?  :unamused:

**Comment by sylvestre** [comment]
No, that it isn't always green and it is expected with 27 testsuites on different OS+hardware

**Comment by nbraud** [comment]
> No, that it isn't always green and it is expected with 27 testsuites on different OS+hardware

Eh, no?  The source of flakiness here is easily preventable, so I sent a PR with an alternative proposal.

**Comment by sylvestre** [comment]
please provide patches to fix them ;)

**Comment by sylvestre** [comment]
note that we are also experiencing some network issues on some worker from time to time
or install issues

**Pull request merged**
