### PR TITLE
Fixing `more` terminal resizing

### PR DESCRIPTION
**Pull request by hbina**
See the demo [here](https://youtu.be/icyXPw_Obuk).

Unfortunately, it does pose a substantial rewrite and does not match `more` behavior exactly.
But in my opinion, this is a lot simpler and better to use.
The goal is to consolidate all the logic into the struct `LineStateMachine`.

### CODE REVIEW

**Comment by tertsdiepraam** [comment]
Thanks for your contribution! You've done some really interesting things! I really like the resizing! You have 2 small regressions, because you don't show the next file in the prompt and don't implement `-d`. Would you agree that the best way to proceed is to merge https://github.com/uutils/coreutils/pull/2382 and then you can port the resizing to that version?

**Comment by hbina** [comment]
Yea, I intentionally disabled those features because I wanted to take it step by step. I am new to writing terminal CLI apps in the first place. Just learning about crossterm.

**Comment by tertsdiepraam** [comment]
> I am new to writing terminal CLI apps in the first place. Just learning about crossterm.

You're doing great! I'll merge that PR then. Let me know if you need any guidance!

**Comment by hbina** [comment]
Closing this in favor of https://github.com/uutils/coreutils/pull/2407

**Pull request closed without merging**
