### PR TITLE
Made cksum return an error if used on a directory.

### PR DESCRIPTION
**Pull request by Ato2207**
This PR should fix https://github.com/uutils/coreutils/issues/5805. Now an error is generated if `cksum` is used on a directory and it returns an exit code of `1`.

### CODE REVIEW

**Comment by Ato2207** [comment]
I tried making the second test work on all algorithms in a loop like some previous tests but I couldn't figure a way.I would gladly change it if it is possible to do.

**Comment by Ato2207** [comment]
Couldn't make the last test work by creating a temporary path + directory, so I used one already existing.

**Comment by cakebaker** [comment]
Sorry, a rebase is needed :|

For creating a temporary directory in `test_all_algorithms_fail_on_folder` you can use a `TestScenario`, something like:
```
let scene = TestScenario::new(util_name!());
let at = &scene.fixtures;
at.mkdir("some_name");

for algo in ALGOS {
    scene
        .ucmd()
        ...
}
```

**Comment by Ato2207** [comment]
Should be ok now I think.

**Comment by Ato2207** [comment]
Should be ok now I think.

**Comment by cakebaker** [comment]
Thanks!

It's almost complete, though there is still an issue with the example from https://github.com/uutils/coreutils/issues/5805 if more than one item is specified. The `show!` macro might be helpful for this.

**Comment by Ato2207** [comment]
Wouldn't that be automatically solved when https://github.com/uutils/coreutils/issues/5809 is merged?

**Comment by cakebaker** [comment]
No, https://github.com/uutils/coreutils/issues/5809 is about showing an error when a specified file doesn't exist, whereas this PR is about showing an error when a directory is specified.

**Comment by Ato2207** [comment]
My bad, I understand.Should be ready now.

**Comment by cakebaker** [comment]
Thanks!

**Pull request merged**
