### PR TITLE
ls: Add more things to the cache

### PR DESCRIPTION
**Pull request by hbina**
Adds more things to the cache (using `OnceCell` for things that are obtained from `Metadata`). Some of this also perform allocations so its quite useful.

### CODE REVIEW

**Comment by hbina** [comment]
Admittedly, not that often. When we call `ls -l` for example, `display_*` are called twice: to calculate the paddings and to print the item. Its quite expensive too, because they actually allocate memory.

**Comment by kimono-koans** [comment]
Interesting.  I thought all that data was in the metadata struct.  

I'd avoid like the plague allocating.  Perhaps you could cache those items per directory?  Like we do at: `fn cached_uid2usr` ?  Anyway I'm no expert.

**Comment by tertsdiepraam** [comment]
@hbina could you do some benchmarks for this change? I'm curious how big the performance improvement is in practice.

**Comment by hbina** [comment]
@tertsdiepraam I tested it a bit and the performance difference is negligible. See

my branch
```shell
hbina@akarin ~/g/uutils (hbina-ls-cache-display_size_or_rdev)> cargo build --release && hyperfine --warmup 3 '~/git/uutils/target/release/ls -lR ~/git/linux'
Benchmark 1: ~/git/uutils/target/release/ls -lR ~/git/linux
  Time (mean ± σ):     822.9 ms ±   6.5 ms    [User: 524.6 ms, System: 295.3 ms]
  Range (min … max):   811.6 ms … 832.7 ms    10 run
```

ls
```shell
hbina@akarin ~/g/uutils (hbina-ls-cache-display_size_or_rdev)> hyperfine --warmup 3 'ls -lR ~/git/linux'
Benchmark 1: ls -lR ~/git/linux
  Time (mean ± σ):     881.1 ms ±  18.5 ms    [User: 326.3 ms, System: 549.7 ms]
  Range (min … max):   850.0 ms … 913.9 ms    10 runs
```

main branch
```shell
hbina@akarin ~/g/uutils (main) [SIGINT]> hyperfine --warmup 3 '~/git/uutils/target/release/ls -lR ~/git/linux'
Benchmark 1: ~/git/uutils/target/release/ls -lR ~/git/linux
  Time (mean ± σ):     830.6 ms ±  20.3 ms    [User: 516.0 ms, System: 311.4 ms]
  Range (min … max):   809.6 ms … 879.2 ms    10 runs
```
 
It fluctuates a lot from run to run so I am not sure what's the best way to benchmark it. But I suspect 1 single alloc is at worse just a rounding error especially for something so small.

**Comment by tertsdiepraam** [comment]
If the performance difference is negligible, I'm not sure this is a good idea, because it adds quite a bit of complexity. A small tip for using hyperfine btw: you can make it run multiple commands in sequence that it will compare, which can be really helpful in these kinds of cases. For example:
```
hyperfine --warmup 3 \
    '~/git/uutils/target/release/ls -lR ~/git/linux' \
    '~/git/uutils/target/release/ls-old -lR ~/git/linux' \
```
Is there another reason for this change besides performance?

**Pull request closed without merging**
