### PR TITLE
first draft of join

### PR DESCRIPTION
**Pull request by GianBra**
Hi, 
This is my very first pull request, and I'm learning Rust.

This is only a first draft that does not support many features of join, but i will keep working on it.
I really appreciate your feedback.

### CODE REVIEW

**Comment by Heather** [comment]
@jbcrail may you review this

**Comment by jbcrail** [comment]
@Heather I'll gladly review the PR.

**Comment by Heather** [comment]
@Gianbaoluo may you re-base it?

**Comment by Gianbaoluo** [comment]
Hi, I did some changes to the program, (sorry me too for the delay)
what do you mean by "re-base" it? I searched a little bit on the web but it is not so clear. 
Is my first time using github on a big project, so I still don't know many things.

**Comment by Heather** [comment]
@Gianbaoluo sorry for delay, currently this pull request desychronized and contains few terrible merges, ideally we need full rework commit history for this (or harder: dropping last merge with interactive rebase and rebasing on top of master, it's complicated to explain how to rebase but there are many tutorials) thanks for your time, tell if we can help there somehow

**Comment by timofonic** [comment]
@GianBra @jbcrail @mpkh @RGafiyatullin @nathanross Any news about this?

**Pull request closed without merging**
