### PR TITLE
gnu/test: add the iso en_us locale to help with some tests

### LINKED ISSUE #2754: GNU test CI needs some more locale work
I fixed some issues in https://github.com/uutils/coreutils/pull/2753 for the tr PR ( https://github.com/uutils/coreutils/pull/2502 )

but we still have this one

`./tests/misc/sort-float.sh: line 58: warning: setlocale: LC_ALL: cannot change locale (none): No such file or directory`

Core: https://github.com/coreutils/coreutils/blob/master/tests/misc/sort-float.sh#L58

### PR DESCRIPTION
**Pull request by sylvestre**
Closes #2754

We are regressing deliberately because they are actual issues.
* `expr` with multibytes: https://github.com/uutils/coreutils/issues/3132
* `sort -k` isn't working well with other locales: https://github.com/uutils/coreutils/issues/3123

### CODE REVIEW

**Comment by sylvestre** [comment]
Failed because
`Warning: Changes from master: PASS -2 / FAIL +3 / ERROR +0 / SKIP -1 `
Reasons:

```
Error: GNU test failed: tests/misc/expr-multibyte. tests/misc/expr-multibyte is passing on 'master'. Maybe you have to rebase?
Error: GNU test failed: tests/misc/sort-debug-keys. tests/misc/sort-debug-keys is passing on 'master'. Maybe you have to rebase?
Error: GNU test failed: tests/misc/sort-month. tests/misc/sort-month is passing on 'master'. Maybe you have to rebase?
```

**Comment by sylvestre** [comment]
tests/misc/sort-month failing is https://github.com/uutils/coreutils/issues/3123

**Comment by sylvestre** [comment]
tests/misc/sort-debug-keys fails on https://github.com/coreutils/coreutils/blob/master/tests/misc/sort-debug-keys.sh#L321-L334

**Comment by sylvestre** [comment]
@tertsdiepraam I think we should merge it if you are ok with it
@jfinkels what do you think ? :)

**Comment by sylvestre** [comment]
The clippy warning is already fixed: https://github.com/uutils/coreutils/pull/3124

**Comment by tertsdiepraam** [comment]
I was waiting for jfinkels, but sure :)

**Comment by jfinkels** [comment]
Hi! I think this will be great for revealing more errors. I don't know much about using locales (I'm on `en_US.UTF-8` and I don't speak other languages, unfortunately) but I'm happy to learn. Does this affect the `Quotable` trait?

**Pull request merged**
