### PR TITLE
CICD: add CARGO_TERM_COLOR env var for colors in CI output

### PR DESCRIPTION
**Pull request by tertsdiepraam**
This hopefully makes the CI output a bit prettier :)

EDIT: Seems to have worked mostly. I want to figure out how to also enable color in the tests though.

### CODE REVIEW

**Comment by tertsdiepraam** [comment]
Great, apparently it's due to an issue open since 2015 :)

https://github.com/rust-lang/cargo/issues/1983

**Comment by tertsdiepraam** [comment]
Well, I can't get it to work in `cargo test`. I remove those changes and leave that for later.

**Comment by sylvestre** [comment]
While I log colors, i am not a big fan in the CI. it is clobbering the raw logs:
https://pipelines.actions.githubusercontent.com/serviceHosts/91055393-6e6f-4662-ba97-3acee74a8c7c/_apis/pipelines/1/runs/20716/signedlogcontent/6?urlExpires=2023-01-27T20%3A12%3A46.9850910Z&urlSigningMethod=HMACV1&urlSignature=gbO%2Be6ji8njlwtpV7mcX87sxHkEn2Ak7VdOYlUatM1o%3D

```

2022-12-06T07:55:24.0549810Z [0m[0m[1m[32m   Compiling[0m proc-macro-error v1.0.4
2022-12-06T07:55:25.6700050Z [0m[0m[1m[32m   Compiling[0m num-bigint v0.4.3
2022-12-06T07:55:25.7502200Z [0m[0m[1m[32m   Compiling[0m lock_api v0.4.9
2022-12-06T07:55:26.2127390Z [0m[0m[1m[32m   Compiling[0m filetime v0.2.18
```

**Comment by tertsdiepraam** [comment]
Sure, I don't look at the raw logs much, but if you think it's important we can close this PR.

**Pull request closed without merging**
