### PR TITLE
Remove unnecessary permissions

### PR DESCRIPTION
**Pull request by sylvestre**

### CODE REVIEW

**Comment by sylvestre** [comment]
@tertsdiepraam 
hmm, the output seems incorrect?

**Comment by tertsdiepraam** [comment]
Strange... Maybe it's getting the data from another PR? Or it's from an earlier run? Another improvement would be to add a link to the run so we can easily check the full results it's referring to.

**Comment by tertsdiepraam** [comment]
Oh nevermind it's actually mentioning tee three times. That makes no sense.

**Comment by tertsdiepraam** [comment]
Okay the artifact matches the text we see, so the problem is in GnuTests.

**Comment by tertsdiepraam** [comment]
Ah I think it downloads the previous log here:
```yaml
- name: Retrieve reference artifacts
      uses: dawidd6/action-download-artifact@v2
      # ref: <https://github.com/dawidd6/action-download-artifact>
      continue-on-error: true ## don't break the build for missing reference artifacts (may be expired or just not generated yet)
      with:
        workflow: GnuTests.yml
        branch: "${{ steps.vars.outputs.repo_reference_branch }}"
        # workflow_conclusion: success ## (default); * but, if commit with failed GnuTests is merged into the default branch, future commits will all show regression errors in GnuTests CI until o/w fixed
        workflow_conclusion: completed ## continually recalibrates to last commit of default branch with a successful GnuTests (ie, "self-heals" from GnuTest regressions, but needs more supervision for/of regressions)
        path: "${{ steps.vars.outputs.path_reference }}"
```

I'll put up a PR

**Review by tertsdiepraam — APPROVED** [review]

**Pull request merged**
