### PR TITLE
when building for the GNU testsuite, force the build of selinux binaries

### PR DESCRIPTION
**Pull request by sylvestre**

### CODE REVIEW

**Comment by tertsdiepraam** [comment]
Interesting. Are we able to test these utils with the current CI setup or will this just build it and then fail at runtime?

**Comment by sylvestre** [comment]
I don't think it is doing than building

**Comment by tertsdiepraam** [comment]
Okay! Since the GNU error is expected from https://github.com/uutils/coreutils/pull/3335, I'll merge this.

**Review by jfinkels — COMMENTED** [review]
:+1:

**Pull request merged**
