### PR TITLE
cache .cargo. TODO: decide `fetch` each time or commit `Cargo.lock`

### PR DESCRIPTION
**Pull request by KeenS**
see #768 .

### CODE REVIEW

**Comment by Heather** [comment]
@ebfe what do you think about committing `Cargo.lock` ?

**Comment by steveklabnik** [comment]
@Heather the convention is usually that binaries have Cargo.lock checked into source control, so :+1: to me

**Comment by Heather** [comment]
@ebfe @KeenS in this case should we add lock in this pull request?

**Comment by ebfe** [comment]
As we still need rust nightlies and thus generally want the lastes version of our dependencies, I don't really see the point/advantage of having a Cargo.lock committed. I was hoping someone has arguments for it except "everyone does it".

**Comment by steveklabnik** [comment]
It makes your builds repeatable. Without that, you're at the whim of whatever versions get pulled down, and hope that no nightly changes between things have broken stuff.

**Comment by ebfe** [comment]
It's not really a repeatable build without the same rust compiler. If the Cargo.lock references dependency versions that are too old to compile with the rust nightly I just downloaded I have the same problem. 

Now I can see the advantages if we could say we build with rust 1.5. But thats currently not the case.

**Comment by ebfe** [comment]
Either way I don't care too  much, if it makes people happy...

**Comment by Heather** [comment]
@ebfe you're right, what time does it take to perform cargo update?

**Comment by ebfe** [comment]
> @ebfe you're right, what time does it take to perform cargo update?

Seconds

**Comment by Heather** [comment]
@ebfe @steveklabnik then it should be for sure better... isn't it?

**Comment by jbcrail** [comment]
I remember reading recently that starting in January Cargo will strongly suggest that packages not use "*" for dependencies. It's not related to the lock issue, but this might be a good time to start using stricter versioning.

**Comment by Heather** [comment]
I see... though I will just accept first pull requests that does either adding lock file or cargo update

**Pull request merged**
