### PR TITLE
CICD maintainence

### PR DESCRIPTION
**Pull request by rivy**
- `outputs()` function update throughout
- increased baseline SHA ref size to 10 hex digits
- spell-checker updates
- cosmetic comment changes

### CODE REVIEW

**Comment by sylvestre** [comment]
> increased baseline SHA ref size to 10 hex digits

why?

**Comment by rivy** [comment]
> > increased baseline SHA ref size to 10 hex digits
> 
> why?

It's a heuristically generated number of digits, increasing the uniqueness of the SHAs, and decreasing the chance of name "collisions" when referring to a specific SHA.

I'm following `git`'s lead here... you may notice that `git` is now displaying 9-digit SHAs when displaying one-line logs. I'm increasing to 10 digits as a convenient, common sized, number for future-proofing. We could go to 12 digits if you'd like, but giving the likely doubling time of the number of commits, it seems likely it will take another decade of commits before we reach higher chances of collisions at 10 digits.

Is there some downside I'm not seeing?

**Comment by sylvestre** [comment]
no, i was just curious :)
Not sure that it is a real problem but no worries :)

**Comment by rivy** [comment]
> no, i was just curious :) Not sure that it is a real problem but no worries :)

Agree, but I wanted to make the change before it ever became a problem.

**Pull request merged**
