### PR TITLE
0.0.17 => 0.0.18

### PR DESCRIPTION
**Pull request by sylvestre**

### CODE REVIEW

**Comment by anastygnome** [comment]
From the time changelog 

- An API has been added to opt out of soundness checks for obtaining the local offset. This replaces
  the previous, officially unsupported `RUSTFLAGS="--cfg unsound_local_offset"`. End users may call
  `time::util::local_offset::set_soundness(time::util::local_offset::Soundness::Unsound)`. This
  method is `unsafe` because it enables undefined behavior if its safety requirements are not
  upheld. Note that libraries **must not** set this to `Unsound`, as it is impossible for a library
  to guarantee end users uphold the required invariants.

**Comment by sylvestre** [comment]
yeah, not sure how to fix that :/

**Comment by tertsdiepraam** [comment]
It's because you updated cargo lock I believe. We've seen this before here: https://github.com/uutils/coreutils/issues/4489

**Comment by sylvestre** [comment]
yeah, my point was more "how do we fix this specific issue" :)

i updated cargo.lock because one of the jobs was complaining. I will have a look

**Comment by tertsdiepraam** [comment]
I think I fixed it (at least it works locally), but I put it in a separate PR, so we can see the CI results first.

**Comment by anastygnome** [comment]
@tertsdiepraam apparently the android CI complains rust & cargo aren't installed. 
Maybe we should modify the script in another PR?

**Comment by anastygnome** [comment]
@tertsdiepraam apparently the android CI complains rust & cargo aren't installed. 
Maybe we should modify the script in another PR?

**Pull request merged**
