### PR TITLE
Partially fix build with rust master

### PR DESCRIPTION
**Pull request by ebfe**
This fixes some more utils.

Still broken:

base64 chmod chroot cut du fmt ~~hashsum~~ id mkfifo nice nl nohup realpath relpath sort split tee test touch tr tsort unexpand uptime users whoami

### CODE REVIEW

**Comment by Arcterus** [comment]
Would you mind squashing these?

**Comment by Heather** [comment]
@Arcterus I think squashing everytime is not necessary, and maybe even worse when commits are logically separated. Just question: why don't let it go as is?

**Comment by Arcterus** [comment]
I think it's better to squash very minor commits that pertain to a specific group of changes.

For example, e2eba70 just changes `ptr.is_not_null()` to `!ptr.is_null()`.  This change is very small.  So are 18f199a, 0e6e142, etc.  I think all of these ones should be squashed as they pertain to changes in Rust.

However, I think 4935dcd and 7276b93 should remain separate commits (or maybe you could squash those two together, but still keep them separate from the big one about changes in Rust) because they aren't directly due to changes in Rust, but rather updates to `rust-crypto` and `time`.

I didn't have much time to write this, so I'm not sure I've explained my opinion very well.

**Comment by Arcterus** [comment]
Basically, I'm okay with doing things this way within reason, but I think it's going to get very messy very fast due to changes in the Rust compiler breaking things all the time.

**Comment by ebfe** [comment]
> Basically, I'm okay with doing things this way within reason, but I
> think it's going to get very messy very fast due to changes in the
> Rust compiler breaking things all the time.

The main to reason why I split these up is that I think it is easier to
review several small commits that each solve a single problem rather
than having a big commit that makes dozens of unrelated changes. I also
think the history is slighty more useful with commits like
"Vec::from_elem removal" instead of "Fixed build". Of course this bloats
up the history somewhat and one could argue that it makes bisecting more
difficult since we have now more commits that don't compile, but with
rust making incompatible changes every other day bisecting isn't an
option anyway. 

Either way I squashed the commits.

**Pull request merged**
