### PR TITLE
split: error when num. of chunks is greater than num. of possible filenames

### PR DESCRIPTION
**Pull request by ndd7xv**
Addresses https://github.com/uutils/coreutils/issues/3106.

Since it was tangentially related, I added support for hexadecimal suffixes `-x`/`--hex-suffixes` (and tests) in two additional commits as a part of this PR. Let me know if I should save it for another issue or scrap it altogether by resetting to the first commit - I'm sure there are plenty of tweaks I should make before it gets merged, and I'm always more than willing to answer any questions.

### CODE REVIEW

**Comment by tertsdiepraam** [comment]
Nice! There's already a PR open for hex suffixes I believe (#2981). Could you check what the differences are?

**Comment by tertsdiepraam** [comment]
Wow those PRs are _very_ similar 😄 Like, most of the time even using the same variable names and (almost) the same tests. Given the similarities we have to dive deep into some small details. Here's what I can find:
- Names for the enum variants. I find `Default` not descriptive enough, so I would at least change that.
```rust
// #3146 (this PR)
pub enum SuffixType {
    Default,
    Numeric,
    Hexadecimal,
}
// #2981
pub enum SuffixType {
    Alphabetic,
    NumericDecimal,
    NumericHexadecimal,
}
// I would propose:
pub enum SuffixType {
    Alphabetic,
    Decimal,
    Hexadecimal,
}
```
- #2981 has a method for getting the radix from the `SuffixType` which is nice.
- #2981 updates the documentation of the some functions to reflect the addition of hex.
- This PR passes the `SuffixType` by reference, instead of by value (due to the new clippy lints?)
- This PR adds the error for when the suffix is too small of course.
- The conversion to hex. I'm not sure what the best option here is
```rust
// #3146 (this PR)
const HEX_DIGITS: [char; 16] = [
    '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'a', 'b', 'c', 'd', 'e', 'f',
];
HEX_DIGITS[*d as usize]
// #2981
(if *d < 10 { b'0' + d } else { b'a' + (d - 10) }) as char
// A third option:
const HEX_DIGITS: &[u8; 16] = b"0123456789abcdef";
HEX_DIGITS[*d as usize] as char
// A fourth option:
std::char::from_digit(d, 16).unwrap()
```
- Help text. I have no strong preference here.
```
// #3146 (this PR)
use hex suffixes instead of alphabetic
// #2981
use hex suffixes starting at 0, not alphabetic
```

Finally, both convert to the radix to then match on the radix, which is a bit inconvenient. Ideally, `FixedWidthNumber` and `DynamicWidthNumber` are both passed the `SuffixType` so that they can directly match on that, but that's not a big issue.

My suggestion would be to take the best of both PRs based on what I have outlined above and put it into this PR (with the `Co-authored by` field of the commit set to @jfinkels).

**Comment by ndd7xv** [comment]
Doh! I'll take this as a lesson to check if there's an existing PR - I definitely would've cherry-picked @jfinkels commits. I'll make improvements based off that PR and the suggestions of @tertsdiepraam and you know when it should be looked at again.

For self reference (and unless this isn't the way to coauthor you can correct me), I'm leaving this link so that I remember to add jfinkels as a coauthor to the -x support commits:
https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors

**Comment by jfinkels** [comment]
You could just rebase your last commit on top of my branch and advocate for the pull request #2981 to get merged.

**Review by tertsdiepraam — APPROVED** [review]

**Pull request merged**
